[tool.poetry]
name = "rede-cotabest"
version = "1.0.2"
description = ""
authors = ["Fernando Coutinho <fernando.coutinho@cotabest.com.br>"]
packages = [
    { include = "maxipago" }
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
