
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T15:31:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "42bed5943c7ec8e8eec7d178d3282faa136280a2",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
