[tool.poetry]
name = "amora"
version = "0.1.1"
description = "Amora Data Build Tool"
authors = ["diogommartins <diogommartins.dev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9.6,<3.10"
pandas = "^1.3.0"
numpy = "^1.21.1"
matplotlib = "^3.4.2"
sqlmodel = "^0.0.4"
sqlalchemy-bigquery = "1.2.1"
networkx = {extras = ["all"], version = "^2.6.3"}
typer = {extras = ["all"], version = "^0.4.0"}
pytest = "^6.2.5"
pytest-xdist = {extras = ['psutil'], version = "~2.4.0"}
rich = "^10.13.0"
Jinja2 = "^2.11.3"

[tool.poetry.dev-dependencies]
pytest-cov = "^3.0.0"
black = "^21.9b0"
dbt = "^0.20.2"
jupyter = "^1.0.0"
mypy = "^0.910"
lxml = "^4.6.3"
pytest-env = "^0.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
