name: "Install-dependencies-and-plottr"
description: "Install plottr and its dependencies"
runs:
  using: "composite"
  steps:
    - name: Install-dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install -r test_requirements.txt
        pip install .[pyqt5] --use-feature=in-tree-build
      shell: bash
