# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-11-20 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('code', models.CharField(blank=True, max_length=6, unique=True, verbose_name='\u4ee3\u7801')),
                ('memo', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lbstracker_events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-create_time',),
                'verbose_name': '\u4e8b\u4ef6',
                'verbose_name_plural': '\u4e8b\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='\u7eac\u5ea6')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u5740')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='lbstracker.Event', verbose_name='\u4e8b\u4ef6')),
            ],
            options={
                'ordering': ('event', '-create_time'),
                'verbose_name': '\u5b9a\u4f4d',
                'verbose_name_plural': '\u5b9a\u4f4d',
            },
        ),
    ]
