[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyproject_metadata"
authors = [{name = "Pradyun Gedam", email = "mail@pradyunsg.me"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/pradyunsg/pyproject-metadata"
