
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T13:49:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d03afae74dcf95ec291c62223d12285c868e1e21",
 "version": "2.2.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
