from distutils.core import setup
setup(
  name = 'encryptdecryptcrypt',
  packages = ['encryptdecryptcrypt'],
  version = '0.1',
  license='MIT',
  description = 'simple vignere encoder with numbers as keys',
  author = 'Sreenath Sreekrishna',
  author_email = 'sreenath.sreekrishna.21@gmail.com',
  url = 'https://github.com/SreenathSreekrishna/encryptdecryptcrypt',
  download_url = 'https://github.com/SreenathSreekrishna/encryptdecryptcrypt/archive/refs/tags/v_01.tar.gz',
  keywords = ['python', 'cryptography', 'encoder', 'decoder'],
  install_requires=[],
  classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
  ],
)
