[tool.poetry]
name = "dyndebug"
version = "0.1.1"
description = "A library to dynamically enable debug through configuration"
authors = ["aurecon"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9.4"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
