
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T09:00:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1959c7e912ee98306431ebd66934c4588c4ddfa0",
 "version": "0.8.357"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
