[tool.poetry]
name = "django-entries"
version = "0.1.0"
description = "Entries is a Django app that has basic CRUD functionality with some defaults."
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
# base
python = "^3.9"
Django = "^3.2"
django-extensions = "3.1.5"

# forms
django-crispy-forms = "^1.13.0" # server-side rendering
markdownify = "^0.10.0" # html to md
Markdown = "^3.3.6" # md to html
types-Markdown = "^3.3.8"
bleach = "^4.1.0" # cleaning input
types-bleach = "^4.1.1"
# if using bootstrap templating | crispy-bootstrap5 = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.1"
pytest-django = "^4.5.1"
mypy = "^0.902"
black = "^21.11b1"
isort = "^5.10.1"
pre-commit = "^2.15.0"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.1.11"]
build-backend = "poetry.core.masonry.api"
