
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T13:38:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e87bc7fc5758e5a978cf8dafe8b363589d59f358",
 "version": "v0.1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
