OHDSI_ID={
     'influenzae': 4195939,
     'cardiobacterium': 4329151,
     'kocuria species': 4185765,
     'mycoplasma hominis': 4043365,
     'streptococcus r': 4240344,
     'e coli': 4011683,
     'streptococcus s': 4240344,
     'bacteroides distasonis': 40492891,
     'campylobacter pylori': 4216359,
     'streptococcus anginosus': 4185892,
     'staphylococcus': 4278981,
     'streptococci isolated': 4240344,
     'streptococci and': 4240344,
     'brucella suis': 4167528,
     'streptococcus sanguis': 4015549,
     'streptococcus clindamycin': 4240344,
     'haemophilus parainfluenzae': 4197565,
     'tuberculosis': 4034215,
     'streptococcus mutans': 4064691,
     'hafnia': 4071894,
     'streptococcus and': 4240344,
     'streptococcus erythromycin': 4240344,
     'gram variable bacilli': 4348425,
     'streptococcus sanguinis': 4015549,
     'streptococcus ferus': 4001440,
     'rickettsia trachomae': 4268159,
     'rochalimaea quintana': 4014330,
     'beta hemolytic streptococci': 4200707,
     'brevibact': 4263119,
     'streptococci susceptibilities': 4240344,
     'bacteroides caccae': 4031998,
     'group g strep': 4326764,
     'vibrio parahaemolyticus': 4035542,
     'gram variable': 4200522,
     'lactobacillus bulgaricus': 4296299,
     'propionibacterium': 4144074,
     'neisseria meningitidis': 4076436,
     'nocardia farcinica': 4310969,
     'gram pos rods': 4017995,
     'haemophilus vaginalis': 4274639,
     'typhi': 4184768,
     'enterococcus avium': 4338685,
     'bacteroides eggerthii': 4231861,
     'actinomyces israelii': 4262658,
     'borrelia burgdorferi': 4295111,
     'gram positive organism': 4177803,
     'streptococci result': 4240344,
     'bacteroides thetaiotaomicron': 4142058,
     'paecilomyces': 4093927,
     'haemophilus': 4323572,
     'enterobactera': 4242438,
     'bordetella pertussis': 4198560,
     'gram positive': 4337977,
     'listeria': 4053183,
     's. pneumoniae': 4083579,
     'streptococcus faecalis': 4302157,
     'presumptive staphylococcus': 4278981,
     'streptococcus preliminarily': 4240344,
     'kytococcus': 4018413,
     'escherichia fergusonii': 4219241,
     'streptococcus proteus': 4222232,
     'bacteroides sp': 4212359,
     'bacillus thuringiensis': 4277574,
     'klebsiella': 4327473,
     'streptococcus from': 4240344,
     'eikenella corrodens': 4200857,
     'peptostrep': 4348178,
     'serratia': 4170580,
     'leuconostoc': 4183602,
     'methanobacterium extroquens': 4160866,
     'acinetobacter i': 4300777,
     'streptococcus parasanguis': 4015548,
     'gram positive coccobacilli': 4177803,
     'enterococcus': 4140015,
     'bacillus megaterium': 4193661,
     'gram variable rod': 4200522,
     'gram positive rods': 4017995,
     'fusobacterium necrophorum': 4099615,
     'pasteurella tularensis': 4197546,
     'shigella': 4297755,
     'raoultella': 4219380,
     'streptococcus massiliensis': 40480270,
     'streptococcus mitis': 4237427,
     'alcaligenes': 4288470,
     'vibrio': 4146528,
     'leishmania donovani': 4196345,
     'streptococcus anaerobius': 4078522,
     'pseudomonas': 4211547,
     'gram variable bacteria': 4200522,
     'aerococcus viridans': 4303232,
     'salmonella typhi': 4184768,
     'streptococcus constellatus': 4294519,
     'streptococci usual': 4240344,
     'burkholderia cepacia': 4034635,
     'legionella pneumophila': 4216497,
     'unspecified organisms': 4001594,
     'streptococcus gordonii': 4015115,
     'streptococci': 4240344,
     'pasteurella multocida': 4032583,
     'bacteroides stercoris': 4039123,
     'streptococcus salivarius': 4220801,
     'streptococcus cristatus': 4015546,
     'staphylococcus methicillin resistant': 46272514,
     'gram negative rods': 4336840,
     'chlamydia': 4037323,
     'bacteroides melaninogenicus': 4015686,
     'streptococci for': 4240344,
     'streptococcus or': 4240344,
     'yersinia pestis': 4184308,
     'mycobacterium tuberculosis': 4034215,
     'bartonella henselae': 4012883,
     'staphylococcus lugdunensis': 4014324,
     'nocardia': 4245771,
     'burkholderia mallei': 4034637,
     'chlamydia pneumoniae': 4013868,
     'acinetobacter haemolyticus': 4296863,
     'bacteroides gingivalis': 4015691,
     'staphylococcus epidermidis': 4246180,
     'ureaplasma urealyticum': 4003364,
     'bacteroides capillosus': 40492429,
     'acinetobacter bauman': 4235587,
     'micrococcus luteus': 4174810,
     'leptospira interrogans': 4023068,
     'bacteroides': 4212359,
     'acinetobacter lwoffi': 4307075,
     'viridans': 4303232,
     'aerococcus': 4231863,
     'bacteroides tectum': 4198539,
     'streptococci one': 4240344,
     'proteus mirabilis': 4248426,
     'bacteroides thetaiotmicron': 4142058,
     'streptococcus susceptibility': 4240344,
     'streptococcus sobrinus': 4183727,
     'agrobacterium tumefaciens': 4140675,
     'acinetobacter s': 4300777,
     'acinetobacter lwoffii': 4307075,
     'streptococcus most': 4240344,
     'escherichia vulneris': 4204079,
     'streptococcus aureus': 37016601,
     'streptococci moderate': 4240344,
     'streptococcus lactis': 4265181,
     'brucella melitensis': 4248720,
     'haemophilus influenzae': 4195939,
     'streptococci in': 4194525,
     'acid fast bacilli seen': 4228144,
     'achromobacter xylosoxidans': 4189931,
     'streptococcus not': 4240344,
     'mycobacterium smegmatis': 4200394,
     'streptococcus': 4240344,
     'streptococcus isolate': 4240344,
     'streptococcus staphylococcus': 4278981,
     'enterobacter cloacae': 4030716,
     'vibrio vulnificus': 4184145,
     'cdiff': 4244400,
     'legionella': 4326728,
     'rhizobium': 4187460,
     'streptococcus klebsiella': 4327473,
     'streptococcus faceium': 4240344,
     'haemophilus ducreyi': 4274806,
     'streptococcus probable': 4240344,
     'corynebacterium fusiforme': 4299363,
     'serratia marcescens': 4140691,
     'chlamydia trachomatis': 4274488,
     'clostridium botulinum': 4045568,
     'yeast': 4265186,
     'bartonella': 4267420,
     'streptococcus enterococcus': 4204753,
     'beta hemolytic streptococcus': 4200707,
     'bacillus stearothermophilus': 4162179,
     'gram neg rods': 4336840,
     'salmonella enteritidis': 4249155,
     'bacillus subtilis': 4306648,
     'streptococcus intermedius': 4268740,
     'campylobacter': 4261232,
     'enterococcus gallinarum': 4180694,
     'streptococci strain': 4240344,
     'azotobacter vinelandii': 4323505,
     'aspergillus': 4085138,
     'mycoplasma fermentans': 4339420,
     'mycoplasma mexican': 4193931,
     'bacteroides vulgatus': 4199446,
     'staphylococcus saprophyticus': 4055349,
     'bacillus anthracis': 4074055,
     'prevotella melaninogenica': 4015686,
     'gram postive organism': 4177803,
     'enterococcus maloratus': 4010027,
     'campylobacter jejuni': 4282778,
     'campylobacter coli': 4227254,
     'streptococcus cloacae': 4245277,
     'mycobacterium bovis': 4098115,
     'enterobacter': 4242438,
     'calymmatobacterium granulomatis': 4214795,
     'trueperella': 45767536,
     'stenotrophomonas maltophilia': 4034125,
     'gram negative flora': 4217941,
     'flavobacterium': 4077760,
     'staphylococcus oxacillin resistant': 46272514,
     'mycobacterium': 4348029,
     'streptococcus agalactiae': 4183468,
     'enterococcus faecalis': 4302157,
     'streptococcus resistant': 4240344,
     'c diff': 4244400,
     'streptococcus serratia': 4240344,
     'escherichia hermannii': 4312475,
     'streptococcus group': 4133816,
     'group a beta strep': 4187877,
     'acinetobacter pittii': 44784215,
     'escherichia': 4277441,
     'citrobacter': 4295448,
     'propionibacterium acnes': 4214681,
     'group a strep': 4187877,
     'acetobacter aurantius': 4263297,
     'streptococcus micros': 4200633,
     'staphylococcus hominis': 4264368,
     'clostridium tetani': 4149585,
     'fusarium': 4148080,
     'listeria monocytogenes': 4261846,
     'hsv': 4064704,
     'streptococcus isolated': 4240344,
     'proteus': 4196666,
     'streptococcus additional': 4240344,
     'streptococci rare': 4240344,
     'clostridium': 4218244,
     'strep not group a': 763524,
     'herpes': 4064704,
     'gonorrhoeae': 4285582,
     'mycoplasma genitalium': 4196675,
     'providencia': 4011684,
     'anaplasma': 4143175,
     'streptococcus pneumoniae': 4321152,
     'rhizobium radiobacter': 4206684,
     'gram positive bacilli': 4177803,
     'gardnerella vaginalis': 4274639,
     'brucella': 4095734,
     'viridans streptococci': 4136500,
     'streptococcus parasanguinis': 4015548,
     'morganella morganii': 4348164,
     'salmonella typhimurium': 4177156,
     'acinetobacter calcoaceticus': 4220355,
     'anaplasma phagocytophilum': 4222397,
     'bacillus licheniformis': 4254684,
     'neisseria': 4244123,
     'streptococcus laboratory': 4240344,
     'acinetobacter pseudomonas': 4211547,
     'prevotella': 4015682,
     'micrococcus': 4199767,
     'lactococcus': 4321593,
     'streptococcus bovis': 4217676,
     'streptococcus lutetiensis': 4214083,
     'rochalimaea': 4267420,
     'mycoplasma pneumoniae': 4240327,
     'corynebacterium': 4299363,
     'influenza': 4236145,
     'ecoli': 4011683,
     'streptococci normal': 4240344,
     'vibrio comma': 4294263,
     'gram positive cocci': 4177803,
     'yersinia pseudotuberculosis': 4235004,
     'zygomycetes': 4048996,
     'cutibacterium': 35621796,
     'streptococcus rattus': 4026260,
     'acinetobacter baumanii': 4235587,
     'coccobacilli': 4014178,
     'lactobacil': 4185121,
     'campylobacter fetus': 4223541,
     'enterococcus durans': 4263064,
     'streptococcus aeruginosa': 4185892,
     'treponema': 4147389,
     'streptococcus cricetus': 4146521,
     'yersinia': 4262819,
     'pseudomonas aeruginosa': 4198675,
     'chlamydophila pneumoniae': 4013868,
     'ehrlichia chaffeensis': 4241105,
     'vibrio cholerae': 4294263,
     'streptococcus pseudopneumoniae': 4222541,
     'actinomyces': 4236735,
     'eikenella': 4183325,
     'streptococcus gallolyticus': 4015114,
     'aeromonas': 4229267,
     'positive_unspecific': 4001594,
     'gemella': 4021869,
     'acinetobacter': 4300777,
     'gram negative bacilli': 4336840,
     'morganella': 4178264,
     'citrobacter freundii': 4269070,
     'bacteroides uniformis': 4245757,
     'capnocytophaga': 4329152,
     'microbacterium multiforme': 4282622,
     'streptococcus infantarius': 4217698,
     'moraxella': 4263926,
     'group b strep': 4183468,
     'salmonella': 4099188,
     'streptococcus sp': 4240344,
     'pasteurella': 4227127,
     'streptococci critical': 4240344,
     'group c strep': 4229618,
     'la pneumophila': 4216497,
     'rothia dentocariosa': 4261653,
     'bacillus brevis': 4015244,
     'neisseria gonorrhoeae': 4285582,
     'acid fast bacilli isolated': 4348172,
     'streptococcus species': 4240344,
     'klebsiella pneumoniae': 4209452,
     'xanthomonas': 4070158,
     'streptococcus gallinarum': 4180694,
     'mycoplasma penetrans': 4034219,
     'burkholderia': 4213231,
     'streptococcus groups': 4133816,
     'peptostreptococcus': 4348178,
     'acinetobacter aureus': 4300777,
     'bacteroides fragilis': 4208525,
     'diphtheroids': 4184593,
     'peptococcus': 4071356,
     'porphyromonas gingivalis': 4015691,
     'lactococcus lactis': 4265181,
     'virus': 4177956,
     'fusobacterium': 4143777,
     'mycoplasma': 4193931,
     'enterococcus faecium': 4234555,
     'gram negative organism': 4217941,
     'streptococcus pyogenes': 4142898,
     'campylobact': 4261232,
     'gram positive flora': 4337977,
     'granulicatella': 4257550,
     'streptococcus strain': 4240344,
     'streptococcus prevotii': 4186052,
     'acinetobacter resistant': 4034065,
     'gram variable rods': 4200522,
     'rickettsia': 4268159,
     'fusobacterium nucleatum': 4139265,
     'streptococci or': 4240344,
     'proteus vulgaris': 4164566,
     'c. diff': 4244400,
     'acid fast bacilli positive': 4348172,
     'haemo[philus]*\\sinfluenzae': 4195939,
     'corynebacterium diphtheriae': 4241690,
     'acinetobacter proteus': 4300777,
     'finegoldia': 4213521,
     'ochrobacterium': 4065995,
     'porphyromonas': 4013782,
     'acinetobacter enterococcus': 4300777,
     'stomatococcus': 4326990,
     'mycobacterium leprae': 4241457,
     'brucella abortus': 4084300,
     'staphylococcus aureus': 4149419,
     'mycobacterium diphtheriae': 4241690,
     'chlamydophila': 4160641,
     'streptococci few': 4240344,
     'bordetella': 4188054,
     'maltophilia': 4034125,
     'bacillus': 4259140,
     'rothia': 4234716,
     'bartonella quintana': 4014330,
     'lactobacillus acidophilus': 4164115,
     'clostridium perfringens': 4307974,
     'rochalimaea henselae': 4012883,
     'ehrlichiosis ewingii infection': 4348439,
     'streptococcus asaccharolyticus': 4203519,
     'acinetobacter junnii': 4029141,
     'moraxella catarrhalis': 4087087,
     'rickettsia prowazekii': 4155851,
     'staphylococcus unspecified': 4278981,
     'candida': 4139129,
     'bacillus mycoides': 4143451,
     'stenotrophomonas': 4017688,
     'oligella': 4011222,
     'bacillus cereus': 4309212,
     'diplococci': 4037741,
     'enterococci': 4174874,
     'streptococci non': 4240344,
     'lactobacillus casei': 4007682,
     'streptococcus agalact': 4183468,
     'coxiella burnetii': 4331299,
     'gram negative': 4217941,
     'staphylococcus coagulase negative': 4020318,
     'yersinia enterocolitica': 4275872,
     'elizabeth kingella': 4135694,
     'streptococcus dysgalactiae': 4246822,
     'leptospira noguchii': 4034767,
     'bacillus fusiformis': 40484284,
     'helicobacter pylori': 4216359,
     'streptococcus mitior': 4237427,
     'acinetobacter aeruginosa': 4300777,
     'azorhizobium caulinodans': 4176456,
     'acinetobacter baumannii': 4235587,
     'burkholderia pseudomallei': 4023067,
     'clostridium difficile': 4244400,
     'acinetobacter r': 4300777,
     'trichosporon': 4266502,
     'streptococci not': 4240344,
     'hafnia alvei': 4295899,
     'citrobacter koseri': 4016448,
     'providencia stuartii': 4031192,
     'gardnerella': 4239345,
     'pantoea': 4018786,
     'wolbachia': 4212748,
     'mycobacterium phlei': 4300524,
     'veillonella': 4107221,
     'abiotrophia': 4017986,
     'bordetella bronchiseptica': 4024720,
     'streptococcus avium': 4338685,
     'rickettsia psittaci': 4032644,
     'escherichia coli': 4011683,
     'rickettsia quintana': 4014330,
     'escherichia hermanii': 4312475,
     'streptococcus given': 4240344,
     'acinetobacter junii': 4029141,
     'lactobacillus': 4185121,
     'achromobacter': 4239076,
     'bacteroides species': 4212359,
     'haemophilus pertussis': 4198560,
     'viridans strep': 4136500,
     'mycobacterium lepraemurium': 4097395,
     'streptococcus notify': 4240344,
     'shigella dysenteriae': 4185110,
     'acinetobacter species': 4300777,
     'bacteroides ovatus': 4313158,
     'cryptococcus': 4069831,
     'acinetobacter ursingii': 4175185,
     'chlamydophila psittaci': 4032644,
     'streptococci no': 4240344,
     'streptococcus at': 4240344,
     'streptococcus oralis': 4057957,
     'mycobacterium intracellulare': 4222607,
     'streptococcus growth': 4240344,
     'mycobacterium avium': 4308737,
     'spirillum volutans': 4034623,
     'bifidobacterium': 4241078,
     'agrobacterium radiobacter': 4206684,
     'penicillium': 4180730,
     'rickettsia rickettsii': 4105949,
     'streptococcus result': 4240344,
     'mold': 4224654,
     'streptococci group': 4213455,
     'plesiomonas': 4179399,
     'bacteroides thetaiotamicron': 4142058,
     'streptococcus r ': 4240344,
     'streptococcus s ': 4240344,
     'streptococci isolated ': 4240344,
     'streptococci and ': 4240344,
     'streptococcus sanguis ': 4015549,
     'streptococcus clindamycin ': 4240344,
     'streptococcus mutans ': 4064691,
     'streptococcus and ': 4240344,
     'streptococcus erythromycin ': 4240344,
     'streptococci susceptibilities ': 4240344,
     'propionibacterium ': 4144074,
     'streptococci result ': 4240344,
     'streptococcus preliminarily ': 4240344,
     'streptococcus proteus ': 4222232,
     'streptococcus from ': 4240344,
     'pseudomonas ': 4211547,
     'streptococci usual ': 4240344,
     'streptococcus gordonii ': 4015115,
     'streptococci ': 4240344,
     'streptococcus sanguinis ': 4015549,
     'streptococcus cristatus ': 4015546,
     'chlamydia ': 4037323,
     'streptococci for ': 4240344,
     'streptococcus or ': 4240344,
     'aerococcus ': 4231863,
     'streptococci one ': 4240344,
     'streptococcus susceptibility ': 4240344,
     'streptococcus most ': 4240344,
     'streptococcus aureus ': 37016601,
     'streptococci moderate ': 4240344,
     'streptococci in ': 4194525,
     'streptococcus anginosus ': 4185892,
     'streptococcus not ': 4240344,
     'streptococcus isolate ': 4240344,
     'streptococcus staphylococcus ': 4278981,
     ' enterobacter cloacae': 4030716,
     'streptococcus klebsiella ': 4327473,
     'streptococcus probable ': 4240344,
     'corynebacterium fusiforme ': 4299363,
     'serratia ': 4170580,
     'streptococcus enterococcus ': 4204753,
     'streptococci strain ': 4240344,
     'mycoplasma mexican ': 4193931,
     'enterococcus maloratus ': 4010027,
     'streptococcus cloacae ': 4245277,
     'streptococcus agalactiae ': 4183468,
     'klebsiella ': 4327473,
     'streptococcus resistant ': 4240344,
     'streptococcus serratia ': 4240344,
     'streptococcus group ': 4133816,
     'group a beta strep ': 4187877,
     'citrobacter ': 4295448,
     'nocardia ': 4245771,
     'streptococcus isolated ': 4240344,
     'proteus ': 4196666,
     'streptococcus constellatus ': 4294519,
     'streptococcus additional ': 4240344,
     'streptococci rare ': 4240344,
     'streptococcus salivarius ': 4220801,
     ' gonorrhoeae': 4285582,
     'listeria ': 4053183,
     'providencia ': 4011684,
     'streptococcus laboratory ': 4240344,
     'streptococcus mitis ': 4237427,
     'influenza ': 4236145,
     'streptococci normal ': 4240344,
     'vibrio comma ': 4294263,
     ' coccobacilli': 4014178,
     'streptococcus aeruginosa ': 4185892,
     'eikenella ': 4183325,
     'streptococcus gallolyticus ': 4015114,
     'aeromonas ': 4229267,
     'viridans ': 4303232,
     'streptococcus ': 4240344,
     'streptococcus bovis ': 4217676,
     'microbacterium multiforme ': 4282622,
     'streptococcus infantarius ': 4217698,
     'streptococci critical ': 4240344,
     'streptococcus species ': 4240344,
     'burkholderia ': 4213231,
     'streptococcus groups ': 4133816,
     'fusobacterium ': 4143777,
     'streptococcus pyogenes ': 4142898,
     'streptococcus strain ': 4240344,
     'streptococcus prevotii ': 4186052,
     'streptococcus pseudopneumoniae ': 4222541,
     'streptococci or ': 4240344,
     'streptococcus micros ': 4200633,
     'pasteurella ': 4227127,
     'mycobacterium diphtheriae ': 4241690,
     'streptococcus intermedius ': 4268740,
     'streptococci few ': 4240344,
     'streptococcus asaccharolyticus ': 4203519,
     'enterobacter ': 4242438,
     'streptococci non ': 4240344,
     'streptococcus dysgalactiae ': 4246822,
     'streptococcus parasanguinis ': 4015548,
     'clostridium difficile ': 4244400,
     'streptococci not ': 4240344,
     ' enterobacter': 4242438,
     'streptococcus given ': 4240344,
     'gemella ': 4021869,
     'streptococcus notify ': 4240344,
     'streptococcus pneumoniae ': 4321152,
     'streptococci no ': 4240344,
     'streptococcus at ': 4240344,
     'streptococcus growth ': 4240344,
     ' enterobacter ': 4242438,
     'streptococcus result ': 4240344,
     'streptococci group ': 4213455,
     'plesiomonas ': 4179399,
    'mycobacteria': 4348029,
    'acid fast bacilli positive': 4348029,

     }


OHDSI_NAME={
    'influenzae': 'Haemophilus influenzae',
     'cardiobacterium': 'Cardiobacterium',
     'kocuria species': 'Kocuria',
     'mycoplasma hominis': 'Mycoplasma hominis',
     'streptococcus r': 'Streptococcus',
     'e coli': 'Escherichia coli',
     'streptococcus s': 'Streptococcus',
     'bacteroides distasonis': 'Parabacteroides distasonis',
     'campylobacter pylori': 'Helicobacter pylori',
     'streptococcus anginosus': 'Streptococcus anginosus',
     'staphylococcus': 'Staphylococcus',
     'streptococci isolated': 'Streptococcus',
     'streptococci and': 'Streptococcus',
     'brucella suis': 'Brucella suis',
     'streptococcus sanguis': 'Streptococcus sanguinis',
     'streptococcus clindamycin': 'Streptococcus',
     'haemophilus parainfluenzae': 'Haemophilus parainfluenzae',
     'tuberculosis': 'Mycobacterium tuberculosis',
     'streptococcus mutans': 'Streptococcus mutans',
     'hafnia': 'Hafnia',
     'streptococcus and': 'Streptococcus',
     'streptococcus erythromycin': 'Streptococcus',
     'gram variable bacilli': 'Gram-variable bacillus',
     'streptococcus sanguinis': 'Streptococcus sanguinis',
     'streptococcus ferus': 'Streptococcus ferus',
     'rickettsia trachomae': 'Rickettsia',
     'rochalimaea quintana': 'Bartonella quintana',
     'beta hemolytic streptococci': 'Beta-hemolytic streptococcus',
     'brevibact': 'Brevibacterium',
     'streptococci susceptibilities': 'Streptococcus',
     'bacteroides caccae': 'Bacteroides caccae',
     'group g strep': 'Streptococcus, group G',
     'vibrio parahaemolyticus': 'Vibrio parahaemolyticus',
     'gram variable': 'Gram-variable bacterium',
     'lactobacillus bulgaricus': 'Lactobacillus delbrueckii bulgaricus',
     'propionibacterium': 'Propionibacterium',
     'neisseria meningitidis': 'Neisseria meningitidis',
     'nocardia farcinica': 'Nocardia farcinica',
     'gram pos rods': 'Non-Sporing Gram Positive Rods',
     'haemophilus vaginalis': 'Gardnerella vaginalis',
     'typhi': 'Salmonella enterica subspecies enterica serovar Typhi',
     'enterococcus avium': 'Enterococcus avium',
     'bacteroides eggerthii': 'Bacteroides eggerthii',
     'actinomyces israelii': 'Actinomyces israelii',
     'borrelia burgdorferi': 'Borrelia burgdorferi',
     'gram positive organism': 'Gram positive coccobacillus',
     'streptococci result': 'Streptococcus',
     'bacteroides thetaiotaomicron': 'Bacteroides thetaiotaomicron',
     'paecilomyces': 'Paecilomyces',
     'haemophilus': 'Haemophilus',
     'enterobactera': 'Enterobacter',
     'bordetella pertussis': 'Bordetella pertussis',
     'gram positive': 'Gram-positive bacteria',
     'listeria': 'Listeria',
     's. pneumoniae': 'Klebsiella pneumoniae ss. pneumoniae',
     'streptococcus faecalis': 'Enterococcus faecalis',
     'presumptive staphylococcus': 'Staphylococcus',
     'streptococcus preliminarily': 'Streptococcus',
     'kytococcus': 'Kytococcus',
     'escherichia fergusonii': 'Escherichia fergusonii',
     'streptococcus proteus': 'Streptococcus gallolyticus subspecies pasteurianus',
     'bacteroides sp': 'Bacteroides',
     'bacillus thuringiensis': 'Bacillus thuringiensis',
     'klebsiella': 'Klebsiella',
     'streptococcus from': 'Streptococcus',
     'eikenella corrodens': 'Eikenella corrodens',
     'peptostrep': 'Peptostreptococcus',
     'serratia': 'Serratia',
     'leuconostoc': 'Leuconostoc',
     'methanobacterium extroquens': 'Methanobacterium',
     'acinetobacter i': 'Acinetobacter',
     'streptococcus parasanguis': 'Streptococcus parasanguinis',
     'gram positive coccobacilli': 'Gram positive coccobacillus',
     'enterococcus': 'Alterococcus',
     'bacillus megaterium': 'Bacillus megaterium',
     'gram variable rod': 'Gram-variable bacterium',
     'gram positive rods': 'Non-Sporing Gram Positive Rods',
     'fusobacterium necrophorum': 'Fusobacterium necrophorum',
     'pasteurella tularensis': 'Francisella tularensis',
     'shigella': 'Shigella',
     'raoultella': 'Raoultella',
     'streptococcus massiliensis': 'Streptococcus massiliensis',
     'streptococcus mitis': 'Streptococcus mitis',
     'alcaligenes': 'Alcaligenes',
     'vibrio': 'Vibrio',
     'leishmania donovani': 'Leishmania donovani complex',
     'streptococcus anaerobius': 'Peptostreptococcus anaerobius',
     'pseudomonas': 'Pseudomonas',
     'gram variable bacteria': 'Gram-variable bacterium',
     'aerococcus viridans': 'Aerococcus viridans',
     'salmonella typhi': 'Salmonella enterica subspecies enterica serovar Typhi',
     'streptococcus constellatus': 'Streptococcus constellatus',
     'streptococci usual': 'Streptococcus',
     'burkholderia cepacia': 'Burkholderia cepacia',
     'legionella pneumophila': 'Legionella pneumophila',
     'unspecified organisms': 'Non-specific',
     'streptococcus gordonii': 'Streptococcus gordonii',
     'streptococci': 'Streptococcus',
     'pasteurella multocida': 'Pasteurella multocida',
     'bacteroides stercoris': 'Bacteroides stercoris',
     'streptococcus salivarius': 'Streptococcus salivarius',
     'streptococcus cristatus': 'Streptococcus cristatus',
     'staphylococcus methicillin resistant': 'Methicillin resistant Staphylococcus',
     'gram negative rods': 'Gram-negative bacillus',
     'chlamydia': 'Chlamydia',
     'bacteroides melaninogenicus': 'Prevotella melaninogenica',
     'streptococci for': 'Streptococcus',
     'streptococcus or': 'Streptococcus',
     'yersinia pestis': 'Yersinia pestis',
     'mycobacterium tuberculosis': 'Mycobacterium tuberculosis',
     'bartonella henselae': 'Bartonella henselae',
     'staphylococcus lugdunensis': 'Staphylococcus lugdunensis',
     'nocardia': 'Nocardia',
     'burkholderia mallei': 'Burkholderia mallei',
     'chlamydia pneumoniae': 'Chlamydophila pneumoniae',
     'acinetobacter haemolyticus': 'Acinetobacter haemolyticus',
     'bacteroides gingivalis': 'Porphyromonas gingivalis',
     'staphylococcus epidermidis': 'Staphylococcus epidermidis',
     'ureaplasma urealyticum': 'Ureaplasma urealyticum',
     'bacteroides capillosus': 'Pseudoflavonifractor capillosus',
     'acinetobacter bauman': 'Acinetobacter baumannii',
     'micrococcus luteus': 'Micrococcus luteus',
     'leptospira interrogans': 'Leptospira interrogans',
     'bacteroides': 'Bacteroides',
     'acinetobacter lwoffi': 'Acinetobacter lwoffii',
     'viridans': 'Aerococcus viridans',
     'aerococcus': 'Aerococcus',
     'bacteroides tectum': 'Bacteroides pyogenes',
     'streptococci one': 'Streptococcus',
     'proteus mirabilis': 'Proteus mirabilis',
     'bacteroides thetaiotmicron': 'Bacteroides thetaiotaomicron',
     'streptococcus susceptibility': 'Streptococcus',
     'streptococcus sobrinus': 'Streptococcus sobrinus',
     'agrobacterium tumefaciens': 'Agrobacterium',
     'acinetobacter s': 'Acinetobacter',
     'acinetobacter lwoffii': 'Acinetobacter lwoffii',
     'streptococcus most': 'Streptococcus',
     'escherichia vulneris': 'Pseudescherichia vulneris',
     'streptococcus aureus': 'Streptococcus castoreus',
     'streptococci moderate': 'Streptococcus',
     'streptococcus lactis': 'Lactococcus lactis',
     'brucella melitensis': 'Brucella melitensis',
     'haemophilus influenzae': 'Haemophilus influenzae',
     'streptococci in': 'Streptococcus iniae',
     'acid fast bacilli seen': 'Partially acid fast bacilli seen',
     'achromobacter xylosoxidans': 'Achromobacter xylosoxidans',
     'streptococcus not': 'Streptococcus',
     'mycobacterium smegmatis': 'Mycobacterium smegmatis',
     'streptococcus': 'Streptococcus',
     'streptococcus isolate': 'Streptococcus',
     'streptococcus staphylococcus': 'Staphylococcus',
     'enterobacter cloacae': 'Enterobacter cloacae',
     'vibrio vulnificus': 'Vibrio vulnificus',
     'cdiff': 'Clostridioides difficile',
     'legionella': 'Legionella',
     'rhizobium': 'Rhizobium',
     'streptococcus klebsiella': 'Klebsiella',
     'streptococcus faceium': 'Streptococcus',
     'haemophilus ducreyi': 'Haemophilus ducreyi',
     'streptococcus probable': 'Streptococcus',
     'corynebacterium fusiforme': 'Corynebacterium',
     'serratia marcescens': 'Serratia marcescens',
     'chlamydia trachomatis': 'Chlamydia trachomatis',
     'clostridium botulinum': 'Clostridium botulinum',
     'yeast': 'Yeast',
     'bartonella': 'Bartonella',
     'streptococcus enterococcus': 'Streptococcus entericus',
     'beta hemolytic streptococcus': 'Beta-hemolytic streptococcus',
     'bacillus stearothermophilus': 'Geobacillus stearothermophilus',
     'gram neg rods': 'Gram-negative bacillus',
     'salmonella enteritidis': 'Salmonella Enteritidis',
     'bacillus subtilis': 'Bacillus subtilis',
     'streptococcus intermedius': 'Streptococcus intermedius',
     'campylobacter': 'Campylobacter',
     'enterococcus gallinarum': 'Enterococcus gallinarum',
     'streptococci strain': 'Streptococcus',
     'azotobacter vinelandii': 'Azotobacter vinelandii',
     'aspergillus': 'Aspergillus',
     'mycoplasma fermentans': 'Mycoplasma fermentans',
     'mycoplasma mexican': 'Genus Mycoplasma',
     'bacteroides vulgatus': 'Bacteroides vulgatus',
     'staphylococcus saprophyticus': 'Staphylococcus saprophyticus',
     'bacillus anthracis': 'Bacillus anthracis',
     'prevotella melaninogenica': 'Prevotella melaninogenica',
     'gram postive organism': 'Gram positive coccobacillus',
     'enterococcus maloratus': 'Enterococcus malodoratus',
     'campylobacter jejuni': 'Campylobacter jejuni',
     'campylobacter coli': 'Campylobacter coli',
     'streptococcus cloacae': 'Streptococcus macacae',
     'mycobacterium bovis': 'Mycobacterium bovis',
     'enterobacter': 'Enterobacter',
     'calymmatobacterium granulomatis': 'Klebsiella granulomatis',
     'trueperella': 'Trueperella',
     'stenotrophomonas maltophilia': 'Stenotrophomonas maltophilia',
     'gram negative flora': 'Gram-negative bacterium',
     'flavobacterium': 'Flavobacterium',
     'staphylococcus oxacillin resistant': 'Methicillin resistant Staphylococcus',
     'mycobacterium': 'Mycobacterium',
     'streptococcus agalactiae': 'Group B streptococcus',
     'enterococcus faecalis': 'Enterococcus faecalis',
     'streptococcus resistant': 'Streptococcus',
     'c diff': 'Clostridioides difficile',
     'streptococcus serratia': 'Streptococcus',
     'escherichia hermannii': 'Escherichia hermannii',
     'streptococcus group': 'Streptococcus mitis group',
     'group a beta strep': 'Beta-hemolytic Streptococcus, group A',
     'acinetobacter pittii': 'Acinetobacter pittii',
     'escherichia': 'Escherichia',
     'citrobacter': 'Citrobacter',
     'propionibacterium acnes': 'Cutibacterium acnes',
     'group a strep': 'Beta-hemolytic Streptococcus, group A',
     'acetobacter aurantius': 'Acetobacter aceti',
     'streptococcus micros': 'Parvimonas micra',
     'staphylococcus hominis': 'Staphylococcus hominis',
     'clostridium tetani': 'Clostridium tetani',
     'fusarium': 'Fusarium',
     'listeria monocytogenes': 'Listeria monocytogenes',
     'hsv': 'Human herpes simplex virus',
     'streptococcus isolated': 'Streptococcus',
     'proteus': 'Proteus',
     'streptococcus additional': 'Streptococcus',
     'streptococci rare': 'Streptococcus',
     'clostridium': 'Clostridium',
     'strep not group a': 'Streptococcus species not group A, B or D',
     'herpes': 'Human herpes simplex virus',
     'gonorrhoeae': 'Neisseria gonorrhoeae',
     'mycoplasma genitalium': 'Mycoplasma genitalium',
     'providencia': 'Providencia',
     'anaplasma': 'Anaplasma',
     'streptococcus pneumoniae': 'Streptococcus pneumoniae',
     'rhizobium radiobacter': 'Rhizobium radiobacter',
     'gram positive bacilli': 'Gram positive coccobacillus',
     'gardnerella vaginalis': 'Gardnerella vaginalis',
     'brucella': 'Brucella',
     'viridans streptococci': 'Streptococcus, viridans group',
     'streptococcus parasanguinis': 'Streptococcus parasanguinis',
     'morganella morganii': 'Morganella morganii',
     'salmonella typhimurium': 'Salmonella Typhimurium',
     'acinetobacter calcoaceticus': 'Acinetobacter calcoaceticus',
     'anaplasma phagocytophilum': 'Anaplasma phagocytophilum',
     'bacillus licheniformis': 'Bacillus licheniformis',
     'neisseria': 'Neisseria',
     'streptococcus laboratory': 'Streptococcus',
     'acinetobacter pseudomonas': 'Pseudomonas',
     'prevotella': 'Prevotella',
     'micrococcus': 'Micrococcus',
     'lactococcus': 'Lactococcus',
     'streptococcus bovis': 'Streptococcus equinus',
     'streptococcus lutetiensis': 'Streptococcus lutetiensis',
     'rochalimaea': 'Bartonella',
     'mycoplasma pneumoniae': 'Mycoplasma pneumoniae',
     'corynebacterium': 'Corynebacterium',
     'influenza': 'Influenza A virus',
     'ecoli': 'Escherichia coli',
     'streptococci normal': 'Streptococcus',
     'vibrio comma': 'Vibrio cholerae',
     'gram positive cocci': 'Gram positive coccobacillus',
     'yersinia pseudotuberculosis': 'Yersinia pseudotuberculosis',
     'zygomycetes': 'Zygomycetes',
     'cutibacterium': 'Cutibacterium',
     'streptococcus rattus': 'Streptococcus ratti',
     'acinetobacter baumanii': 'Acinetobacter baumannii',
     'coccobacilli': 'Coccobacilli',
     'lactobacil': 'Lactobacillus',
     'campylobacter fetus': 'Campylobacter fetus',
     'enterococcus durans': 'Enterococcus durans',
     'streptococcus aeruginosa': 'Streptococcus anginosus',
     'treponema': 'Treponema',
     'streptococcus cricetus': 'Streptococcus criceti',
     'yersinia': 'Yersinia',
     'pseudomonas aeruginosa': 'Pseudomonas aeruginosa',
     'chlamydophila pneumoniae': 'Chlamydophila pneumoniae',
     'ehrlichia chaffeensis': 'Ehrlichia chaffeensis',
     'vibrio cholerae': 'Vibrio cholerae',
     'streptococcus pseudopneumoniae': 'Streptococcus pseudopneumoniae',
     'actinomyces': 'Actinomyces',
     'eikenella': 'Eikenella',
     'streptococcus gallolyticus': 'Streptococcus gallolyticus',
     'aeromonas': 'Aeromonas',
     'positive_unspecific': 'Non-specific',
     'gemella': 'Gemella',
     'acinetobacter': 'Acinetobacter',
     'gram negative bacilli': 'Gram-negative bacillus',
     'morganella': 'Morganella',
     'citrobacter freundii': 'Citrobacter freundii',
     'bacteroides uniformis': 'Bacteroides uniformis',
     'capnocytophaga': 'Capnocytophaga',
     'microbacterium multiforme': 'Eubacterium multiforme',
     'streptococcus infantarius': 'Streptococcus infantarius',
     'moraxella': 'Moraxella',
     'group b strep': 'Group B streptococcus',
     'salmonella': 'Salmonella',
     'streptococcus sp': 'Streptococcus',
     'pasteurella': 'Pasteurella',
     'streptococci critical': 'Streptococcus',
     'group c strep': 'Streptococcus, group C',
     'la pneumophila': 'Legionella pneumophila',
     'rothia dentocariosa': 'Rothia dentocariosa',
     'bacillus brevis': 'Brevibacillus brevis',
     'neisseria gonorrhoeae': 'Neisseria gonorrhoeae',
     'acid fast bacilli isolated': 'Acid-fast bacillus',
     'streptococcus species': 'Streptococcus',
     'klebsiella pneumoniae': 'Klebsiella pneumoniae',
     'xanthomonas': 'Xanthomonas',
     'streptococcus gallinarum': 'Enterococcus gallinarum',
     'mycoplasma penetrans': 'Mycoplasma penetrans',
     'burkholderia': 'Burkholderia',
     'streptococcus groups': 'Streptococcus mitis group',
     'peptostreptococcus': 'Peptostreptococcus',
     'acinetobacter aureus': 'Acinetobacter',
     'bacteroides fragilis': 'Bacteroides fragilis',
     'diphtheroids': 'Diphtheroids',
     'peptococcus': 'Peptococcus',
     'porphyromonas gingivalis': 'Porphyromonas gingivalis',
     'lactococcus lactis': 'Lactococcus lactis',
     'virus': 'Virus',
     'fusobacterium': 'Fusobacterium',
     'mycoplasma': 'Genus Mycoplasma',
     'enterococcus faecium': 'Enterococcus faecium',
     'gram negative organism': 'Gram-negative bacterium',
     'streptococcus pyogenes': 'Streptococcus equi subsp. zooepidemicus',
     'campylobact': 'Campylobacter',
     'gram positive flora': 'Gram-positive bacteria',
     'granulicatella': 'Granulicatella',
     'streptococcus strain': 'Streptococcus',
     'streptococcus prevotii': 'Anaerococcus prevotii',
     'acinetobacter resistant': 'Acinetobacter radioresistens',
     'gram variable rods': 'Gram-variable bacterium',
     'rickettsia': 'Rickettsia',
     'fusobacterium nucleatum': 'Fusobacterium nucleatum',
     'streptococci or': 'Streptococcus',
     'proteus vulgaris': 'Proteus vulgaris',
     'c. diff': 'Clostridioides difficile',
     'acid fast bacilli positive': 'Acid-fast bacillus',
     'haemo[philus]*\\sinfluenzae': 'Haemophilus influenzae',
     'corynebacterium diphtheriae': 'Corynebacterium diphtheriae',
     'acinetobacter proteus': 'Acinetobacter',
     'finegoldia': 'Finegoldia',
     'ochrobacterium': 'Chromobacterium',
     'porphyromonas': 'Porphyromonas',
     'acinetobacter enterococcus': 'Acinetobacter',
     'stomatococcus': 'Blastococcus',
     'mycobacterium leprae': 'Mycobacterium leprae',
     'brucella abortus': 'Brucella abortus',
     'staphylococcus aureus': 'Staphylococcus aureus',
     'mycobacterium diphtheriae': 'Corynebacterium diphtheriae',
     'chlamydophila': 'Chlamydophila',
     'streptococci few': 'Streptococcus',
     'bordetella': 'Bordetella',
     'maltophilia': 'Stenotrophomonas maltophilia',
     'bacillus': 'Bacillus',
     'rothia': 'Rothia',
     'bartonella quintana': 'Bartonella quintana',
     'lactobacillus acidophilus': 'Lactobacillus acidophilus',
     'clostridium perfringens': 'Clostridium perfringens',
     'rochalimaea henselae': 'Bartonella henselae',
     'ehrlichiosis ewingii infection': 'Ehrlichia ewingii',
     'streptococcus asaccharolyticus': 'Peptoniphilus asaccharolyticus',
     'acinetobacter junnii': 'Acinetobacter junii',
     'moraxella catarrhalis': 'Moraxella catarrhalis',
     'rickettsia prowazekii': 'Rickettsia prowazekii',
     'staphylococcus unspecified': 'Staphylococcus',
     'candida': 'Candida',
     'bacillus mycoides': 'Bacillus mycoides',
     'stenotrophomonas': 'Stenotrophomonas',
     'oligella': 'Oligella',
     'bacillus cereus': 'Bacillus cereus',
     'diplococci': 'Diplococci',
     'enterococci': 'Enterococcus canis',
     'streptococci non': 'Streptococcus',
     'lactobacillus casei': 'Lactobacillus casei',
     'streptococcus agalact': 'Group B streptococcus',
     'coxiella burnetii': 'Coxiella burnetii',
     'gram negative': 'Gram-negative bacterium',
     'staphylococcus coagulase negative': 'Staphylococcus, coagulase negative',
     'yersinia enterocolitica': 'Yersinia enterocolitica',
     'elizabeth kingella': 'Kingella',
     'streptococcus dysgalactiae': 'Streptococcus dysgalactiae',
     'leptospira noguchii': 'Leptospira noguchii',
     'bacillus fusiformis': 'Lysinibacillus fusiformis',
     'helicobacter pylori': 'Helicobacter pylori',
     'streptococcus mitior': 'Streptococcus mitis',
     'acinetobacter aeruginosa': 'Acinetobacter',
     'azorhizobium caulinodans': 'Azorhizobium caulinodans',
     'acinetobacter baumannii': 'Acinetobacter baumannii',
     'burkholderia pseudomallei': 'Burkholderia pseudomallei',
     'clostridium difficile': 'Clostridioides difficile',
     'acinetobacter r': 'Acinetobacter',
     'trichosporon': 'Trichosporon',
     'streptococci not': 'Streptococcus',
     'hafnia alvei': 'Hafnia alvei',
     'citrobacter koseri': 'Citrobacter koseri',
     'providencia stuartii': 'Providencia stuartii',
     'gardnerella': 'Gardnerella',
     'pantoea': 'Pantoea',
     'wolbachia': 'Wolbachia',
     'mycobacterium phlei': 'Mycobacterium phlei',
     'veillonella': 'Veillonella',
     'abiotrophia': 'Abiotrophia',
     'bordetella bronchiseptica': 'Bordetella bronchiseptica',
     'streptococcus avium': 'Enterococcus avium',
     'rickettsia psittaci': 'Chlamydophila psittaci',
     'escherichia coli': 'Escherichia coli',
     'rickettsia quintana': 'Bartonella quintana',
     'escherichia hermanii': 'Escherichia hermannii',
     'streptococcus given': 'Streptococcus',
     'acinetobacter junii': 'Acinetobacter junii',
     'lactobacillus': 'Lactobacillus',
     'achromobacter': 'Achromobacter',
     'bacteroides species': 'Bacteroides',
     'haemophilus pertussis': 'Bordetella pertussis',
     'viridans strep': 'Streptococcus, viridans group',
     'mycobacterium lepraemurium': 'Mycobacterium lepraemurium',
     'streptococcus notify': 'Streptococcus',
     'shigella dysenteriae': 'Shigella dysenteriae',
     'acinetobacter species': 'Acinetobacter',
     'bacteroides ovatus': 'Bacteroides ovatus',
     'cryptococcus': 'Cryptococcus',
     'acinetobacter ursingii': 'Acinetobacter ursingii',
     'chlamydophila psittaci': 'Chlamydophila psittaci',
     'streptococci no': 'Streptococcus',
     'streptococcus at': 'Streptococcus',
     'streptococcus oralis': 'Streptococcus oralis',
     'mycobacterium intracellulare': 'Mycobacterium intracellulare',
     'streptococcus growth': 'Streptococcus',
     'mycobacterium avium': 'Mycobacterium avium',
     'spirillum volutans': 'Spirillum volutans',
     'bifidobacterium': 'Bifidobacterium',
     'agrobacterium radiobacter': 'Rhizobium radiobacter',
     'penicillium': 'Penicillium',
     'rickettsia rickettsii': 'Rickettsia rickettsii',
     'streptococcus result': 'Streptococcus',
     'mold': 'Mold',
     'streptococci group': 'Streptococcus pyogenes',
     'plesiomonas': 'Plesiomonas',
     'bacteroides thetaiotamicron': 'Bacteroides thetaiotaomicron',
     'streptococcus r ': 'Streptococcus',
     'streptococcus s ': 'Streptococcus',
     'streptococci isolated ': 'Streptococcus',
     'streptococci and ': 'Streptococcus',
     'streptococcus sanguis ': 'Streptococcus sanguinis',
     'streptococcus clindamycin ': 'Streptococcus',
     'streptococcus mutans ': 'Streptococcus mutans',
     'streptococcus and ': 'Streptococcus',
     'streptococcus erythromycin ': 'Streptococcus',
     'streptococci susceptibilities ': 'Streptococcus',
     'propionibacterium ': 'Propionibacterium',
     'streptococci result ': 'Streptococcus',
     'streptococcus preliminarily ': 'Streptococcus',
     'streptococcus proteus ': 'Streptococcus gallolyticus subspecies pasteurianus',
     'streptococcus from ': 'Streptococcus',
     'pseudomonas ': 'Pseudomonas',
     'streptococci usual ': 'Streptococcus',
     'streptococcus gordonii ': 'Streptococcus gordonii',
     'streptococci ': 'Streptococcus',
     'streptococcus sanguinis ': 'Streptococcus sanguinis',
     'streptococcus cristatus ': 'Streptococcus cristatus',
     'chlamydia ': 'Chlamydia',
     'streptococci for ': 'Streptococcus',
     'streptococcus or ': 'Streptococcus',
     'aerococcus ': 'Aerococcus',
     'streptococci one ': 'Streptococcus',
     'streptococcus susceptibility ': 'Streptococcus',
     'streptococcus most ': 'Streptococcus',
     'streptococcus aureus ': 'Streptococcus castoreus',
     'streptococci moderate ': 'Streptococcus',
     'streptococci in ': 'Streptococcus iniae',
     'streptococcus anginosus ': 'Streptococcus anginosus',
     'streptococcus not ': 'Streptococcus',
     'streptococcus isolate ': 'Streptococcus',
     'streptococcus staphylococcus ': 'Staphylococcus',
     ' enterobacter cloacae': 'Enterobacter cloacae',
     'streptococcus klebsiella ': 'Klebsiella',
     'streptococcus probable ': 'Streptococcus',
     'corynebacterium fusiforme ': 'Corynebacterium',
     'serratia ': 'Serratia',
     'streptococcus enterococcus ': 'Streptococcus entericus',
     'streptococci strain ': 'Streptococcus',
     'mycoplasma mexican ': 'Genus Mycoplasma',
     'enterococcus maloratus ': 'Enterococcus malodoratus',
     'streptococcus cloacae ': 'Streptococcus macacae',
     'streptococcus agalactiae ': 'Group B streptococcus',
     'klebsiella ': 'Klebsiella',
     'streptococcus resistant ': 'Streptococcus',
     'streptococcus serratia ': 'Streptococcus',
     'streptococcus group ': 'Streptococcus mitis group',
     'group a beta strep ': 'Beta-hemolytic Streptococcus, group A',
     'citrobacter ': 'Citrobacter',
     'nocardia ': 'Nocardia',
     'streptococcus isolated ': 'Streptococcus',
     'proteus ': 'Proteus',
     'streptococcus constellatus ': 'Streptococcus constellatus',
     'streptococcus additional ': 'Streptococcus',
     'streptococci rare ': 'Streptococcus',
     'streptococcus salivarius ': 'Streptococcus salivarius',
     ' gonorrhoeae': 'Neisseria gonorrhoeae',
     'listeria ': 'Listeria',
     'providencia ': 'Providencia',
     'streptococcus laboratory ': 'Streptococcus',
     'streptococcus mitis ': 'Streptococcus mitis',
     'influenza ': 'Influenza A virus',
     'streptococci normal ': 'Streptococcus',
     'vibrio comma ': 'Vibrio cholerae',
     ' coccobacilli': 'Coccobacilli',
     'streptococcus aeruginosa ': 'Streptococcus anginosus',
     'eikenella ': 'Eikenella',
     'streptococcus gallolyticus ': 'Streptococcus gallolyticus',
     'aeromonas ': 'Aeromonas',
     'viridans ': 'Aerococcus viridans',
     'streptococcus ': 'Streptococcus',
     'streptococcus bovis ': 'Streptococcus equinus',
     'microbacterium multiforme ': 'Eubacterium multiforme',
     'streptococcus infantarius ': 'Streptococcus infantarius',
     'streptococci critical ': 'Streptococcus',
     'streptococcus species ': 'Streptococcus',
     'burkholderia ': 'Burkholderia',
     'streptococcus groups ': 'Streptococcus mitis group',
     'fusobacterium ': 'Fusobacterium',
     'streptococcus pyogenes ': 'Streptococcus equi subsp. zooepidemicus',
     'streptococcus strain ': 'Streptococcus',
     'streptococcus prevotii ': 'Anaerococcus prevotii',
     'streptococcus pseudopneumoniae ': 'Streptococcus pseudopneumoniae',
     'streptococci or ': 'Streptococcus',
     'streptococcus micros ': 'Parvimonas micra',
     'pasteurella ': 'Pasteurella',
     'mycobacterium diphtheriae ': 'Corynebacterium diphtheriae',
     'streptococcus intermedius ': 'Streptococcus intermedius',
     'streptococci few ': 'Streptococcus',
     'streptococcus asaccharolyticus ': 'Peptoniphilus asaccharolyticus',
     'enterobacter ': 'Enterobacter',
     'streptococci non ': 'Streptococcus',
     'streptococcus dysgalactiae ': 'Streptococcus dysgalactiae',
     'streptococcus parasanguinis ': 'Streptococcus parasanguinis',
     'clostridium difficile ': 'Clostridioides difficile',
     'streptococci not ': 'Streptococcus',
     ' enterobacter': 'Enterobacter',
     'streptococcus given ': 'Streptococcus',
     'gemella ': 'Gemella',
     'streptococcus notify ': 'Streptococcus',
     'streptococcus pneumoniae ': 'Streptococcus pneumoniae',
     'streptococci no ': 'Streptococcus',
     'streptococcus at ': 'Streptococcus',
     'streptococcus growth ': 'Streptococcus',
     ' enterobacter ': 'Enterobacter',
     'streptococcus result ': 'Streptococcus',
     'streptococci group ': 'Streptococcus pyogenes',
     'plesiomonas ': 'Plesiomonas',
     'mycobacteria': 'Mycobacterium',
     'acid fast bacilli positive': 'Mycobacterium',
    }