
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T15:09:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "63147519cba6e88c69f0e5f3a1441a5c7179171b",
 "version": "1.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
