
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T16:42:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f687712a8360998877317b12776cd7c5afe85ea",
 "version": "0.13.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
