arangodb:
  DB_end_point: createDB
  DB_service_host: arangoml.arangodb.cloud
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: https
  dbName: MLd7j0httm5kad8pap0meul
  password: ML202ejzo6gx7shhx651kgcr
  username: ML06weos0qj5z54fsd0m5mjrr
mlgraph:
  graphname: enterprise_ml_graph
