language: python
python:
  - "3.7"

env:
  # - MATPLOTLIB_VERSION=3.0.3  # This version has a bug for text rotations.
  # - MATPLOTLIB_VERSION=3.1.1
  - MATPLOTLIB_VERSION=3.2.0
  - MATPLOTLIB_VERSION=3.3.0
  - MATPLOTLIB_VERSION=3.4.0
  - MATPLOTLIB_VERSION=3.5.0

before_install:
  - sudo apt-get -y install ghostscript inkscape

install:
  - python -mpip install --upgrade pip
  - python -mpip install matplotlib==$MATPLOTLIB_VERSION
  - python -mpip install pytest>=4.6
  - python -mpip install pytest-cov
  - python -mpip install codecov coverage
script: python -mpytest -ra --cov=./ --log-level=DEBUG
after_success:
  - codecov
