
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T20:16:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2eda0ada3de804e8a952d94fba1e428eee37d31d",
 "version": "0.32.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
