
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-04T16:54:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "05dde04420220bcee1850e73f5f6dee8a0772f0d",
 "version": "v1.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
