repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-ast

- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
  - id: black
    language_version: python3

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies: [types-requests, types-toml, types-PyYAML, types-setuptools, pydantic]
