VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('30')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('23')
MAJOR_VERSION = 0
MINOR_VERSION = 10
PATCH_VERSION = 202111301123
version_date = '2021/11/30 11:23'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
