
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T16:25:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1c98dc480e0d92234d8c18708d16895423a0f3e",
 "version": "4.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
