
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T22:31:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9f9685cfe3d1ff58f7ec1e0d69367b3955281b2",
 "version": "0.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
