[tool.poetry]
name = "aiohttp-sqlalchemy"
version = "0.34.0"
description = "SQLAlchemy 1.4 / 2.0 support for aiohttp."
license = "MIT"

authors = [
    "Ruslan Ilyasovich Gilfanov <ri.gilfanov@yandex.ru>",
]
maintainers = [
    "Ruslan Ilyasovich Gilfanov <ri.gilfanov@yandex.ru>",
]

readme = "README.rst"
homepage = "https://pypi.org/project/aiohttp-sqlalchemy/"
repository = "https://github.com/ri-gilfanov/aiohttp-sqlalchemy"
documentation = "https://aiohttp-sqlalchemy.readthedocs.io/"

keywords = ["aiohttp", "sqlalchemy", "asyncio"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: aiohttp",
    "Framework :: AsyncIO",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4.post0"
aiohttp-things = ">=0.13.0"
SQLAlchemy = "^1.4.22"
sqlalchemy-things = ">=0.10.1"
aiomysql = { version = ">=0.0.22", optional = true }
aiosqlite = { version = ">=0.17.0", optional = true }
asyncpg = { version = ">=0.25.0", optional = true }

[tool.poetry.extras]
mysql = ["aiomysql"]
postgresql = ["asyncpg"]
sqlite = ["aiosqlite"]

[tool.poetry.dev-dependencies]
aiomysql = ">=0.0.22"
aiosqlite = ">=0.17.0"
asyncpg = ">=0.25.0"
flake8 = ">=4.0.1"
isort = ">=5.10.1"
mypy = ">=0.910"
pytest = ">=6.2.5"
pytest-cov = ">=3.0.0"
Sphinx = ">=4.3.1"
sphinx_rtd_theme = ">=1.0.0"
tomli = ">=1.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = ["aiohttp_sqlalchemy"]
known_third_party = ["aiohttp", "aiohttp-things", "sqlalchemy"]
profile = "wemake"
src_paths = ["aiohttp_sqlalchemy", "examples", "tests"]

[tool.mypy]
files = ["aiohttp_sqlalchemy", "tests"]
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = ['sqlalchemy.*']
ignore_missing_imports = true
