# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test plugins

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    types:
    - labeled
    - opened
    - synchronize
    - reopened


jobs:
  build:
    # if: ${{ github.event.label.name == 'test-plugins' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        plugin-name: [integral, integral-all-sky, antares, polar]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Clone ${{ matrix.plugin-name }} plugin 
      uses: actions/checkout@v2
      with:
        repository: 'oda-hub/dispatcher-plugin-${{matrix.plugin-name}}'
        path: plugin   


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy pylint pytest-cov    
        if [ -f plugin/requirements.txt ]; then pip install -r plugin/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .[test]
    
    - name: Test ${{ matrix.plugin-name }} plugin with pytest
      run: |
        cd plugin && DISPATCHER_MOCK_KB=yes python -m pytest tests -sv --full-trace --log-cli-level=DEBUG 
    
