
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T13:08:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a618c319dfc87954203fac6a902938ac47158b5",
 "version": "1.15.0.post.dev629"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
