
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T20:01:39+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f21b44c60b0c73f439e1a3f9ec0eace7f411d2a",
 "version": "0.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
