[tool.poetry]
name = "olympia"
version = "0.2.0"
description = "Olympia"
authors = ["Luke Miloszewski <lukemiloszewski@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/lukemiloszewski/olympia"
repository = "https://github.com/lukemiloszewski/olympia"
classifiers = [
    "Topic :: Software Development",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7.1"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
flake8 = "^4.0.1"
isort = "^5.8.0"
mypy = "^0.910"
pre-commit = "^2.13.0"
pydocstyle = "^6.1.1"
pytest = "^6.2.4"
pytest-cov = "3.0.0"

[tool.poetry.scripts]
olympia = "olympia.__main__:main"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["olympia"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.coverage.xml]
output = "coverage.xml"

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
