
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T09:32:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c55a39c626b1aca4a3b4965b59e877fbfde18d63",
 "version": "1.15.0.post.dev619"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
