VERSION_YEAR = 2021
VERSION_MONTH = int('12')
VERSION_DAY = int('02')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('12')
MAJOR_VERSION = 1
MINOR_VERSION = 2
PATCH_VERSION = 202112021312
version_date = '2021/12/02 13:12'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
