
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-24T10:25:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "196c7d9980b6967bb31e60673eb651fca5c01227",
 "version": "1.0a8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
