
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T13:35:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "282fd8258487ccad26e3cfb2c47543754dcb1e7c",
 "version": "2.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
