#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['libtgmk']

package_data = \
{'': ['*']}

setup(name='libtgmk',
      version='0.4.2',
      description='a LIBrary implementing TGMK (Tebi-Gibi-Mebi-Kibi), a human-readable lossless 1024-base integer representation, suitable for bits and bytes',
      author='Carlo Alessandro Verre',
      author_email='carlo.alessandro.verre@gmail.com',
      url='https://pypi.org/project/libtgmk',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
