[tool.poetry]
name = "kicksaw-lambda-logger"
version = "0.0.1"
description = "A customized loger for seamlessly logging on an AWS Lambda or local environment, with reporting in Sentry and other logging-related featues"
readme = "README.md"
repository = "https://github.com/Kicksaw-Consulting/kicksaw-lambda-logger"
authors = ["Alex Drozd <alex@kicksaw.com>", "Tim Sabat <tim@kicksaw.com>"]
keywords = ["kicksaw", "aws", "lambda", "logging"]
packages = [
    { include = "kicksaw_lambda_logger" }
]

[tool.poetry.dependencies]
python = "^3.8"
sentry-sdk = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.11b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
