# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Hustens0hn.github.io/world_nbdev/"

git_url = "https://github.com/Hustens0hn/world_nbdev/tree/{branch}/"

def custom_doc_links(name): return None
