
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T15:05:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdbd2aeaadfb2a5145f0eb9af01a018169fc8392",
 "version": "2021.11.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
