
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T20:29:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "410a88eb322c1d7c2e1cf143921030b69ad128d5",
 "version": "1.6.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
