addons:
  apt:
    packages:
    - graphviz

language: python

python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - git clone https://github.com/NeuroML/NeuroMLlite.git
  - cd NeuroMLlite
  - git checkout master  # specific branch of NeuroMLlite to use...
  - python setup.py install
  - cd ..
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.9" ]]; then python -m pip install git+https://github.com/SheffieldML/GPy.git@devel; fi
  - python -m pip install git+https://github.com/PrincetonUniversity/PsyNeuLink.git@mdf
  - pip install .[dev]

script:
  ###       Run main tests
  - ./test_all.sh
  - pip freeze  # List currently installed Python packages
