name: deploy-package
on:
  push:
    tags:
      - v*
jobs:
  package-actions:
    # strategy:
    #   matrix:
    #     pyversion: ["3.8", "3.9"]
    # os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          # Need to set this to 0 for setuptools-scm, so that it will grab all
          # history to get the tag correct.
          fetch-depth: 0
        # Setup python, later we set this to version 3.9.
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install packages
        run: pip install build twine
      - name: Build package
        run: python -m build
      - name: Deploy Package
        shell: bash
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/* -u $PYPI_USERNAME  -p $PYPI_PASSWORD
