
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T12:16:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8a41159416f60f3cab824d695d37198f1700dc3",
 "version": "1.0.44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
