
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T00:40:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9caddb52d9b4c6ddbe2b58536619e92c23ebe39",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
