
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T17:11:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "47d9183b254fd7322321aa85339d86a6759fd8f2",
 "version": "1.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
