
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T09:17:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9d36a92a80749e0cd92a0241c6b6e611d19a507c",
 "version": "0.30.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
