
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T15:07:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0a24e4aff028134702a0531316634d765d8208d",
 "version": "0.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
