
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-28T14:14:06-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f72665d0dd8acfc1657e6f0423d08295c82c7658",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
