[build-system]
requires = ["setuptools>=45",  "setuptools_scm>=6.2", "wheel", "cffi>=1.0.1"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]
# Dev versions are PREVIOUS.post1.devXYZ
version_scheme = "no-guess-dev"


[tool.pytest.ini_options]
addopts = "-ra --strict-markers --capture=no"
xfail_strict = true
testpaths = "tests"
filterwarnings = [
    "once::Warning",
]


[tool.black]
line-length = 79


[tool.isort]
profile = "attrs"
