"""Autogenerated file: DO NOT EDIT!"""
import typing  # noqa: F401
from dazzler.system import Component, Aspect, UNDEFINED  # noqa: F401


class TimePicker(Component):
    """
    Time input with fallback for ie and safari.

    :CSS:

        - ``dazzler-calendar-time-picker``
        - ``time-input``
        - ``fallback-timepicker``
        - ``time-range``
        - ``time-value``
    """
    value = Aspect(default='00:00', docstring="Time value formatted as HH:MM (default='00:00')")  # noqa: E501
    fallback_mode = Aspect(docstring="Use a custom picker instead of browser dependant.Automatically set when no time input support detected.")  # noqa: E501
    mode = Aspect(default="'24h'", docstring="What to display when in fallback mode. (Possible values: '24h', 'AM/PM') (default="'24h'")")  # noqa: E501
    class_name = Aspect(docstring="Class name automatically added by dazzler api with a prefix for the component library.ie: core component Container become ``dazzler-core-container``.When added on the component, the class names will be concatenated.")  # noqa: E501
    style = Aspect(docstring="Style object for the top level wrapper of the component.")  # noqa: E501

    def __init__(
            self,
            value: typing.Optional[str] = '00:00',
            fallback_mode: typing.Optional[bool] = UNDEFINED,
            mode: typing.Optional[typing.Any] = "'24h'",
            class_name: typing.Optional[str] = UNDEFINED,
            style: typing.Optional[typing.Dict] = UNDEFINED,
            identity: str = None
    ):
        """
        :param value: Time value formatted as HH:MM (default='00:00')
        :param fallback_mode: Use a custom picker instead of browser
            dependant. Automatically set when no time input support detected.
        :param mode: What to display when in fallback mode. (Possible
            values: '24h', 'AM/PM') (default="'24h'")
        :param class_name: Class name automatically added by dazzler api
            with a prefix for the  component library. ie: core component
            Container become ``dazzler-core-container``. When added on the
            component, the class names will be concatenated.
        :param style: Style object for the top level wrapper of the
            component.
        """
        Component.__init__(self, locals(), identity)
