
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T23:04:38+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "b69105502145320d48f536a67dffe89433f53373",
 "version": "0.2.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
