
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T10:51:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "20e92e33426bc18e87e8885e5094ca036f3ed6ee",
 "version": "1.92.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
