[project]
name = "samurai"
dynamic = ["version", "description"]
authors = [{name = "c4ffein", email="c4ffein.work@gmail.com"}]
readme = "README.md"
requires-python = ">3.7,<4"
keywords = ["django", "rest", "ninja"]
classifiers = [
    "Topic :: Software Development",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/c4ffein/django-samurai"
Source = "https://github.com/c4ffein/django-samurai"
Documentation = "https://github.com/c4ffein/django-samurai"

[dev-dependencies]
black = { version = "^21.11b1", python = "^3.9" }

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 120
target_version = ['py39']
include = '\.pyi?$'

# We should use flit to publish. But flit can't publish a package under a different name than the module
[tool.poetry]
name = "django-samurai"
version = "0.0.1"
description = "?"
authors = ["c4ffein <c4ffein.work@gmail.com>"]
packages = [
    { include = "samurai" }
]
