
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T11:17:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "406a260ec88275803ff11368bad533cc699b52de",
 "version": "0.7.1.post.dev174"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
