[tool.poetry]
name = "quality-lac-data-ref-postcodes"
version = "2021.8-alpha.5"
description = """\
This is a redistribution of the ONS dataset on Lower Tier Local Authority to\
Upper Tier Local Authority Lookup packaged for the Quality Lac Data project.\
\
Source: Office for National Statistics licensed under the Open Government Licence v.3.0\
"""
authors = [
    "Office for National Statistics <sharedcustomercontactcentre@ons.gov.uk>",
    "Kaj Siebert <kaj@k-si.com>",
]
repository = "https://github.com/SocialFinanceDigitalLabs/quality-lac-data-ref-postcodes"
license = "OGL-UK-3.0"
packages = [
    { include = "qlacref_postcodes" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
rsa = "^4.7.2"

[tool.poetry.dev-dependencies]
pandas = "1.0.5" # Matches pyodide version for pickle compatibility

[tool.poetry.extras]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
