
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T12:33:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "79601f7c57f63a0a2f2f0b75d1f4209ed17aa3cc",
 "version": "6.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
