
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T11:23:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a134ce8c28d8243ea32c799cfb9100dbe8c80bf5",
 "version": "0.7.1.post.dev203"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
