[tool.poetry]
name = "colorhash"
version = "1.0.4"
description = "Generate color based on any object"
authors = [
    "dimostenis",
    "Felix Krull <f_krull@gmx.de>"
    ]
license = "MIT"
include = [
    "README.md",
    ]

readme = "README.md"
homepage = "https://github.com/dimostenis/color-hash-python"
repository = "https://pypi.org/project/colorhash/"

keywords = ["color", "hash"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/dimostenis/color-hash-python/issues"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.3"
black = "^20.8b1"
pytest = "^6.2.5"

[tool.isort]
profile = "black"
multi_line_output = 7
force_single_line = true

[tool.black]
line-length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
