[tool.poetry]
name = "nvn"
version = "4.0.0"
description = "nvn"
authors = ["Ardustri <social.linter@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
watchgod = "*"
click = "8.0.0"
pyyaml = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
