
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T12:48:41-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd5efa94409e228ef6adcb9a5878a39c9d3957f1",
 "version": "4.9.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
