
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T11:40:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7635bd0a96c7d4c4a62548aa5759e43f13b0892",
 "version": "0.7.1.post.dev195"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
