
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-26T16:58:11-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "514f7d563abe5acc3bbbfa4a22878e3c9cf136a6",
 "version": "1.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
