
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T11:15:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "efb61c1bfaae8ce697a9c306ddb28b302608c463",
 "version": "0.7.1.post.dev189"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
