# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_simulate.user.ipynb (unless otherwise specified).

__all__ = ['api2data', 'random_user']

# Cell
from ..imports import *

# Cell
def api2data(api_url):
    r = requests.get(api_url)
    return r.json()

# Cell
def random_user(api_url='https://randomuser.me/api/?exec=login'):
    return api2data(api_url)