# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import consensus_service_pb2 as consensus__service__pb2


class ConsensusServiceStub(object):
    """*
    The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS)
    messages for an HCS Topic via a specific (possibly open-ended) time range.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribeTopic = channel.unary_stream(
                '/com.hedera.mirror.api.proto.ConsensusService/subscribeTopic',
                request_serializer=consensus__service__pb2.ConsensusTopicQuery.SerializeToString,
                response_deserializer=consensus__service__pb2.ConsensusTopicResponse.FromString,
                )


class ConsensusServiceServicer(object):
    """*
    The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS)
    messages for an HCS Topic via a specific (possibly open-ended) time range.
    """

    def subscribeTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribeTopic': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribeTopic,
                    request_deserializer=consensus__service__pb2.ConsensusTopicQuery.FromString,
                    response_serializer=consensus__service__pb2.ConsensusTopicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.hedera.mirror.api.proto.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsensusService(object):
    """*
    The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS)
    messages for an HCS Topic via a specific (possibly open-ended) time range.
    """

    @staticmethod
    def subscribeTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.hedera.mirror.api.proto.ConsensusService/subscribeTopic',
            consensus__service__pb2.ConsensusTopicQuery.SerializeToString,
            consensus__service__pb2.ConsensusTopicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
