[tool.poetry]
name = "nawaka"
version = "0.1.0"
description = ""
authors = ["Tristan de Boer <info@tristandeboer.nl>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
pandas = "^1.3.4"
openpyxl = "^3.0.9"
requests = "^2.26.0"
loguru = "^0.5.3"
fuzzywuzzy = "^0.18.0"
tqdm = "^4.62.3"
simplekml = "^1.3.6"

[tool.poetry.scripts]
get_groups = "nawaka.groups.get_group_location:cli"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
