name: Ubuntu-test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up system and environment
      shell: bash
      run: |
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        sudo apt-get update -qq
        sudo eatmydata apt-get install --no-install-recommends git-annex-standalone aria2 git-remote-gcrypt lsof gnupg nocache
        sudo eatmydata apt-get install pandoc
        cd ..; pip install -q codecov; cd -
        git config --global user.email "test@github.land"
        git config --global user.name "GitHub Almighty"
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      shell: bash
      run: |
        pip install -r requirements-devel.txt
        python setup.py build
        pip install -e .
    - name: WTF
      shell: bash
      run: |
        datalad wtf
    - name: Run tests
      shell: bash
      run: |
        PATH=$PWD/tools/coverage-bin:$PATH
        python -m pytest -s -v --cov=remodnav --cov-report=term-missing .