
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T13:58:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2b648cc256bd2060eb2ae4097e0748de2d3eb8e",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
