
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-27T03:17:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "16c7ab35e5413243f6c5fed5df9e7044e7781d59",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
