[tool.poetry]
name = "relycomply_client"
version = "0.2.0"
description = "A python client for the RelyComply platform"
authors = ["James Saunders <james@relycomply.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4"
requests = "*"
pandas = "*"
gql = "3.0.0a1"
boto3 = "*"
dryenv = "*"
requests-toolbelt = "*"
littleutils = "*"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
dephell = "*"
sh = "*"
GitPython = "*"

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "setuppy", path = "setup.py" }


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
