
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T11:50:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "778389737c4e0f26eb20dffb9c2864419a3f009d",
 "version": "1.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
