name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install apt dependencies
        run: |
          sudo apt-get install -y bcftools zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev

      - name: Cache htslib
        id: cache-htslib
        uses: actions/cache@v2
        with:
          path: htslib-1.10
          key: ${{ runner.os }}-htslib

      - name: Build htslib
        if: steps.cache-htslib.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/samtools/htslib/releases/download/1.10/htslib-1.10.tar.bz2
          tar -vxjf htslib-1.10.tar.bz2
          cd htslib-1.10
          make
          cd ..

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Package installation
        run: pip install .[str]

      - name: Run tests
        run: PATH="${PATH}:$(pwd)/htslib-1.10" python -m pytest

      - name: Check command-line entrypoint
        run: PATH="${PATH}:$(pwd)/htslib-1.10" bcf-extras -h
