
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T16:54:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fd4e4ba82a26d107f85f856504d8a6fdcfbc81d",
 "version": "0.4.6b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
