
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/ol_openedx_sentry:sentry_package

from setuptools import setup

setup(**{
    'description': 'An Open edX plugin to enable error tracking with Sentry',
    'entry_points': {
        'lms.djangoapp': [
            'ol_openedx_sentry = ol_openedx_sentry.app:EdxSentry',
        ],
        'cms.djangoapp': [
            'ol_openedx_sentry = ol_openedx_sentry.app:EdxSentry',
        ],
    },
    'name': 'ol-openedx-sentry',
    'version': '0.1.1',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        '',
        'ol_openedx_sentry',
        'ol_openedx_sentry.settings',
    ),
    'namespace_packages': (
    ),
    'package_data': {
    },
    'install_requires': (
        'Django>2.0',
        'sentry-sdk<2.0.0,>=1.3.1',
    ),
})
