
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-28T20:42:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c9b67825019b221927343a18a3c00001ae92aa2",
 "version": "2.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
