
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T12:08:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5976a4d296d24e5d3e61bdc0677de8f82c6fdea",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
