[tool.poetry]
name = "plotly-resampler"
version = "0.1.0"
description = "Visualizing large time series"
authors = ["Jonas Van Der Donckt", "Emiel Deprost", "Jeroen Van Der Donckt"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
jupyter-dash = "^0.4.0"
dash-bootstrap-components = "^0.13.1"
plotly = "^5.3.1"
dash = "^2.0.0"
lttbc = "^0.2.0"
orjson = "^3.6.4"
trace-updater = "^0.0.1"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.2.0"
numpy = "^1.21.2"
pandas = "^1.3.4"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
black = {version = "^21.11b1", allow-prereleases = true}
pdoc3 = "^0.10.0"
selenium = "^4.1.0"
pytest-selenium = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
