
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T14:12:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb58a14a467b620e5fa2ffe866acdecdb60dd83e",
 "version": "1.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
