[tool]
[tool.poetry]
name = "media_hoard_cli"
version = "0.1.0"
homepage = "https://github.com/midwatch/media_hoard_cli"
description = "Top-level package for Media Hoard CLI."
authors = ["Justin Stout <midwatch@jstout.us>"]
readme = "README.rst"
license = "MIT"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.8',
]

packages = [
    { include = "media_hoard_cli" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
click = "*"
python = "^3.8"

[tool.poetry.dev-dependencies]
bump2version = "*"
isort = "*"
pycodestyle = "*"
pydocstyle = "*"
pylint = "*"
pytest = "*"
yapf = "*"

[tool.poetry.scripts]
media_hoard_cli = 'media_hoard_cli.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
