import cv2 as cv

FONTS = [cv.FONT_HERSHEY_SIMPLEX, cv.FONT_HERSHEY_PLAIN, cv.FONT_HERSHEY_DUPLEX, cv.FONT_HERSHEY_COMPLEX,
         cv.FONT_HERSHEY_TRIPLEX, cv.FONT_HERSHEY_SCRIPT_SIMPLEX, cv.FONT_HERSHEY_SCRIPT_COMPLEX]

CHARSET_ALPHA_LOWER = "abcdefghijklmnopqrstuvwxyz"
CHARSET_ALPHA_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
CHARSET_ARABIC_NUMERALS = "0123456789"
CHARSET_ALPHANUMERIC = CHARSET_ALPHA_LOWER + \
    CHARSET_ALPHA_UPPER + CHARSET_ARABIC_NUMERALS
