
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T11:16:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad4ceb0993d4d1e9a49fe632242380b9bd5565ec",
 "version": "0.4.dev2148"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
