# Form implementation generated from reading ui file '/home/detlev/Development/Python/Eric/eric7-21.12/eric/eric7/Preferences/ConfigurationPages/WebBrowserInterfacePage.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WebBrowserInterfacePage(object):
    def setupUi(self, WebBrowserInterfacePage):
        WebBrowserInterfacePage.setObjectName("WebBrowserInterfacePage")
        WebBrowserInterfacePage.resize(555, 133)
        self.verticalLayout = QtWidgets.QVBoxLayout(WebBrowserInterfacePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(WebBrowserInterfacePage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line9 = QtWidgets.QFrame(WebBrowserInterfacePage)
        self.line9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line9.setObjectName("line9")
        self.verticalLayout.addWidget(self.line9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(WebBrowserInterfacePage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.styleComboBox = QtWidgets.QComboBox(WebBrowserInterfacePage)
        self.styleComboBox.setObjectName("styleComboBox")
        self.gridLayout.addWidget(self.styleComboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(WebBrowserInterfacePage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.styleSheetPicker = EricPathPicker(WebBrowserInterfacePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleSheetPicker.sizePolicy().hasHeightForWidth())
        self.styleSheetPicker.setSizePolicy(sizePolicy)
        self.styleSheetPicker.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.styleSheetPicker.setObjectName("styleSheetPicker")
        self.gridLayout.addWidget(self.styleSheetPicker, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(537, 41, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(WebBrowserInterfacePage)
        QtCore.QMetaObject.connectSlotsByName(WebBrowserInterfacePage)

    def retranslateUi(self, WebBrowserInterfacePage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("WebBrowserInterfacePage", "<b>Configure User Interface</b>"))
        self.label_2.setText(_translate("WebBrowserInterfacePage", "Style:"))
        self.styleComboBox.setToolTip(_translate("WebBrowserInterfacePage", "Select the interface style"))
        self.label_3.setText(_translate("WebBrowserInterfacePage", "Style Sheet:"))
        self.styleSheetPicker.setToolTip(_translate("WebBrowserInterfacePage", "Enter the path of the style sheet file"))
from EricWidgets.EricPathPicker import EricPathPicker
