# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "pip"
    # Files stored in `requirements` directory
    directory: "/requirements"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"