
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T23:37:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "946f0e688d73df84f9f5998a6c82adaeb2315e3e",
 "version": "2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
