
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T11:08:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b978235c1f0b3677d592f77d21fc1d48d6e439bf",
 "version": "0.7.1.post.dev172"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
