# Generated by Django 3.2.2 on 2021-11-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
