[tool.poetry]
name = "orm_right_version"
version = "0.1.0"
description = ""
authors = ["TheBatya3 <86134076+TheBatya3@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
black = "^21.11b1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
