
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T09:49:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "341e2fb0993fe001e64350814270818de3be43ae",
 "version": "0.8.01"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
