
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-12-03T17:14:48-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "65fcfd5efbb9f82db787684c9ce7d20e7e820f55",
 "version": "v0.25.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
