[tool.poetry]
name = "durham-directory"
version = "1.3.0"
description = "Python Bindings for the Durham University (UK) Directory"
authors = ["John Maximilian <2e0byo@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/2e0byo/durham-directory"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
bs4 = "^0.0.1"
lxml = "^4.6.3"

[tool.poetry.scripts]
durham-directory= 'durham_directory:main'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
