
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T15:30:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "66bfc307009bec7ab295cfcb4edc442ec2393888",
 "version": "0.25.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
