
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T18:23:06-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dfa18701c2ed8705d776f4da59637b7c49b427f",
 "version": "0.15.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
