[tool.poetry]
name = "ubConvert"
version = "1.2"
description = "Time, Temperature, Speed & Distance, Volume, Weight conversion module"
authors = ["ZennDogg, Utility_Belt Designs, Tacoma, WA"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
