[tool.poetry]
name = "django-browsable-router"
version = "0.2.1"
description = "A Django REST Framework router that can show APIViews and include other routers as navigable urls in the root view."
authors = [
    "Matti Lamppu <lamppu.matti.akseli@gmail.com>",
]
packages = [
    { include = "browsable_router" },
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/MrThearMan/django-browsable-router"
repository = "https://github.com/MrThearMan/django-browsable-router"
keywords = [
    "django",
    "djangorestframework",
    "drf",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Framework :: Django",
    "Framework :: Django :: 1.10",
    "Framework :: Django :: 1.11",
    "Framework :: Django :: 2.0",
    "Framework :: Django :: 2.1",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]
include = [
    "README.md",
    "LICENSE",
]
exclude = [
    "tests",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/MrThearMan/django-browsable-router/issues"

[tool.poetry.dependencies]
python = ">=3.6.1,<4"
Django = ">=1.10"
djangorestframework = ">=3.7.0"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
# For testing and CI
pytest-cov = "^2.12.1"
pytest-django = "^4.4.0"
pre-commit = "^2.13.0"
tox-gh-actions = "^2.7.0"
tox = "^3.24.4"
coveralls = "^3.2.0"
# For documentation
mkdocs = "^1.2.2"
# For code style
flake8 = "^3.9.2"
mypy = "^0.910"
django-stubs = "^1.9.0"
djangorestframework-stubs = "^1.4.0"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
skip_gitignore = "True"
lines_after_imports = 2

[tool.pylint.MASTER]
ignore-paths = [
    "tests/*",
    "docs/*",
    ".venv/*",
    ".tox/*",
]

[tool.pylint.messages_control]
disable = "C0330, C0326, C0114, C0115, C0116, R0903, R0914, R1721, W1203"

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.miscellaneous]
notes = "FIXME,XXX,BUG"

[tool.mypy]
python_version = 3.9
warn_return_any = "True"
warn_unused_configs = "True"
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]

[tool.django-stubs]
django_settings_module = "tests.django.settings"

[tool.coverage.run]
relative_files = true

[tool.coverage.report]
omit = [
    "tests/*",
    "docs/*",
    ".venv/*",
    ".tox/*",
]
exclude_lines = [
    "if TYPE_CHECKING:",
    "except ImportError:",
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py{36, 37, 38, 39}-django{110, 111, 200, 201, 202, 300, 301, 302}
isolated_build = true

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39

[testenv]
whitelist_externals =
    poetry
setenv =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = tests.django.settings
deps =
    py36,py37: typing-extensions

    django110: Django>=1.10,<1.11
    django111: Django>=1.11,<1.12
    django200: Django>=2.0,<2.1
    django201: Django>=2.1,<2.2
    django202: Django>=2.2,<2.3
    django300: Django>=3.0,<3.1
    django301: Django>=3.1,<3.2
    django302: Django>=3.2,<3.3

    pytest-cov
    pytest-django
commands =
    coverage run -m pytest -vv -s
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
