
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T15:13:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc6515307c2d3e2865b776703d3d8ef208ec83b2",
 "version": "1.6.0a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
