# Generated by Django 3.2.8 on 2021-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djplacedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.IntegerField(choices=[(0, 'State'), (1, 'County'), (2, 'City'), (3, 'Tract')]),
        ),
    ]
