
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T15:13:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b113a49e7592059cbd3d5002bbb09f9f838b226",
 "version": "v0.4.0b6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
