
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-04T10:20:50+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "f464ef803db9cc6990b0b44825aad1b2a10a7eb3",
 "version": "0.3.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
