
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T17:01:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "36732bfccb7717faaab178f874d4f41457cb7d12",
 "version": "6.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
