[tool.poetry]
name = "secread"
version = "0.1.1"
description = "This Python module allows to retrive secrets from Thycotic Secret Server. It utilizes the REST API"
authors = ["Josef Fuchs <j053ff0x@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.18.0"
types-requests = "^2.25.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pylama = "^7.7.1"
pytest = "^6.2.5"
mypy = "^0.910"
requests-mock = "^1.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
