[tool.poetry]
name = "FreelanceAPI"
version = "v0.1.2-beta"
description = "FreelanceAPI is a module for reading & evaluating export files from the Freelance control system."

license = "GNU"

authors = ["Peter Schwarz <p.schwarz1994@outlook.de>"]

readme = 'README.md' 

repository = "https://github.com/DarkJumper/FreelanceAPI"
homepage = "https://github.com/DarkJumper/FreelanceAPI"

[tool.poetry.dependencies]
python = "^3.9.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
