
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T15:50:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "88b80b56dc0e80d824c4897d9c1b818b41ddefe5",
 "version": "1.6.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
