
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T11:32:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9c3ee3c763ee3164099456d8cbf94ed38636762",
 "version": "0.7.1.post.dev205"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
