
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T00:23:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7328c23ab79dcff364745c65f35e72555c25721",
 "version": "0.4.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
