
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T22:02:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1df7ef99f515e083d28d5347f7d5779ec8581303",
 "version": "0.post1.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
