
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T11:56:58+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "26de387af184dd9dbf7fe362031c7efb8b2ab4c7",
 "version": "2.9.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
