[tool.poetry]
name = "decode"
version = "0.6.1"
description = "DESHIMA code for data analysis"
authors = [
    "Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>",
    "Tsuyoshi Ishida <tishida@ioa.s.u-tokyo.ac.jp>",
]
keywords = [
    "astronomy",
    "submillimeter",
    "spectroscopy",
    "deshima",
    "data-analysis",
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/deshima-dev/decode/"
documentation = "https://deshima-dev.github.io/decode/"

[tool.poetry.dependencies]
python = ">=3.7, <3.10"
astropy = "^4.3"
matplotlib = "^3.2"
netcdf4 = "^1.5"
numpy = "^1.19"
scikit-learn = "^1.0"
scipy = "^1.4"
tomli = "^1.2"
tqdm = "^4.62"
xarray = "^0.18"

[tool.poetry.dev-dependencies]
black = "^21.10b"
ipython = "^7.29"
myst-parser = "^0.15"
pydata-sphinx-theme = "^0.7"
pytest = "^6.2"
sphinx = "^4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
