[tool.poetry]
name = "sleepstudyparser"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["debakarr <debakar.roy@outlook.com>"]
homepage = "https://github.com/Dibakarroy1997/sleepstudyparser"
repository = "https://github.com/Dibakarroy1997/sleepstudyparser"
keywords = ["sleepstudy", "windows11"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
