
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T09:10:27-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d499a69e034f51d1d59e2a2dc1010e735229b24c",
 "version": "1.92.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
