
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T11:18:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca3e79021a2358ffd967110155a7df0c67b9f5bd",
 "version": "1.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
