
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T10:53:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a434dd8028e65c3bd15cb48590a79c51eff22418",
 "version": "0.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
