# https://docs.readthedocs.io/en/latest/config-file/index.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

formats:
  - htmlzip
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: requirements/docs.txt

sphinx:
  fail_on_warning: true
