[tool.poetry]
name = "envswitcher"
version = "0.1.0"
description = "Switch between envfiles"
authors = ["Jack Reilly <jackdreilly@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
typer = { version = "<0.4", extras = ["all"] }

[tool.poetry.scripts]
es = "envswitcher:app"

[tool.poetry.dev-dependencies]
black = { version = "^21.11b1", allow-prereleases = true }
pytest = "^6.2.5"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
