[tool.poetry]
name = "crunch-statuspageio"
version = "0.3"
description = "Python client library for statuspage.io"
authors = ["Adrien Pensart <adrien.pensart@corp.ovh.com>"]
license = "MIT"
packages = [
    { include = "statuspageio" },
]

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
requests = "^2.26.0"
munch = "^2.5.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.master]
jobs = 4
[tool.pylint.messages_control]
max-line-length = 180
disable = """
too-many-arguments,invalid-name,too-many-public-methods,too-many-instance-attributes,duplicate-code,too-many-nested-blocks,too-many-branches,too-many-return-statements,too-many-statements,too-many-locals,too-few-public-methods,too-many-ancestors,abstract-method,anomalous-backslash-in-string,broad-except,too-many-lines,import-outside-toplevel,logging-fstring-interpolation,protected-access,using-constant-test,missing-module-docstring,missing-function-docstring
"""
