[tool.poetry]
name = "vanoma-api-utils"
version = "0.8.0"
description = "Python utils for vanoma APIs"
authors = ["Vanoma <contact@vanoma.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.9"
djangorestframework = "^3.12.4"
djangorestframework-camel-case = "^1.2.0"
phonenumbers = "^8.12.37"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
