
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T11:33:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3006032b5b5904cec6fa2f3a169346e3c34b2e40",
 "version": "0.7.1.post.dev193"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
