[tool.poetry]
name = "accelrotate"
version = "1.0.0"
description = "Rotate linux devices (screens, touchpads etc) based on accelerometer"
authors = ["granitosaurus <bernardas.alisauskas@pm.me>"]
license = "GPLv3"
include = ["accelrotate.py"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.0"

[tool.poetry.scripts]
accelrotate = 'accelrotate:cli'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
