
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T05:58:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "912c991c813fc57c9da819a5d8bb7757bef94bc3",
 "version": "1.15.0.post.dev607"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
