
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T17:25:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5da9de34c48e8f1d8974a25dba7b64c65f3a991c",
 "version": "1.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
