
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T10:06:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6b9464ba7ceea2af477331e714899a795152e62",
 "version": "1.15.0.post.dev621"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
