
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T11:44:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "99f31a3e2fb3d2c92af3fc770df71430e3828ad8",
 "version": "0.7.1.post.dev180"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
