[build-system]
requires = [
    "wheel",
    "setuptools~=57.0.0",
    "requests~=2.26.0",
    'lxml~=4.6.4',
    "pytest~=6.2.5",
    "coverage~=6.1.2"
]
build-backend = "setuptools.build_meta:__legacy__"