# This is a basic workflow that is manually triggered

name: Run examples

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Optional: Inputs the workflow accepts.

jobs:
  examples:
    runs-on: ubuntu-latest
    env:
      LALPULSAR_DATADIR: ${{ github.workspace }}/ephem
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install package and chainconsumer
      run: |
        python -m pip install --upgrade pip
        pip install -e ${GITHUB_WORKSPACE}[chainconsumer]
    - name: Run all the examples
      run: |
        source bin/get-and-export-ephemeris.sh
        python $GITHUB_WORKSPACE/examples/run_all_examples.py
    - name: Save output files as artifacts (*.sft files excluded!)
      uses: actions/upload-artifact@v2
      with:
        name: "examples-${{ github.sha }}"
        path: |
          PyFstat_example_data
          !PyFstat_example_data/*/*.sft
