
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T11:39:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d86895d67f40291babb161657d0ab557a18ee62",
 "version": "0.7.1.post.dev207"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
