
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T22:55:01+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3bb60265d3b58fb6afe5b41aebd2e2225bc5b45a",
 "version": "0.2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
