[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | build
  | dist
)/
'''

[tool.coverage.run]
branch = true
source = ["django_drf_utils"]
omit = [
  "*/tests/*"
]

[tool.tox]
legacy_tox_ini = '''
[tox]
envlist = clean,py37,py38,py39,report
skipsdist = True

[testenv]
deps =
    pytest-cov
    pytest-randomly
    pytest-xdist
    .[test]
depends =
    {py37,py38,py39}: clean
    report: py37,py38,py39
commands = pytest {posargs: -n 4 --cov --cov-append --cov-report=}

[testenv:report]
deps = coverage[toml]
skip_install = true
commands =
    coverage report

[testenv:clean]
deps = coverage[toml]
skip_install = true
commands = coverage erase
'''


[tool.django-stubs]
django_settings_module = "tests.settings"
[tool.mypy]
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
[[tool.mypy.overrides]]
module = ["assertpy", "pythonjsonlogger.*"]
ignore_missing_imports = true


[tool.pylint.'MESSAGES CONTROL']
disable = "line-too-long,invalid-name,too-few-public-methods,too-many-instance-attributes,too-many-arguments,missing-docstring,fixme"
output-format = "text"
