
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T17:32:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "28c517f3cffb2cbbaa207547da1a50fed0bd761e",
 "version": "0.1.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
