
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T07:07:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2aa89d4e4f0608a19511d8e3dc799b89faaa924d",
 "version": "1.15.0.post.dev611"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
