[tool.poetry]
name = "census-shapefiles"
version = "1.1.2"
description = "Library to get census shapefiles"
authors = ["Zach Perkitny <zperkitny@gmail.com>"]
readme = "readme.md"
repository = "https://gitlab.com/zachperkitny/census-shapefiles"

[tool.poetry.dependencies]
python = "^3.6.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
