[tool.poetry]
name = "clear-s2s"
version = "0.1.5"
description = ""
authors = ["Your Name <you@example.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2.6"
requests-pkcs12 = "^1.13"
xmltodict = "^0.12.0"
Jinja2 = "^3.0.2"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

