
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T11:40:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c944f17701651c65635eeb047f33e1094c35c79",
 "version": "v0.4.0b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
