[tool.poetry]
name = "asdf_cy"
version = "0.1.0"
description = ""
authors = ["reona <c0116129a7@edu.teu.ac.jp>"]
build = "build.py"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
Cython = "^0.29.24"
numpy = "^1.21.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0", "cython", "numpy"]
build-backend = "poetry.core.masonry.api"
