[tool.poetry]
name = "finjet"
version = "0.1.3"
description = "Dependency injection like FastAPI."
authors = ["elda27 <kaz.birdstick@gmail.com>"]
license = "Apache2.0"
readme = "README.md"
keywords = [
  "Dependency injection",
  "DI",
  "Inversion of Control",
  "IoC",
  "Factory",
  "Singleton",
  "Design patterns",
]
classifiers=[
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = {version="*", optional=true}

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"
flakehell = "^0.9.0"
pydantic = "^1.8.2"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
poethepoet = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flakehell]
extended_default_ignore=[]

[tool.poe.tasks]
test = "python -m pytest --cov=finjet"
