
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T20:30:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffa0e717f4be677a722ddf1b7b970483211ab16a",
 "version": "0.5.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
