
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T15:47:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b60bd14899e1bb8bdc41ba6994aa90cfe430143e",
 "version": "1.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
