[tool.poetry]
name = "beets-beetfs"
version = "0.8.0"
description = "A beets plugin for mounting a FUSE filesystem of audio items"
authors = ["Drew Abbott <abbotta4@gmail.com>"]
license = "MIT"
packages = [
	{ include = "beetsplug" },
]

[tool.poetry.dependencies]
python = "^3.6"
beets = "^1.6.0"
pyfuse3 = "^3.2.1"
mutagen = "^1.45.1"
trio = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
