# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateSession.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43reateSession.proto\x12\x11opentera.protobuf\"B\n\rCreateSession\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x08reply_to\x18\x03 \x01(\tb\x06proto3')



_CREATESESSION = DESCRIPTOR.message_types_by_name['CreateSession']
CreateSession = _reflection.GeneratedProtocolMessageType('CreateSession', (_message.Message,), {
  'DESCRIPTOR' : _CREATESESSION,
  '__module__' : 'CreateSession_pb2'
  # @@protoc_insertion_point(class_scope:opentera.protobuf.CreateSession)
  })
_sym_db.RegisterMessage(CreateSession)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATESESSION._serialized_start=42
  _CREATESESSION._serialized_end=108
# @@protoc_insertion_point(module_scope)
