# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TeraMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11TeraMessage.proto\x12\x11opentera.protobuf\x1a\x19google/protobuf/any.proto\"4\n\x0bTeraMessage\x12%\n\x07message\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')



_TERAMESSAGE = DESCRIPTOR.message_types_by_name['TeraMessage']
TeraMessage = _reflection.GeneratedProtocolMessageType('TeraMessage', (_message.Message,), {
  'DESCRIPTOR' : _TERAMESSAGE,
  '__module__' : 'TeraMessage_pb2'
  # @@protoc_insertion_point(class_scope:opentera.protobuf.TeraMessage)
  })
_sym_db.RegisterMessage(TeraMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TERAMESSAGE._serialized_start=67
  _TERAMESSAGE._serialized_end=119
# @@protoc_insertion_point(module_scope)
