
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T17:55:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "98a8ed7f3a5e621d4d19b5d461c41a97bb69b4e7",
 "version": "0.25.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
