[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[metadata]
name = 'lyceum'
version = '0.1.0'
license = "ISC license"
url = 'https://framagit.org/benabel/lyceum'

[project]
name = "lyceum"
authors = [{ name = "Benjamin Abel", email = "dev.abel@free.fr" }]
description = "Un paquet Python utile pour la programmation en lycée."
dynamic = ["version"]
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Education',
    'License :: OSI Approved :: ISC License (ISCL)',
    'Natural Language :: French',
    'Programming Language :: Python :: 3'
]

[project.urls]
Home = "https://framagit.org/benabel/lyceum"

[tool.pytest.ini_options]
addopts = "--ignore=setup.py"
testpaths = ["tests"]
