
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T16:38:32-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9f7d2e8e29832c748c11e5893f137100b014e9f",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
