
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-27T09:58:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aaeb1293bc86359da328b5f9d0c71027a70c49c7",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
