
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T13:24:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "565a1628e7a644ff3cd49425fba7ed7cccfd69b8",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
