
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T11:53:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3673446ce645802ab4b610ff9ccbd0f1c490756",
 "version": "0.7.1.post.dev199"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
