
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T14:52:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a75776965a720f82b5f660eb66288bdbce3ef23a",
 "version": "2021.11.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
