[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "interviewing"
authors = [{name = "Alec Johnson", email = "alec@ayyjohn.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.8"

[project.urls]
Home = "https://github.com/ayyjohn/interviewing"
Source = "https://github.com/ayyjohn/interviewing"
Tracker = "https://github.com/ayyjohn/interviewing/issues"