[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "python-rofi-phfn"
authors = [
	{name = "Paul Hoffmann", email = "phfn@phfn.de"},
	{name='Blair Bonnett', email='blair.bonnett@gmail.com'},
	{name='Marco Köpcke', email='marco.koepke@tudock.de'}
	]
readme = "README.rst"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

[tool.flit.module]
name = "rofi"

[project.urls]
Source = "https://github.com/phfn/python-rofi"
