
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T09:40:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5da4666284cbb536101ece78b9a53c7f749c36f",
 "version": "1.15.0.post.dev679"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
