[tool.poetry]
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
description = "Python subcommands made easy."
license = "MIT"
name = "psme"
packages = [
  {include = "psme"},
]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.semantic_release]
branch = "main"
build_command = "poetry build"
commit_author = "Clay McLeod <clay.l.mcleod@gmail.com>"
commit_message = ""
commit_subject = "chore: bumping version to v{version}"
upload_to_release = "false"
version_source = "commit"
version_variable = "pyproject.toml:version"
