[tool.poetry]
name = "test_poetry_deps"
version = "0.1.0"
description = ""
authors = ["Skylar Kerzner <skerzner@community.com>"]

[tool.poetry.dependencies]
python = "~3.8"
numpy = "^1.21.4"
pandas = "^1.3.4"
emoji = "^1.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
