
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T18:00:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b19539b05ac66b3e78afee2fcdfb8d1a3bba0190",
 "version": "0.4.6b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
