# Generated by Django 3.2.4 on 2021-06-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DagRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.TextField()),
                ('created', models.DateTimeField()),
                ('creator', models.TextField()),
                ('status', models.TextField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running')),
            ],
            options={
                'unique_together': {('dag', 'created')},
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('attempt', models.IntegerField(default=1)),
                ('status', models.TextField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='waiting')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('ended', models.DateTimeField(null=True)),
                ('dag_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.dagrun')),
            ],
            options={
                'unique_together': {('dag_run', 'task', 'attempt')},
            },
        ),
    ]
