# Generated by Django 3.2.4 on 2021-07-02 19:59

from django.db import migrations, models
import workflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dagrun',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='host',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dagrun',
            name='created',
            field=models.DateTimeField(default=workflows.models.current_time),
        ),
        migrations.AlterUniqueTogether(
            name='taskrun',
            unique_together={('task', 'dag_run', 'attempt')},
        ),
        migrations.AddIndex(
            model_name='dagrun',
            index=models.Index(condition=models.Q(('status', 'running')), fields=['status'], name='workflows_dagrun_status_sparse'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(condition=models.Q(('status__in', ['running', 'waiting'])), fields=['status'], name='workflows_taskrun_stat_sparse'),
        ),
    ]
