
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T13:16:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "371756345775cac3418787f2e4b111117cd6fea3",
 "version": "1.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
