
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T16:04:12-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "36702f855e9ded775ad656d8aa8556f23d8baa5f",
 "version": "1.8.9-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
