
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-05T02:18:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ad68787c35e259cb7704b56d679659104d2494c",
 "version": "0.9.dev2149"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
