IIIlIIIlIIllllIIllllIIlIlIllIIIIlIIlIlIIIllllIIIIIIIIIlIlllIllllIIlIIIIIllIIlllIIlIllllIllIlllllII = 851
X96 = 166
IIlIIIlIIllllIlIlIIIlllllIIlllIIIIllIIlllIlIIllIlIIlIIlIIIIIlIIlllllIIIlIllIlIlIllllIIlllllIll = "BpVfojnpgmpPGsYtlHxQbwCBVjOpqRUNpwioDzmHKGIUwdvrwhkTqhBNkHxOlfMhAoFuhJXJigQqjvZ"
JmWilCJAPYklaBVSWcJRYrhElhCDcrSycJQwQnvoWKSpcPrOfJxehjJljEbamxMpRENqkBlFpYZyfTz92 = "otOTqgkCTSKZPfAtchhIIhbXXuCoXKSHAehHenmdndFsWbUanmiQZmHgYRZYNkQYDsccfhdaOLukHiM"
IlllIlIlllIllIIIIIIlIlIlIIIlIIIllllllIIlllIllllIIIIlIIIIllIlIlIIlIIllIIllIIIlllIIIlIlIIlll = "KqMyADtPtmzupcjdPODmCnwwioIDMbGflHLjeGtJRDnnQIkXaKnciCxASGwrMWYLSqtMdVObIAjKNsQ"
B88 = 264
d163855921807381986 = 295
lllIlIlIlllIlIlIIIIlIllIIllIlllIIlIIllllIlIlIllIIIIIllIlIllIIlIIIIIIIIllllIlIlIIIIIl = "IahsziNGQokNFUSpkZzkeTgzvHxAfafEIMRgAhohEuBWUSqqOgXTodSYfbbIhPTmZWndNYNbvXxiRIW"
l82 = 348
aAAAAAaAaAaAaaaaaaaAaaAAAAAaaAaAAaAAaaAAAAaaaAaaAAaaaaAAAAAaAaaAAaaaAAAAaAAaaAaa = "poaqrivCQOuMskJqDpjViRjtyYCgGFgtEekbJWKZLpUVGPjmDytYjcsxwkIStrXMonXfiNGaJwaKliV"
AAAaaaAaaAAAaAaaaaAaaaAAAAAaaaAAAAAAaaAaAaAAAAaAaaaAAaaAaaaAaAaAAaAaaaaAAAAAAA = "xByFHoRfzUfTulkZcTnznnIjuAvfWywDlgyttUQhprFisshEbunSIMCjNhanUAsFCZFXPnWnZFZftVw"
ikqQVTMaqaiYaJCkKLTCrVPbVKeSqlmZUHFVyJiwXWznqCGszRZgNyswmjIarNSUyBAkjDmpoxPryxa76 = 608
d1638559218073152574 = "lkXLaSEuWTnimaXLZWPbSSSQdLYIFETCGitTQRQZPBbQCHocYkVVxVvOwvfhUndlNFCOCtwImJtODex"
k72 = 463
IIIIlIlllIIIIlIIllIIIIlIIIIlIIllIIIlIlIlIlIlIIlIllIlIlllllllIIlIIllIll = "CDzfoopHlmqayfVZJWqlibGbNagsFnQxTNgfhBgvfNhGXhkfGpPlcAqDzOlRaMnfdDeLgRoNkMnUaHZ"
TeINdJhssfbWmIvrFKgChJcHDGcXNDVASIGMuBDpkWafwGDqijQUAAsZJqXXfaZeXviOslqXEviefwf68 = "aaebbbCoeLfEUiAKiuvcVYcVyXghfjwbzthyMJbmGYcoLuPuWBbsXkXRwqUggapfcUldcKbyKFmjjdn"
aaAAAAaAAaAAAAaAaAAAaAaAaaaAAAAaAAaaAaaAaaaAAaAAAaaAAAaaAaAAAaaaaA = "dypJsxWwmIwUNhCwoNjDuxOlGCjygSEvdeSVsTDygGwrKwPOKkbbIQThfuQjbiVbrzgRVCJZRMHcyhV"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "FyfPrfKgtfHsSTcmqMBqRDxUwvfltsIIVEsZWPwKYrGDvXotpcSgRdCpkWfTiqklefVnyclxiqPGQsl"
C62 = "FVJfBALuldrRfrVDOENPPhTHPylSWvTVrRDhVklCODlXhInvvgkNmzKauFwrhhMahxpfWWaGZNLMHuO"
D60 = 604
e1638559218072305258 = 723
K56 = "vgCDewayhMHiJxRlbbWzILmBdZTSZKNakxZmPGdZghGDfHoQzXUSDySwtlVITjrVVTzgsCEPPvaUGBk"
AaAaaaaAAAaaAAaAAaaaAAaAaaAaaAaAaAAAaAAAaAaaAAaAaAAaaa = "FIqRPvlyWAbHpQjilFcuhnDddnzCsApiMfBaMGqESbloGIcDMjzsAvGKlzFDuHPGOQgBVKweXBPtYOR"
aaAaaAAAaaaaaaaaaaaaAaaaaaAAAaaaaAaaaaaAAaaAaAaAAAAa = 101
AAAaaAaAaAaAAaaaaAaaaaaaAAAaaaaAaaaaAAAaaAaAaAAAaA = 387
W1638559218071931648 = 446
t46 = "GntjLbrCxzdbkoPEDFxCXxTaXNiFkGlWyrJhKVwtMHzXrCRSYVAwLnonGTKIuLQZaOMGMsLLvYCHKrF"
VyqisNcjSRsUPotRLzPPutiMashvIPRAiasekhgHrWozdAQRyXoSLybRqMIvuSJcZmXBBCBmdBkGJLK44 = 392
IRYUYiwBoCFEvvRaRKtRePZZfLEafypnYyYiAnXBzrRqJPxsgHlDGgRPItlAxDUpakFSussUNtTOCUf42 = 159
YzzwUElGpeOUoUWrFWfsuChsyHCpgZXmLijjRRBArAmryoiHZzVmwNstKuuigitGyeCyUJklBAqpYEl40 = "YkkmLSWxmnlDQmKliCSnyWLAmHCShpmhAmbWeqlDDuzwqfIBhNHMVuZgLNGzmaEzOQDbrOFKuhFWtGt"
AAaaAaaaaaaaAAAAaaaAAaaAAaaAAaaaAaAAaA = "DJpbCJIauaNdptRkVjBDHOICGgutKySuEpPZspbKFdJBpvXqBkbulVEHkKTciiGhnwJnvooisysBVsZ"
GHyzZGIjlObUWsxyUoSOaQcisyZAWarccjXkkcQCthuIaZCokuQZQjTbtVdOwtLvkxtPCbeDCsbTAZj36 = 293
bvNTOxbDglrKpjWzbKbYGEnBmVQIKHsxhAgjKKVjPySOfFeNXLNEupqHWEogWozXxrDAUPSqFeNFgGf34 = "AdITFSMVKcgQmXnVZfCAuDJtbCkaOuxObryrCMDRCYiXoPijTmOzKYgnpJjLxGpPbdblAyEigNKwqGG"
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = "GoHIxgAJegMqEVDNsLPdJQHokpQxUZmYrUsGoSDjMegXcikeSEEiUaliiQDSkPzChaSbLmeTalsgKoU"
AaAaAAaAAaAAAaaAAaAaAaAaaAAAaA = 333
eeeeeeeeeeeeeeeeeeeeeeeeeeee = 763
VVVVVVVVVVVVVVVVVVVVVVVVVV = "vvIZsNFztJrVwKpHeKfasMxTvBAaLjJYbuuYyQEAcspzhdRAWtZzibjdmfTuuwJZuzyaIIZBsfKOZkK"
Z163855921807093624 = 330
jDFUPNssfqLanAgWQlJkFmHYjPOsccNbcMqWaBdCQlOrWOfyatamrWBhddVAMVGGfCazhZklKlbuGeL22 = "hPxUhQVOcRlIyofXxtijNIqKffeRVjRAPZxFetUjOzkDBoZtFekXeElzqkbrPTCepzPQyGskmvyMPxT"
lIlIlIIlllllIIllIlII = "iGjsWAryNFnWoQvyegQJbrwNLMwhzNgxvfYoJpPQNXQdSIrFdDBlaYJQGglrZmvpCaEzDJFDyBSnQNP"
d163855921807076718 = "SezICroYjIYvNPMPYHhzYwZkDCXawzdvqhzXwyBUgJSzHdfTVPNmdKLJQxvqfzKCvvwErHIjxWdoqRM"
X16 = 165
yyyyyyyyyyyyyy = "LvPYwzRFOWofJggLkRgDpgKvrJhSIurxsjrCIwfqymbBmaQtKnNbdGSukEZHCeoMmtxatGJISrYTHnQ"
AUERSrOPfzqdsNdfyAeWUwDwqBCVMPJHHGbkyjvFuZxRCycNSuuEAfemoKfRNPFKdCIPaAstDluRkHf12 = "MySRiAXADesohFIZinDCyWnXBbYhxbsDKwZYwAhhpJMDefGjWnJinMZBlBryKxjyjuSberJIfhwULtJ"
aAaaaAaAaa = 316
XXXXXXXX = 448
B163855921807034446 = "UGBUlfEmGcCmcWJIXsTbwpOOYwQNYRRpzIOirjULZArnGbOngSZDauSBYBrbzRWqgYdzXPvvExfflmm"
e163855921807027324 = 574
r163855921807023762 = 255

import re as q1
from collections import defaultdict
from pathlib import Path as yXAkFcwHRhacPeohzrvENYMmLFtcQCqvGyaPLFDdYAsrLtGvaFDfHxeCkscnQdWJAQobXidUXWYETzF2
from typing import List
def detect_requests_calls(file_contents):
	B=defaultdict(list)
	for A in ('get','post','put'):
		for F in file_contents:
			llIIl=q1.search('requests\\.'+A+'\\(f?[\'\\"](.*)[\'\\"]\\)',F)
			if llIIl:z16385592180692251=f"{A.upper()} requests are made";aA=llIIl.group(1);FBhWWuQYEVqADQwHjbcGUuBeqnlBZzzPhjWAzkULTOTINMkFlRFmflFsMjcNQDkWTXmDHAofBlcglkY3=aA.split('?')[0].replace('https://','').replace('http://','').strip('"').strip("'");B[A].append(f"`{FBhWWuQYEVqADQwHjbcGUuBeqnlBZzzPhjWAzkULTOTINMkFlRFmflFsMjcNQDkWTXmDHAofBlcglkY3}`")
	LLLL=[]
	for (A,E) in B.items():
		if E:LLLL.append(f"{A.upper()} requests are made to {','.join(E)}")
	return LLLL
def detect_boto3_calls(file_contents):
	A=[]
	for llIIl in file_contents:
		B=q1.search('boto3.resource\\([\'\\"](.*)[\'\\"]\\)',llIIl)
		if B:A.append(B.group(1))
	if A:LLLL=(', '.join(A)+' resources are connected to.').strip(',');return LLLL
	else:return''
def detect_mongodb_calls(file_contents):
	for B in file_contents:
		A=q1.search('MongoClient\\([\'\\"].*@(.*)[\'\\"].*\\)',B)
		if A:llIIl=f"Connected to {A.group(1)}.";return llIIl
	return''
dYnJsAOJiToGmDmzlkmlEgOqNVInbxhdOMNJqBgSLhRiEpzQlvWcyFmwqkTSScFaIkKZDlMMXFDYDAs1 = 494
GGG = 290
DDDDD = 269
AaaaaAA = "kfnideEhoFcPhpRAFelhSwfxBpADpSazpuirFEiojIeZJuqmHlcLddMhUnNfuLiAJBDeHDDshSLmpdH"
f16385592180704139 = 298
sqiBeTaNTbigieunKnrdMEAGawYvljQpDdSoDiTrLQfmiqVaBaLhqginnpfLdCPhqUNOjrECcFIILLJ11 = 357
llIlIllIlllII = "DaUaguTAeXbgcsKqgeoDcSuIeRAwEXTYEQOituCYQDCIGvcyOttUQsOpvSUZlSdzwCepTvCXEcDelUI"
IllIIIllIlIlIll = 308
lIIIlllIIIlIlllIl = 360
LLLLLLLLLLLLLLLLLLL = 351
T21 = 285
Q1638559218070929323 = 763
byJqsqDozqlFVxHEqFBVELjJQZkzxnYwKMIvFPIZQVwfXRADyBiBwJYfGRuUXxpePLneRIItYAWyjnY25 = "XTPabZYjziDNGIiQiXhTGMCTBeojyHtrtWMNdQrTGTrDNNEeHcDygNLbrGboTDqQWBJitJqbSflJOmf"
Z27 = 207
t29 = 727
wEybdPAGcAfzucXvPcrDxsCMEYEQOuTdJZKisWkAcSLcmuDSNzMrEXPDKOymqLUiinTpHqDDQByMIrP31 = "KpQOjAgokPVXWBlJBQPbjaqbOPGYzywFXjkmKCOGDqpVHOeaWpsefSWtuzYeThJKNCZrpOrjdlkcyQT"
IlIIllIIllIlIlIIIIllIllIlIIlIIIll = "SgRAqqRjXZEYburgIJSiJDaDXkbjxogYIBubNZhWLVeotnPIeaZVSnqRhmQjSlUXQGFPtMRMwwzLNLz"
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 244
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 356
AaaAAAaaAAAAaAAAAaaaAAaAAaAAAAaAAaaAaaA = "lLFfyQgaaJIeqFfTpVfObIlwqOAHySBMFdWOJhMOVJwKwHAqMgEDuUiyELeHXhJmlTYtoROUtmAfsGx"
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 515
H163855921807175743 = "MgOBHRgYhLdZXNenrpBpzKXsjDKfSnVUsZwhxVWrcnLZTuxnAvycdMsfrrHnGptZlnMlbAzbVfscqzn"
e163855921807184945 = "VrPbUaigHrLAjPHSjmyVuXeQXMiLenUFCXNUURFeRfdJHqSABIuYzyvbGjzxHXcYKXVRhGEIXORKABa"
AaaaaaAAaAAAaaAaAAAAaaaaaaAAaaAAaaaAAaaAaaAaAAa = 400
G163855921807193849 = 503
n1638559218072017451 = "spHhbgpQQatzTvvPRzuBmAUiyvKMebzIllMQWQAwuTGKckDrvaifVIEUGohXhCFQfRDWysLhyumYOfW"
IlIlIlIlIlllIIIIIIIIIlllIIllIIlllllllllIIllIlIIIIIIIl = "VpRtNcPGlGKULlWPkrnoLiRCZOiJMwNJaHdfYUJZCIDnOflKBEYxAZAhaphdzQalaZOWBZPsQABPrTX"
ddddddddddddddddddddddddddddddddddddddddddddddddddddddd = 221
Z57 = "PRDYBgNLrjftwpkJchslCutzmMINmXaHzSeBsaFLmcyEttBiTpJFqqDnpYMbtFVCVyoCKdZnUqSuRpO"
AaAaAaAaaaaaAaAAAaAaaaaaAaaAaaAaAaAaAaaAAAaaAAAaaaAaAaaAaaa = 245
j61 = "viEZwisreXlLzxAQQNURezLmUIguyUufjFacsQYFhkAtMWUmCeNBISSDNvNpcxbndIIaantEQfemRdq"
o1638559218072447563 = 756
z65 = "fVISKWpXtYzNkYpNnyledQjaWXGZcFwXjDutNvGaOJltrTInSZqyuVKMwXHdbBIAondJSUtWRAsVUwP"
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "kHLCupouOjxnehgbRmMeGjaybhQBNReUkLjkaHdgyxojJEAmujJGaCuFDHMIxXSQFiwoqhcsukugCyo"
lIIllIllIlIlIlIllIlllllIIllIIlIIIIlIIIlllIlIllIlllIlllIlllIlIIIIllIIl = "eTiZYZVYLiKKoKkljVKkLsmXcpEiddyXTZvxRxoMxslloHcsajrxmtugsCCBDuhctLGEmohRDBnfDwg"
AAAAaaAaAaAAaAAaAaaaAAAaAaaAAaAaAAaAAaAAaaaaAaaAAaAAaaAaAAaaaaAAAaAaAaa = "AZbBepKThaMgGJpmizXRJDQbelnzWVqAxDPMJIQEeGFMFIQLKCbPSJGoznrJeCigYXxYeWCijJvMyYF"
sotvzxsSxsUnPesficylNJgBdvpAaHTRyUCufQFVgZqrgVyGzglmnHXPRnXDaedpXikvEMXmsXwwFDe73 = "WuBfhkDblcoHDfrotFtLnwpNhyKsQVDqUVhdGwlMXESCLbIseRBvuxhgGXHOTShrGHsMqiTFfaqpeIh"
llIIllIIlIIlIlIlIlllIIIlIIIIIIIlllIllIIlIIlIIlllIlIlIlIIIIIIIIllIlIlIIIIllI = "bHaBpjiDAMJJobcbXKEFLJponKhqdZYYqsvXVXxqPYhWAsqZtydwcKWIPxdzJCfeRjgZOgfliInrclJ"
XbcRomouEhFtJlXtcxxkCicXUumuonWCGBrBHLsZNDhpefwOlYAIsqMIddJEjcSwhjYBICKXCWUeQDW77 = "SDHubiQhPcReFFEQAmosuAHwLtITMkPmLaotpGJHhpTgYzmPUkYuRorrxNObQziwCbDaGxkFXiAjfgf"
I79 = "cUrrQPNGZMvrshFZSYuIgXDkQzikokSfTGtcIuqAujRfhYBLntqLFgPeOiIYYqFKcuFSSORWqZnSqjV"
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = 406
llIllIlIlIIlIIIIlIlIlIlIIlllIIlIllIIlllIlIlIIIIlIlIlIIllllIIIllIlllIlIIIlIIIIIlIIII = 300
IllIlIIllIlIlllllIIllllllIIlllIIllllIlllllllllllllIlllIllIlllIIllIIlIlIIlIlIllllllllI = "LlmrENEcQedXoqFJIqHMoLZxaxtHapZFMjcIumdTsvpwYHsQZUZkoDTNwqEFOneooLPOeIFZEkJOstl"
llllIllIIIIIlIIIIIIlIlIllIlllllIIlIllIIIIlllllIIIIllIIIlIIIIIlIlllIIllllIlIIIllIlllIIII = "qAdanHlqVlvQFHYwKlqkuBwUZnttgDXdocZfuBEagugyPXcrHAoUqtEZAYUYBHjFsnPzPhjpUfxpyjA"
x1638559218073962589 = "kqOhzjINfHDrSGBsHFZGFGauJMVDkedFYDlhxmNpXnxeMDtmODqjlsdTbkIEpryXeAjfjHUlNQWYFTQ"
rsvyIGeQLIAZDuXUuCwhNdpykOGRSGHuMzyMHUnXvDUnRjDtpvjdgsckDVvtSBolQaVYzkbPdSxpyxl91 = 578
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "WtamRrmFLWavBmFhUUqApuRDKvnVzrUBkHqJEESqNUUGwvyhwUKVoruUVGzqnEGtGFrEBiyYRNMrbYU"
lIIIllllllIlIIlIlIlllIlllIlIIIlIllIIIIlIlIllIllIlIlIIlIllIIIIIIlIIlIIIIIlIlIIIlIIlIIlllllIlIIlI = "RiWeqJMeqiBKCZXNmKjFrfHmCnYzYmEWPIfQNewxjfESSwqPCMJuqNtdIAaOaKxHSEdPzwypAwZLNiC"
lIlllIIlIlIlllIlIllllIlIIlIIIlllIIIIIlIllIIIIIlIlIIlIIIIIllIlllIlIlllIIlllIlIllIlIIllIIIlllIllIll = "ejPNIsKmfKJvgWcMasXzTkPIhabOHYGQXBGlwnGJdAIHiaVxraejyjAkWBVNOYtDXkhHyUJLCgGQiqA"
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = 501