DqppTPOdAHjccOGMSvMQVmmGRsXaBRUiPoPMwPfdxSidgvmSBCeXXjtKFLrPTDHuQzofbfjrGjCyzrP326 = "raWHDlizHeKnfBQeewHfkLMoawidbglkvnPHoqZQwaSgbAmkNTMPDZWJmpRiCOeVxShcmAwOqtvtNoQ"
a1638559218124725324 = "RPBETaVevyEnNhFgRtFbTNrPZefXUPUqwbHzOAboiNFBmoAffAtcyFgQOTwEEOIMWlgBJZnDlZYKOCH"
aaAaAAAaAaaAaaaAAaAaaAAaaaaaaAaAaAaaAaaaaAAaAAaAAAaaaaAaaaAaaAAaaAaAaAAaAAAAAAaAAAaAAaAaaaaAaaaAAAaAAAAAAaAaAaaaaaAAaaaAAAaAaaaAAaaAAaAAAAaaaAAaAaaAAaAAAAaAAaAAAaAaAaaaAaAAaaaAaAAAAAaaAAAaaAAaAaaAAAaaaAaaaaAAaaAAAAaAAaaAaaaAaAaAaAaaAaAaAAAaaAAaAAAaaAaAaaaAaAaaaAAAAAaaaAAAaaaaaaAaaAAaaAAaaAAaAAaaaaaAAAAAAAAaaAaaAAAAaaaAaa = 646
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = 245
n16385592181244233318 = "icLAJzPbgDpBygxtUvTdmwofRixZDvyPgDoJiYJgwaHPQXlxuVySeyEGDHZQbJNOQWEFJhcQYFqoWwo"
G316 = 620
N314 = 790
llllllIIIIlIIIlIllllIIIIlIlIIlIIlIlIIlIIlIIIIlIllllIlIlIllllIIlllIIIllIlIIIlllIIIlllllIIIlllIlIlllIIIIlIIIIlIlIlIIlIIlIIlIlllIIIIllIlIIIllIIIlIIlIlIIllllIllIIllIIllIIlllIlllllIlIllllIllIIIlllllIIIIlllIlIllIIlIIllIlllllllIIlIlIlIllllIlIIllIIlIIIlIlllllIlllllIIllllllIIllIlllIlIlIIllIIlIIIllIIllIlllllIIIIIIIIIlIII = "dWiolEkcMjhyLphcAdRLEjQLgZKqbuoEhjjMNnybYlcoKXDGVYoLCAVzhqtfZbOKOHfDXGrDVfnlRwr"
AAaaaAAAaAAAaAaaAAaaAAaAAAaaaaAaAaaaAAAaaaAAAAaAaaAAAAAAAaAAaAaaAaAaaAAaAAAAaaaaaAAaaAAAaaAaAAAAAAaaaAaaaaAAAAAaAAaaaAAAAaaaAaAAAaaAaaAAaaaaaAAAAAAAaaaAaAaAAAaaAaAaAaaAaAaAAaAaaaAAaAAaAaaAaaaAaaaAaAAAaAAAAaAaaAaAAaaaAAAAaAaaaaaAaaaAAaAAAAAAaAAAAAaaaaaAAAaaAAAaaAaaaaAaaAaaAaAaaaaAAAaAAaaaaaAaAaaaAaAaaAaAAAaAAA = 774
ePGSUCFkgrhdZgOAwNzFcsDtlybWQcBaSCtlqUUsSoNXKZWyHCSDgrFVWqQAhBPGvapYuKpkhuGeEVH308 = "fWmpRabMuVTSllMVnneaFmSnZNGPpRPXHZJBTVklVMYpeArkwaWztSfbTDqyGgGwapOwBqPDaKqiHKD"
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = 213
z1638559218123337304 = 664
IsfFiRpXhiBvFDKcyuJCntectqJQmfTyMDoGYHkNvPXgOrrVkywNCcUdAzpjiaKiFtkZSYFhJacQFQN302 = "MVvTWZHOSaZPnoIRonjTLtuEuntCbfsrzRtQuoaYMMpBgaIyQlmBJppISOCVozFHgzOPwfrmUQWkWsm"
AAAAAaAaAaaAaaAAAAAaAaaaaAaAAaAaAaAAAaAAaAAaaAAaAAaaAAAAAaAAaAAaaAAAAAAaAaAAaAAaAaaaaAaaAAAaAaaaAaAAAAaaaaAAaaAaAaAaaaaaAaaaaaAaaaAaaaAaAAaaAaaaaaAAaAAAAaaaaaAAAaAaAaaAaAAaAaaaAAaaAaaaAAaaAAaaaaaAaaAAAaAaaAaaaaAaaaaaaAAAAAaAaaaaaAaAAAAaaaAaaAAaAAaAaAaaAAaaaAaaaAaaaaaAAaAAAaaAAaaAaaaAaaAaAaAaaAaaaaaa = "HQfTSptVIcWuvQLIkRvagQFSBjxBgsXLeBaaZCzRefJtmPnyGxJFVTrXAobQccLeDgYWWZDLyFyNmAt"
F298 = 435
AhqsPLFkWNHEIEWaubTOEzMrviUuFuIsOzrXKrXfqMubBgFuRoHsOlkdMuJguhNfcugYqjvNzAsevSL296 = 622
U294 = "jWtmdRgojXHEvdPISqdvGWxHfcppvTDYZjEiUyrvgtAgFInqafSYSwVqNHPiqPDgDbHkhDkHrXUPXPY"
yFJJpWxnbdbVNUaxaaqwBdcWGIGtUEkIlmMRyjrlncISHWNRzFXIlWgxrIHWZiXJCvLXUMBpsvPPKyl292 = 298
G16385592181221974290 = 400
llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll = "IlaoVoXrpfTCodnpRYRuVRxkVWvdpoeGMOHVMAqOVULlMdgYYCUsiybeYQSoXbvMGJQaouhNtlJMuLX"
aAAAAAAAaAaAAAAAAAaaAAaaAAaaAaAAaaaaAaAAAaaAAAAaAAAAAaaAAAaaAaaAaAAAaAaaAaaaaaAaAaAaaaAAaAaAAAaAaAAAaaaAAAAAaAAaaAaAaaaaAAaAAaaAAaAaAAAaaAAaAaaAaaAAAaaAAAAaaaAaAAaAAaAAAAaAaAaaAaAaaAaaaAaAAaAAAAaAaaaAaaAaAaaaaAaaAaAAAaaaaAAaAAaaaaaaaaAaAaAaaAaAAaaAAAaAAaAAaaaAAAAaAAAaaaaaAAAaAaaAaaAaaA = 371
lIllIlIllIlllIIIIIIlIllIIlllIIlIlIlIlIlIIIIIlIIIlIIlIIIIllIllIIIIlllIllIIIlIIllIIlIllIIllllIIlllIlllIllIIIlIIllIlllIIlIIlIlIlllIIIlIIlIIllIIIllIIIIlIIlllllIlIIIllIlIIlIIIlllIIIIlIIlllIlIllIIllIlIllIlllIlIIIllIIllIIllIIllllIlIIlIIIlIlIllllIlIIllIIIlIllIlIIlIIlIlllIlIlllIllIIIIlIIIIlll = "pgrNkeXlHVEbHpphnUmYAqtfBCvVcawFBXQQNklZyRWwamoObbXhNqDTVrbePukhIfmGRNwSvDXhaWT"
J16385592181214397282 = "xpOtVNgOKpKBiDKlDMmJaeNXUHzROrlgJQdURrpTaEsztlMuZVYceZorvfsBsMzDniKSUTEipamFPvz"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 156
lIIlIIlIlIlIIIIIIIlIlIIllIIlIllIIIllIlIIlIIIllIIlllIIIlIIIIlIIlIllllllIIlIllllIlIllIlllIIllllIlIllIIIlIIIIIllIlllIIIIllllllllIIIIIlIIlllllllIlIIllIlllllIlIIlllIlIlIlllIlllIIlIIlIlllIlIIIIlIllIlllllIllIlIIlIlIIlllllIlllIlIllIIllIIIIlllIlIllllIIIIllIIlllIlllIlIIIIIllIlIIllIlIIIIl = 288
i16385592181209915276 = 765
aaAaAaAAaaaAaAaaAAaAaaaAAaAaaaaaAAaAAAaAAaAaaAaaaaAAaaAaAaaaAaaaaaaaaAaAaAAaAAAAAAaAaAaAaaAaaaaAAaaAAaAAAAaaAAaAaAAAAAaAaaaaAAAaAaAaAAAAAaaAaAaAAaaAaAaAAAAAAAAAaAaAAAAaaaAAaaaaaaaaaaaAaaaaAaAaaAaaaaAaaAaaaaAAaaAAaaAaaaAAAAAaAaAaAaaaaAaAaAaAaaAaaAAAAaAAaaaaaaaaAAaaaAAAaAAaaa = "DkGJRxEplmcRuQIAawqNuBZysqTGbfPPkIxNQvCIoFftBADjsZxiNXPDWXLGXRFGIgVQIhoVFCyzcSI"
mxTJxgqaxjBydlFatTCvQRDbiCvqvGlOPNKAPvSoWJkLDEIXnfwNQBKeZmwuFKVxidjBdONkFPDdPFx272 = "qikAgPKjVGsoIQJLtOgnmAydOmaArwdsOecywueckHuUCaktMXbLzJoyExLLhuvgPHGbpRFuyfgiejw"
gKgqFhxpugUmIqhpgIuTgMEtxJwRIpTctwZJKYmOMmCriWOmLwHdxXwDirawSgKfoJIDfccdcvrLdAy270 = 283
AAAaAAaaAaAAaaAAaAAAAaAaaaaaaaAaAAaAAaaAaaAAAaAaAAaaAaAaaAAAAaAAAaaAAaaAaaAaaAAAAaaaAaaaaaaAaAAaaaaAaAaaaAAAAAAaaAaAAaAAaAAaaaaaaaaAAaaaAaAAAAAAaaaAaaaAaAAaAAaAAAaaaAAAaaAaAaaAAaaAaaAAaaaaaAAaaAaAaaaaAaaaaAAAaAAaaaaaaAAaaAAaaAaaaAaAAAaAaaAAaaaaAAAaaAaAaAAAaAaaAAAAAaAa = "mkXtbTPtpyICksOLGgijBQFrARaiJpyoeXGuzxXGcruPfbhMKdSGFRPCHYHLtoXXPWDHErrEfuEGiFM"
llIIIlIIIIIIlIIIllIlllllllllIllIlllIllIIIlIIlllIIllIIlIIlIIIlllllIIIlIIlIllIIIlllIlIIIIlIllllIllIlllIIllIllIIIlIllIlIIlllIlIIllIIlIlIIIIIIIllIlIIlIlIllIIlIIlIlIIllIlllIIllllIIlllIIlllIllIllIIlIIIllIlIIlllllllIlIlIllIllIIIIIlIlIIllllIllIIlIIllIIIlIllllllIlllIIIIIIIIl = 333
YkoDPwcZeISzgCTOnmNUIQxScdgoMgGBxTjLzdWWGteeFXHsauYmBTrHcfqnIyDanMCxbscseLeimvY264 = "katMUDviCrhApqggkBdHByyaTiBWBcYYBnBWZKGxjreVXucxlvQGESytZiQYXPiWUkQYgIuKvlWXDKR"
djHzxYUHVOXMtADjDpbMYLfYNmOFIJKhDWXEAnwXDuFDhfvQsxgorBbSbtGFXJQcKUETlukZarhoDCN262 = 283
wrcurddZYAnppbtqMPHBddutPJQtysmxWZnnKdDCflziEqKRqxNisbPdnJORTjYoOjzVBiqydwQFPga260 = "PxPiLToMXYqzwOFsqefwfoGfLCFPnRQIsEBByFQxHeWffvadmTsSidihxBdDsSnxSBJSpypOJzsbwvP"
k258 = 484
czfExDaNREznmpxUOUKVKsUfebqdlwbyyeYWQNOZnzoJsYdBRaRJnPuYmLMWKrjpHrLyDYHlQnQMTAU256 = "JwDVFsPrJrXDcKtsdhgsqXnsrrOWyBEcnpIBKVwbMRDEdImhVcLiLnPAUzxBdHLGgOehTCUOsmzmQgm"
L1638559218119346254 = 285
Q252 = 454
AaaAAaAaAAAAaAAAAAaaaaAAaaaaaaAaaAAaaAaaAaAAAaaAAAAaAaAAAAaaaAAaAAAaAaAAAAAaAAaAaaaAaAaaAAaAaAAaaAAaaAaaAAaaAAaAAaaAaAaAAaaaAAAaAAAaAaaaAaaaAaAaAaAaAaAaaAAAaaAaAAaAAAAAaAAaAAaAAAAaaAaAAAaaAaAAAaaAAAaaAaaAAaaaAAaAaaaaAAAAAaaaaaAaaaaaaAAaAAAAAAAaAaAAaa = 311
A16385592181188965248 = 583
lIlIlllllIllIIIlllIllIlIlIllIllIIlIIllllllIIIIlllIllIlIIIlllIlIllIllIIlIlIIIIlIlllIIlIlIlllIIlIlllIIllllIllIIllllllIIlllllIlllIlIllIllIIIIllIlllIlIIIlIlIIIIlllIIllIIIIIIlIIllIIIlIllIIIllIllIlllllIIlIIIlIIIIllIlllIllIIIlllIllIIllIlIIlIlIllIIIlIlII = "IJunEudiikFVRvqDUleHcBnxvjqNdTMbTCMqrlWYoGnzWfNPFndtONvJXpDdZPhVUcYWJyerqtsuhps"
GDPQRzlPNSPWaPHeDjUQAiIGRvrRwZRhaAMmoGeqyaailsnQccAgTCaxIqYPJWESVFSmXaBoYQTVVXL244 = "MabKXcPdEgCsorxLNoeZaaWTXngsRTRhMesnPjGzXtuQmTGVgNANVQeYEaabvbSMwkVwuTnsUXGHPHL"
mJCaRMcjCXFdZiqGNOAoHphLjNBuVQxxtAuylydepYYeWcVxdnFJDLeAejNuBTnhTYwJwaRpGKAJcRw242 = 307
C16385592181182675240 = "KAFdncwehdOZTSTIHhNMtKbtfExWxuiTfJhuJrRZttXisQjXHpLupLeeQDPoQGHJURKxiTNdAIdkAKP"
a238 = "PhtKQChFLieocBiALxvBNNUaImdQlcDwxRiVbPiAwZOfdoxcWmpBKMkyyQqNWnxrwMFpvJLfGHoyahR"
q236 = 403
lIllIllllllllIlllIlllllIIlIIlIIIIllIlIIIIlIlIlllIlIlIlIlIlIlIllIIlllIIllIIIlllllIllIlIllIlllllIlIIlIIIllIlllIlIIlIIlIIIllllIlIlIllIIllIIlIIlIlIIlllIIIlIIIIllIIIIllllllllIlllIllIIlIIIIIIIlIIllIlIIIllIIIIlIlIlIIlIlIlllllIIIllllIlIIIIIIl = "kLOPZAPdPuuDrxNSJMhQgJqrjdcCRNRZJipsYQMcOQfoqNhJdVIHtblZIYRYYdMqvGCCjtopIJDlaon"
B16385592181178021232 = 304
J16385592181176815230 = "RAeNpFPTTDvbxTsdTvfDrPKQVdWwPeBMPnqfFZbOjkJDbwhCZGPOaLMrbstLIEQdyAgkOlMbadHCnrn"
aAaaaaaAaaaaaaAAaAAAAAaAaAaaAAAAaaaAaaaAaaaaaaaAaAaaaAAAaaaAAaAaaAaaaAaAAaaAaAaaAaAAaAaAaaaaaaaaAaAaaaAAAAaAaaAaAaaAAAaAAAAAAaaaAaAAAAAaAaaaAaaAAAaaAaaaaaaaaaaAaAaAAaaAaaAaaAaAAAAaAAAaaaaAaAAAaaaaAaaaAaAAaaaaAAAAAaAAaaAAAAaaaaAa = 609
wvJgdaLXgGegxrGByZTWYTbaUQAUqWIduEHhcXNFIBTjzOonxoQYXDGIoVctxydHTimnkNVhqBGGskj226 = "ihtCNjANGHOVOoqtCfwCsOCycQtzCfCclToGVwKBRaTshTQCjkgjyJNxrfbAxOTVqpyKztGEUEDWcXt"
G224 = 427
ioiRXXqEjQoaKqbpgstDHDfWFQkJOoMlFJdQcragFwbRVPDlrLnnTHNVCmrdNIFHzPvIPvcjefplYWP222 = 410
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 262
I16385592181168504218 = "DLfElPEPhAzCNEToPuqehTImMJTIROdyTWhxeadrnWSpzMklFmAowUxUOHjflpjbrBUzCOMUmZTHshe"
llIlllIIIllIlIlIllIlllllllIllIIIIlIIIIIllllIIIIlIIIIllIlIllIlIIIIlllllIlllIIlIlllIIlIlIlIlllllllIIlIlIllIlIlIllIIIIIlIIllIIIlllIIIllIllllIlIIIIllIIlIlIlIlIlIlllIllIlIlIllIIIlIIIlIIlIIIlIIIIIIlllIIIlIllIllIIlIIIIlIlll = 246
aAAaAAAAAAAaaAaAAAaaaAAAaaaAAaAAAaaaaaaAAaaaAaAAAaaAaaAaAAAaaAaAaaaaAAAAAAaAaaAAaaaaaAAAaaaaaAAaaaaaaAAAAAAaaaAaAaaAAAaaaaAAaAaaaAaaAAAAaAaaaAaAaAAAaaAAAaAaaAAAaAAAaaaaaaAAaaaaAaAaaAaaAaAAAaAAAaAaAAAAaAaAaaAaaaaaaA = 434
IIllIIIIllllIIIIlIIIIllIlllIIllIlIlIlllllIlllIlllllIlIIIIlIlIIIIIlIIlIllIlllIIIIllIllllIllIlIllIllIIlllIIIIlIIIIllIIlIlIIIIIllIlllllIlIllIlIIlIllllIlIIIIlIIIlIlIlIllIlllIlllIIIIllIIIlIIIllIlllIIIIllllIIIlIIIIIllI = 302
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "ncTuVkLyDuKTzVejgByrnzVaKnrmutgoRiVjMxakKNgeqLdrJEVRtLESmIPLtKZioSqtPmkpAUmGXNy"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "PnGVcLrySzWmnxjlwUacgNKRTEmCUmwqhQUmNXlDHrAAeQLzquvaRbjuMwnjHUzlXgqyOEQbOebIkNF"
B16385592181161752206 = "gxPpUBqaHDkSHEnXLjIpRkDPSYpBssIjHGDEWCoHSXKyzidikurpIKfXZLfiuTdqrMcwmGYGpWAvQxV"
IIllIlIIIIIlllllIllIIlIIllllIllIIIIllIllIllIIllIlIlllIIlIIIIIIIIIIlIlIIIIIIIlllllIllIlIIIIIlllIIllIIIllllIlIIIIlllIIIlIIIlIllllIlIlIlIllllllllIIlIIlllllIllIIIllIlIIIlIIlIIIIlIIlllllIIlIlIllllIIIllIllIlIIl = 338
oEmVuJqDPbxDtNOvTozWpbJOYsUkWxeCviPolmuQRoKniCdrGKvNMgTdCNZtuMoxhBBzHoBIZsflmMw202 = 384
T16385592181156983200 = "WPgGQuYbzhsVncHgALtDuxjtCpFLelzPFMXVolHzfCufKKjwSkLYhRKAiIrDqvwrRFWOumDfwsXdJgl"
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = 279
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "KLeDxgqTefYZYAIxBAWtQnOSNyGIlTfvOUQXJdyLqcwGBgQXoOEXcQsnxDXpULsKftFtADpLJLpWSHl"
AAAAAAaAaAaaaAAAAaaaAAAaAAaaaAAAaAaAaAAAAaAAaaaAaAAaAaAaAaAaAaAaAaAaaAAAaAAaAaAAaAAAAAAAAAaaaaaAAAAAaAaAaAaaaAaaAAAaAaaAAAaaAaAaaAAaaAAAAAAAaAaAAaAaAaaaAaAaaaAAaAaaaaAAAAAaAaAaAaAaaAAaaAaAaAAAaa = 495
J16385592181146533192 = "TSukqTwDfkzevzWrEmmyrKLxDwzDFAxeYCXySGoblbHsaFEdYhyDsOKBbvjoOKDDFGMVoXaepLoHngx"
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 306
J16385592181142087188 = "wVzBvfFGcxgdUdmQkpmDEPKJoLtiLRxBqTftByqMaDFenqIelhPCAHBZwyBhfWOHtJdEdhbXorjJEcF"
j186 = 475
aaAaaAAaaaAAAAAAaaAaaAaAaaaAaAAAAaAAaAAAAAAAaAaAaaAAaAaaaaAaAAaAAaaaaaAaAaAaAaAAaaaaaaAaAAAaAaaaAAAaaAaAAaaAaaAAaaAaAAAaAAaaaaaAAaAaAAaAAAAAaaaaAAAAAAAaaaAaaaaaaAAAaaAaAAaaaaAaaAAaAAAa = 429
d16385592181139193182 = "bGnPetsdFhiFoHbrEYcijLsCJkvhUIVHUQyInjFSUjhyAYEQHRmWqVZaHHhptaRmnsqtoXRmxxpfvoV"
j16385592181137834180 = 944
llIlIIIlIlIIlIllIIlIIIIlllIIllIIlllllllIlIlIIlIIlIllllllIIlIIIIlIlIIlIlllIllllIIIlIIlIIlIIIlIllIIllllIllIIIllllllllIIIIIllIIIIIIllllllllIIlIllIlIIlIIIlIIllIlIIllIIlIIlllIlllIllII = "VeALbAmMRvyERyxeLdKNNnUoSfnDVImNsGuhXAEdWgFUMITpBHkdCxTWDoJfCohFenKuquyAftuQYKU"
R176 = "rmQdfUbQlqTkFKBgwODnoJhAiRchvvnsomfZCnPsmnGoOVQKIJEQuUDyMcLQnmwPQALFAYQXzVHTHLv"
R174 = "lhVfViqFtarCrnsgHDyelyFRIeJLzXLwMFNMrGBOJUhTrHKwwMteWoSSmJAedOXcMofSBFpODIpSYWC"
lllIIlIIlIlIlIIlIlIIIIIIlIIIIlIIIIIIIIlllIIIIlIllIIllIIlllIIIlIIlIlIIIllIIlIIIIIIlllIlllIllIllIlIlIllIIlIIlIllllIIIlIlIlllIIlIlIllIIIIIIIlllIlIllIIllIIlllIlIIIlllIIlIIIlIII = "GSxcRVpbAEEEpyGYaLTDWfEXeJzublSDcmctrHGWMkEnwsgNczWChkSooVwxABiehlpCqluhjpozahi"
Z170 = 650
oWAyHLZBqrfbVNCUYLVujxeZWjXaNwYfudGjXQkXQxNgApMeWqTZroLCpJQBvkymxtKfWBpCRWsXsWd168 = 382
llIlIIllIllIIIllIlllIIlIIlIlIllIlIIlIIllIlIllIlIIlIlIIlIlIlIIlIIlllIlIIIlIlIllIlllIIlIlllIIIIIlIlIIIIllllIlIllllIlIIIIllIllIlIllIlIIlllIlIIIllIIllIIIlIIIlllllIlIIlIlI = "zYiJcIytKzEfxLaxXtJNneTLeNVhhEyDCOsSmsVVVnctPsQxDvaQzSLdeGkOLqbJpOZgccixCqBniwJ"
c16385592181127079164 = "JHOxBydAEaRrTIzxvCoZlDPGkICHCjiMblBjncQNGOvqlFKGAfEUcbkHsuYhielQAtGOmPMFXjjotKN"
IlIIllllIIlIllIIIIllIlllIlIIlIlIIIllIIlllllIIIlIlIIIlllllIlIIIIlllIIIllIlIllIIIlIlIIIlIIlIIlIllIIIllIIIllIIIIIlIllIllIIIIIlIlllllIIllIlllIlIlIIIlllIIIIIlllIIlIlIl = 232
IlllIIllllIIlIIIIllIIllIIlIIIIlIIIIIllIIIIIllllIlIlIllIlllIllIIllllIIIlIllllllIllIlIIIIIIlIllIlIIIIIIIIlllIIIlIIlllIIlIlIlllIIIlllIIIIlIIllIlIlIIlIlIllIIllIIIll = 339
B158 = "EDUSGjplwNTsxnSyFLfUZcmwgKUqtKVEQibpfmtXwwYrwQZrSNJnrXXgTkiFQxCrkYUXKvtGGDfavEq"
aaaaAaaAAaAAaaAAAaaAAAaAAAAaAaaAaAaAAAAaAaaaaaAaAAAaaAAAaAAaAaaAAaAaaAAaAaAaaaAAaAAAaaAaAaAAAaAAAaaaAaAAaAaAaAAaAaaaAAaAaaAAaAaaAaaAaAaAaAAAAaaaAAAaaaAaAaaA = 195
l154 = "QhIslpfNFKyAcEcFstTQyHMMHKzykKdqrWicrMWFmwAMSrKRzDeVrhnEgYgIwnXdNqEJvoaTsJTSHjY"
aAaaAAAAAAAaaAAaAAaaAaAaaAAAaAaAAaaAAAAAAaAaAAaaAAAaAAAAAAAaaAAaAAaaaAaAAAaAAaaaAAAaaAaaaAaaaAaaAAaaaaAAAaAAAAaAAaAAaaaAAaAAaaAAaAAaaaAAAAaAaAaaaAAAAaaA = 269
A150 = "WcxWgnDKxRSHXaulSHmfWipZtnAvVzKfHsYBNVgBlmWTrEuSqVxhgLVHQIlKceWUMwGIOwrFSalTkfo"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = "TVgcctSyEQQaugxxSBMRFLncArOrNoZQRlpfLPzgxgXCWtzTxgatDglPYJGJuHWSGaFJvGaKVzjcREl"
I16385592181116595146 = "McWtwZMgTgsRYcLWopfcXEMdTFQYFAyiKVaMTuPUAqKXOGjrywxlKEGULixwmwAyxqCucJdoLRuPZuD"
aaaaaaAaAaaaAAAaaAaAAAAaaaAAAaAaAAAAaAAaAaAAaAaAAaAAaAAAaAAaaaAAaAAaaaaaAAAAaaaAaAAAaAaaAaaaaaaaAaAaAAaaAAAAAAAaaAaAAaAaAAaaaAAaaAAaAAaaaAAaaaaa = 404
u1638559218111455142 = "UTYJtjbLaQQSixYMtHAsmqNAyUNkqLKkpsdZEURkGnHcQlWQFPENLdTSZmtdduNMeKqacPuHjPDMEiu"
aaAaAaAaAaAaAaaAAAAAAaaAAaAaAAaAaaAAaaaAAAAAaaAaAaaAaAaaAaAAaaAAAaaaaaAaaaAAAaaaaAAaaAaAaAaAaAAaAaAAAaaaAaAaaaaAaAAAaAaAaaAaaaAAAaAAaAaaaAaA = 150
AAaAaaAAaAAAAAaaAAAAAaAAaAaaaAAaaaaaAaAAAaaAAAaAAaaaaaAAAaAAaAaaAAAAaAAAaaaaaaaAAaaAAaaAaaAaaAAAaaaaaAaaaAAAAaaAaaAaaaaaaaaAaAaAAaaAAAaAAa = 492
llIIIllIllIlIlIIllIIIlIIlIIIIIllIlIlIlIlllllIIllIIIIIIllIlIllIlllIlIIIllIlIIIIlIIIlIIIlIIIIIlllllIllIlIllIIIIllIIIlllllIIIlllllIIllIIIll = "bDvlTKpSyTXFsmEctXNjKYeohWClryGxipWxOCeaqzlRWshgHfcrnJCKsjaZUhCDLFyIlECnWujvpnr"
K16385592181110263134 = "dadQKKsXDiberMSuyqMjPTsTeimyOrmEdEzivDCxhZisrBTZfOIxnGsLlyPGgMqroijHlZfqcGEZYZL"
V1638559218110873132 = 258
lIlIllIIIllllIllIlIIlIlIlIlIIIllIlllIIllIlIIllllIIllllIIIllIIIlIlllIIlIIIIIllIlIIllllllIIIIlllIlllIIlIlIlIIIlIIIIIIlIlIIllIllIlllI = "AYDgvykVoaRLnsMRNanVGkGtRICBcYeJXRsHgtItPZJSjNifhLXSQMphNbQQDRLJILiKOTHchVCnnnw"
AaaaaAAAAaAaAAAaAAaAAAaAAaAaaAAaaaaaAaAAAaAaaaaAAaaaAaaaaAaaAAaAAAAaAAAAAAaaAAaAaAAAAaAaaaaaaaAaAaaAAaaAAAaaaaaAaaAAAaAaaAAaAaaa = "nNzpeLObEZCoLKOSoApNOEvPAhBebPcsNgtnuIiCGKgawadaWfISrBDCXioFwSmzjgvbrsPpzXvuQMg"
dPEumeQACwWGrCDVkEdXZyqVaxcrZrlnYluWFjDrAxcIFhXVIVoTcQhAFiuITcijvStFTIVSWbJlrLN126 = "gNpHXyTfSPSDOJunOMbPPjiBhcrQdrRpLeKhqqsqCQqsRWcbTbVUidUZWDnOlxAeiDEmrZUymBxMHAR"
jWkBSagHOREDjcnROiYoAzCDICVRuEXlyloknHHlVLtmdkGzCdVOCOkuGqpavCcxMotFnyczWIukENM124 = 56
lIBIaOdzhgnLQKqRfSADpXHpaKXAZHGQtbsPnCDnqNdKpMsgcRLInjwtIYWQqPVaCFKhDAaIsUJKBnk122 = 835
D120 = 642
llllllllIllIllIIIllIIlIlIIIIlIlllIlIIlIIlllIIIIIIIllllIIIlllIllIIIllIlIlIllIIIIllIIIllIllIIlllIIIIIIIlIllllIIlIIIIlIIl = 349
XbtujzofChmYdGHPScRsRGmqZdrbDPWNkyZgYhUApSyfsgIyoKXeZFNvmfWvKYywiqknnSdIePlQNZT116 = "bYzEfIpFtjdGeySJuoGYMOZVdsxZbpAbiiQpcHiopYXLsLjRpHJDcCYMJFSCeGIpwoRueiRKxnDWQBU"
AaaAaaAAAAAaAaaaAaaAAaaAaaaAaaAaAAaAaAAaAAaAAAAAaaAaAaAAaaAaAaaAaaaaaAaAaaaaaaAaaaAaAaAAAaaaaAaaAaAAAaaaaaAAaAaAAA = 355
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "FiNljwaPGFARbinjeYlxZCQKBLkfEpcRmnmdRmTSmuoWBVHgFPeudGtKhsFkhIjrAYgAHlKucLHJoWB"
E110 = "HOhjYCABUXFDYOzPTswLtxSRhUXHIYFtrDHJryWDitRswyDrgEHfxVjpcsTOGBsSAFDVAUMQZCZaYGP"
aAAAAaAaaaaaAAAaAAAaaAAaaAaAaaaAAaaAAaaAaAAAAaaAAAAAAAAaAAAAAAaAaAaaaAaaaaAAaAaaaaAaAaAAaAAAaAaaAAaaaaaAAAaA = 351
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "rRsEHSjuKthuYvxOFgziHmdxUoAYBDhtFBnhhDtpygvEVVmofABsNXlBFnNfAziRnhIyncjhVBGMNra"
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "UYVHDYUZMSBhkMPJceZWlMDJgYhXnsJJISegYWFmjOuoXXtqvvWZcRQUmiuaXQdQVVkUMiEZYPyMJeX"
AAaaAAaAaAaaaaAAAAAaaaaaaaaaaAaAAAaAAAaAAAAaaAaaAaaAaaaaAAaAaaAaaAaaAAAaAAAaAaaaaaAAAAaAAAaAAaAAAAaaAa = 282
x100 = "cegdOrkLABBiepaZaRoAjHlzMdQxZpmiwnLEyHyAYSIEHwUyzzoIeBrCBNmqBxKoNEPNWDljLSxbJsH"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "KMmNCgNZeTjwFJZirSUUxQiFHvyndopzzTAuhlVMNvUTeaxOSjRzgutpdlUqTprXKibfQJNRurTIIDo"
lllIIIllIlIIlIIIlIIllIIIlllllIIlIlIIllIlIIllIIlIlIIllllIlIIllIlIlIllllllIlllIIIlIIlllIllIllIIIII = "zwvBOBjAHdTdlFEkXKTKLuIiHiEtQJNQagnBzmSwPuKulXIFBgNCrDdyhdfvTsnmYcrGVrmjoIELnFk"
IIlIlIIllIIIlIIlllIllllIllIIlIllIllIIllllllIllIIIlIIlllIlIlIIIlllIIIIIIlIlllIIllIlIllIIIllIIIl = 385
r92 = 254
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 388
IIllIllIlIIllllIIlllIlIllIlIIlIlIllllIIIlIIIIIIIlIlIllIIIlIlIllIllIlIIlIIIlllIIlIIlIlIII = 613
D1638559218108663886 = 58
MVLHYOiyImQOGoVZQiNHpNKcqmLAyKSsqxmhTBBahwJHxgMCEVMPNnfsMOMSrfIxiidoxqTRlqzkMyz84 = 675
o1638559218108528982 = 342
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "vAkdmmyDOsrVqJVARMHwHFKGKbvfTXcEsmPbHUEugETKbptzuosPHCPJEaDYVjDfTRGKcmyRZInPaqJ"
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "VDfmHPzwbiRuWvepxmcQnWtKPOCEYDySnWmApVTkvpcFqyKkDWIbiNcxRZiDMCHIlprHuvQtHtZXeeD"
aaaaAAAAAAaaaaaAaaAAaaAAaAaAaAaAAaaAaaaaaaAAaAaaAaaAAAaAAaAAAaAaAAaaAAaaAaAA = 333
AaaAAaAaaaaAAAaaAAAaaAaAAAAAAAAAaaaaAAAAaaAaaAaaaaaAaAaAaaAAaAAAAaaAAAAaAA = 348
V72 = "DscwaafejMTkpFqAxtVHKSCEmpndXjTfGPcKkOSHlXsoXIuYrZptLXrTNBXeqSGojyXniYJPvPoEffx"
htatYtsOeDTWeiDKDiEjnAGOcAukCycGUQmylBskYysxMUJBfOYvYNODcxYNmYBeYOBFAhLYjfrsOwT70 = "lASWIqmGOMFFKOsOdDSXNwvxbjGmpixyzCXWunnDkoKCEodAujENOufcATCNBdHrepUmAyvzRxXviUp"
w163855921810788868 = 518
h66 = "RNMvebYqAEDHWTQWrPopRmLUKhAbOlmAIeolujrXsDecKHHJWRqBhEnVcFVvPLrYXUYJfDasZXUkpTB"
llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll = 365
IlIIlIllllllIIlIIllIIlIlIIIIlIllIIIIIlIIIlIlIIlIIIIlIIllIIlIlI = "sWUXjvKpiqnIMCooNTQQOACoCUOyVSppvmZgDimIhZBQNwVqGSImIxAHHTaNqfirInjgHeOtDIKynxv"
A60 = "ZGFkRtpCZjHufQraNFYAMgKFFfjBYyltUbdEQNBQoLbQbDToGTEPYMqltwiiPGrkuQKkZnVSzCYDgQG"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "CEmGnVvAynBSeKgbHanLPNzApuxhsxwAooDIRhXdMGbLExGlUpDImjTTbZMQOeocbHPHwkQioKbasNl"
aAaaaAAaAaAAAAaAAAaAAaAaaaaaAAaaaAAAAAAaaaaaAaaAaAaAAAAA = "YPNZGwDxapGHbfnQLIuToREwPtPmChvAJuggbgwFiJIAJoldoswXtZJtCbJzrRdHuhvgeisranEiMWU"
dddddddddddddddddddddddddddddddddddddddddddddddddddddd = 659
T52 = "lLIzDYzWWUPQSZWbNtQqigbuBmdMPDXvdLhFYGgtxrSCECRsezNPONqTTrvUXAotNZWMwRNkZfzxWLT"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 316
j48 = 267
l46 = 397
K44 = "QZWliMNTBxKTedfWJrUchfitMjIPjFaRvkjdjARSFPXXzuLUrEzCrsalCCgwfSIGdjwFsXfPYoAobLI"
IllllIIIllIIIIIlIlIIllllIIIIIIIlIlIIlIIIII = "McdzPopFsoiJNUPOijiTIcjLsQMmnmUOGzMeNYOMVCeqAZvBasTAQhweHTGaFScWgwlXiYfIUVKlLRt"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 466
AAAAAAAAaaAAAAAAAaaAaaaaaaaaaAaAAaAAaa = "HhJYywQbHBIdMfrxPucFEAhoBvYXoVawCxYfkrZDElCiOyKULXBYcAqUpIultblkemiXqLbRwhvAjDi"
AaAAaAAaAaAAAaaaAaAAAaaaaaaaAaAaAaaa = "vWQXITbunRZuvopgLfJZQGJuKbNCGvYIHodHgQuMuKaCJgkyjknNZqjmhCqtFpcrRXazbAZPNaPbnxE"
lIlIlllIllIlIIllIIIIIIIllllIIIlIll = "IDZSnVwzvKNQudZWfqWIgmsLYgPBSShdtEkmBdXfvSSglkELbylXnlSoWBXSwJKFdQfuMbApUXxgXPP"
lIIIlIlIIlllIIllllllIIllllIllIII = "GMeBqFsIXlQaoxSQdqANtpngUtdEUcCbgVxwFYDtAvDqmzTOgGHVePKsSOwDRRyYbhVsYLkmRSdayHi"
AAaAAaAaaAAAaaAaaAaAAAaaaAAaAA = 477
lllIllIIlIllIIIllIIIIIIIIlll = 386
AaaAaaaAAaAAAAaaAaaaaAaaaA = 917
Q163855921810631524 = "MqyYUBPKkfXdARwmWcYCUNKCOPYlERNsMrRvgKBpewIYVdiIZSxKVbzNjgxCYuuJHoaRvWUdMWSrVml"
IIIlIlIllIIIlIlIlIlIIl = 298
mgtUuMXEwmdBEQSSJFgKoDnKXSpEvddDbGqIPVCAGemRxCWTvxMORrbkRFlSQThAHbqLPDrHFnVUhtu20 = "mQBTYpoNxXAUBnZqTZNGsepVYkMsgmtdyGwbNxiWXviVbbisnHGORjkWIyjfbJnzhVjmvbzFxmoAVLE"
ZLahNfRMdivZfwEWOMLfwhPxsSagUqYAPbBXDoHeZVdwVFvVvFIJiWJXfMxYPfJYxJThUKwtDQAgZOf18 = 357
C1638559218105987516 = "ouhrtZdqogAYktbPiOvnKRaEstsyKYxHKrksSopruAOCmxEJNWcGMaGvCxiYTgVtqZonEOOIwqghaeo"
YbiwzybaGRPfPfnsGxIWqlLRXRKbVecZtjlZHNcIcXtTojZjXKvgMksVSJtVztsnmLtIuRPpyQBEzlO14 = "hVDdnacufmYLAOdMkHqhKCWGpcoWkmjtRbISqgFNfKpDHKutnRmhFCYEwynprhTXjdpevkkuuHzgKrW"
GqtXyhGtzmJszHkXagKBSOCBdeghumPqgDVIEOiyCkTjvkoGxKtqWeXYuoFSpObSerDwpRwpCHKTWwg12 = 353
AAaAAAaaAa = "AYKhYjpGUyedbhfAVMnWqSETVECLiFdCDbtPwCbyjvFPRqoWtfBoAcppEwPOeUkcinwUHIPNKbMBDzw"
q8 = 523
R16385592181056536 = 292
e163855921810559944 = "KaATwNwSoSsvKDfIdgPrbnCECIWLqlAMapoMCWmGyFvNLffhAybOYKwNSuuJEQOovVIrUGlAXZOpWoX"
o163855921810550522 = "pmDNkKYilWTSWnAiqxYYaWeroeECWCkNrXyAqccwGfQiEQJihISuUlhMEMWzpzasLzQSxfJYVyWfYKi"

import os as i,re as s1
from pathlib import Path
from typing import List as OO
data_packages={'pymongo':'MongoDB and connects with PyMongo. MongoDB is a NoSQL, document database.','sqlite3':'SQLite database and connects with sqlite3.','redis':'Redis, a NoSQL, key:value database.','psycopg2':'PostgresSQL and connects with psycopg2. PostgresSQL is a popular, open-source SQL database.'}
cloud_packages={'boto3':'Amazon Web Services (AWS) and connects with boto3.'}
def _select_important_packages(packages):N163855921810317281=packages;H2=[data_packages[H2]for H2 in N163855921810317281 if H2 in data_packages];M163855921810347223=[cloud_packages[H2]for H2 in N163855921810317281 if H2 in cloud_packages];return H2,M163855921810347223
def read_packages(project_dir):
	D='environment.yaml';M163855921810347223='environment.yml';H2='requirements.txt';N163855921810317281=project_dir
	if H2 in i.listdir(N163855921810317281):return read_requirements_packages(N163855921810317281/H2)
	elif M163855921810347223 in i.listdir(N163855921810317281):return read_environment_packages(N163855921810317281/M163855921810347223)
	elif D in i.listdir(N163855921810317281):return read_environment_packages(N163855921810317281/D)
	else:return[],[]
def read_requirements_packages(filepath):
	with open(filepath,'r')as N163855921810317281:H2=N163855921810317281.readlines()
	M163855921810347223=[N163855921810317281.split('=')[0].split('>')[0].strip()for N163855921810317281 in H2];return _select_important_packages(M163855921810347223)
def read_environment_packages(filepath):
	with open(filepath,'r')as N163855921810317281:H2=N163855921810317281.readlines()
	M163855921810347223=[N163855921810317281.split('=')[0].split('>')[0].replace('-','').strip()for N163855921810317281 in H2 if not N163855921810317281.endswith(':')];return _select_important_packages(M163855921810347223)
class PyVersionDetector:
	def __init__(N163855921810317281):N163855921810317281.PY37=37;N163855921810317281.PY38=38;N163855921810317281.PY39=39;N163855921810317281.PY310=310;N163855921810317281._version=None;N163855921810317281.possible_versions=N163855921810317281.PY38,N163855921810317281.PY39,N163855921810317281.PY310;N163855921810317281._walrus=[];N163855921810317281._walrus_pattern=s1.compile('if\\s\\(?\\w*\\s?:=\\s?.+\\)?');N163855921810317281._dict_union=[];N163855921810317281._dict_union_pattern=s1.compile(f"^\\s*(?:\\w+(?:\\s?:\\s?\\w+(?:\\[\\w+:\\w+\\])?)?\\s?=\\s?)?[\\w_]+\\s?\\|\\s?[\\w_]+");N163855921810317281._pipe_optional=[];N163855921810317281._pipe_pattern=s1.compile(f":\\s?\\w+(?:\\[\\w+:?\\w+\\])?\\s?\\|\\s?\\w+(?:\\[\\w+:?\\w+\\])?\\s?[,\\)=]");N163855921810317281._type_hint=[];N163855921810317281._match_operator=[]
	@property
	def version(self):H2=self;N163855921810317281=str(H2._version)if H2._version else str(H2.PY37);N163855921810317281=N163855921810317281[0]+'.'+N163855921810317281[1:];return N163855921810317281
	def review(N163855921810317281,filename,code_contents):
		D=code_contents;M163855921810347223=filename;wEXocFWBOIORZJRDqEqHkIYreQBRLxqcMwiaBHJmVGgeLVgGxbzvYCQXTTSmruwHGOLFmSqPGnyHgWn13=N163855921810317281.PY37 if not N163855921810317281._version else N163855921810317281._version
		for H2 in N163855921810317281.possible_versions:
			if H2<=wEXocFWBOIORZJRDqEqHkIYreQBRLxqcMwiaBHJmVGgeLVgGxbzvYCQXTTSmruwHGOLFmSqPGnyHgWn13:continue
			if H2==N163855921810317281.PY38:N163855921810317281._match_38(M163855921810347223,D)
			elif H2==N163855921810317281.PY39:N163855921810317281._match_39(M163855921810347223,D)
			elif H2==N163855921810317281.PY310:N163855921810317281._match_310(M163855921810347223,D)
	def _match_38(N163855921810317281,filename,code_contents):
		for H2 in code_contents:
			if(M163855921810347223:=N163855921810317281._walrus_pattern.search(H2)):N163855921810317281._walrus.append(filename);N163855921810317281._version=N163855921810317281.PY38
	def _match_39(N163855921810317281,filename,code_contents):
		for H2 in code_contents:
			if(M163855921810347223:=N163855921810317281._dict_union_pattern.search(H2)):N163855921810317281._dict_union.append(filename);N163855921810317281._version=N163855921810317281.PY39
	def _match_310(N163855921810317281,filename,code_contents):
		for H2 in code_contents:
			if(M163855921810347223:=N163855921810317281._pipe_pattern.search(H2)):N163855921810317281._pipe_optional.append(filename);N163855921810317281._version=N163855921810317281.PY310
	def __str__(N163855921810317281):
		if not N163855921810317281._version:return'\n                    No exact compatable Python version has been detected.\n                    Versions below 3.8 are compatable.\n                    '
		return f"\n                The codebase is compatible with Python {N163855921810317281.version} and below.\n                "
B16385592181054551 = 366
lll = "gnOupzUjQBjprHXPGsUvkzZfXaqMtlaFhHRdGHKPWrsLANIoHEVyGLKDyuTUuNPAtmscHfgksGBSciT"
llIlI = "pRUgpHMYfGljiUKZYyMdQHhwcgDAPcdfrEMcWuCZipCgHxpdUvVimzxAbhDsAMSHJaCJKiHvOQrTIPO"
xxxxxxx = 399
IIlIllllI = 257
rRhTyHAUwLKlpgjMpVGVrQORsUZzwjQiTxQyecelpNYVXvKCRThokKZbFVaFBhvOIWLnaNZvffWUeNN11 = 153
J13 = "acqvQWCFjMHrlvOxopiWVlVmwhyxvRKdqVCKnIZPgdCCvFAPGYSXUuGwWmKPMoGHsVtrxyvpOBvAZpV"
IIllllllllIIIII = 118
QQQQQQQQQQQQQQQQQ = "qDweEuzlWdGxGYjmSfgSdFlMPNCgbnFBjtPPIRGpPfvVTzZiYrXzdUeBwDKXjKNOKSRXYNvadeewFKI"
UFxjjkzcUgBeHTGZzDTInWJTOjqNDwHAgbvtCVLKnhPPkasGGvLZBAgLgjRbgbDYYjojiALedlPNeXV19 = "jlqWZDMQHMfDduRVzThJYyqOByuUSyeQcTIFiMbIoIXPFICMiDzmgRtZfaSwhToMuBrSnlwyoMtcikB"
AaaAaaAAAAAAAAAAAaaaa = 511
YYYYYYYYYYYYYYYYYYYYYYY = 295
T25 = 99
buwrTCBAbztdPdHeocxynNTjxTAbWzgCHCewnxixklmpLlXZpwcqEiXuXBfsarbiCxNrGSpIDVCbNzL27 = "CSsQQlLEGWrRefZyEmtACjNunaFBYziDpkfdssYepIpWdWDoTYITnCkwxEkYAVboACsjytLRmgQVSGe"
aaaaaAaAAaAaAaAAaaAaaaaAAaAAA = "RWWVzdDVweUtDxFSfJRDmamjrQJANpxEJdVzFRbCPeHvZLhPkakwFOVHJRWTMUCyoWKcZceLsOAbazB"
TsEiQfJJNZuIjQixzVtDflRmxawuJyxnCTxQygdShvBjwWGlhCtuRaFqhbqAcUzXyOJVmqIjfeBtbHM31 = "PyRBqGZjzpEVNoTersIteWFiLRCqQrCLKWmZKoQhUpYRlOajiRTvuCjPLFNnrsyjiMLqDBHKPTNxaUW"
AAAaAAAAaaAAaAaAAAaAaAaAaAAAaAaAa = "pUoQycOaLvpLtutJOLBSDkLFsCyDjgBkKzctbxmPGdnWgxHBqStxMMktegDEdvhNzMTFyqjarwknMoN"
c1638559218106861435 = "fWjuDjLtjKfvAUMiskPXYwDqGZjMUEOxTmQtQXDkCfaHhYtqtJTbGXKiYRQOOeBYYAJcazBZqbeOUtI"
aaAaAAAaAaAaaAaAaAAAaaAAAAaAAaAaAAAAA = "NyjWgnAmFrlrVnhPnbZIeJdzDsbeinRMjeakQmvaAFPqPVhFKJNTPlrvjckyqPCDqYpINTqNKChlLgR"
AAaaaAaAaAaaaAaAaaaaaaaAaaAAAaaAaaaAaaA = "LEGYksPHqjpEMzBMFfLmTgVXolcTfoObfApDcnYRZmULtfLkjytQcmmXcztRVnuAYCDdzYAUZMEbuHN"
llllllIlIIlIIIIIIlIIIIlIIlIlIIllIIIIIlllI = 245
n43 = 602
c45 = "akXkBjGuTGfAVfDZbUmYmoENePTampXakHTQIItRfgGWUFykICyXIMMHaxXbMDKrKKMXshqyroADBES"
f1638559218107310847 = 252
AAAaaAaAaAAaaAAAaAaAaAaaAaaaaAAAAaAAaAaAaaaAaAaAa = 332
p51 = 591
AaAaAaAaAAaaAAAAAAaAAaAaaaaaAAaaAAAAAAaaaaAaAAAAAaaaa = 543
c55 = 446
V1638559218107515857 = 647
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 675
IllIllIIIlIlIlIIIIIlllIlIIlIIlIIIIIlllIllllIIlIlIIIIIllIlllIl = 561
IllIllIIlIIIIIlIIlIIllIlIIlIllIlIlIIllIIIlllIllllIIIIlllIIllIlI = 187
U65 = 191
IlIlIlllIllIIIllIIIIIIIllIIIIllIIIlIIIllllllIllllIlIIllIllIllIIIlII = "eCIUJWuWUHLyVNQuSVAnZoLxnfqAogdLQUYUetaKfCHcYAKWqppyqfqAaeeTfYPgOjmAwUsDmYJMSUH"
IlIIIIIIIlllIIIIIlllIIIIIIlIlIlIlIIIIIIllllIllIIIIlIIlIIIlllIIllllIII = 712
lIIlllllIIIlIlIllIIIlIlllIllllllIIIIIIIIIIIlIIlIIIIIIIIlIIlllllIlIIlIll = "eMTedvXfDRzOtoiCnEYHbtQNgmfolRbfYPsqfkGZFYmvwGIxjaFZXocZstCUbEGTIocZyFLdLdlIwTJ"
I163855921810816873 = 58
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ = 501
IIlIIlIIllIlIllIllIllIlllIIllIlllIllllIIIllIIlIIIIIIIIIlllIIIllIIlIlIIlllIIll = "cIRfGIdCQhZMTlVUNivhmVJWfUUmrvQbYreYeSERVUXFWpDpyeGDLqrrYcVvYNNXiDYviabbTXkByAG"
ZFgRKbCkADQJDxamkwuQJSyjesxwWQscMZZkidQcLFZiGWZIQrNKnJbgJYYkirxWpHIPjTvUEIxfzAQ79 = 241
llIllIIIIlIllIlIIIIlIIIIIIlIIIIllIIllllIIIIlIIIIlIllIlllIIIIIllIIlIlIlIlllIlIIllI = 915
W83 = 281
aAaAaAaAaAAaAAAAAaaaaAaAaAAAaAaAAaAaAaAaAAaaAaaAaaaAaaaaAaAaaaAaaAAAAAaaAAaAAAaaAaAaa = "IecTqfaTGsiFoDNTKxvxHAHjoilJnRRSrCQXFweMPTAyAQztscYTITaVyODsYDVocJGeEtBxVYcKOQd"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = "UXGmPqJtVrpRpqiQIYmFxSthEzbHFvHrQEtjnatBaZRiniTbumzTMuVSEoFZfXbfNBoMtAeneqywXEX"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 119
aAaaAAAaaaaAaaaAaAaAAaaAAAaAAaaAaaaAAAAaAAaaAAaAaAAaaAaAaAAaAaAAaaAAaAaaaAAAaAAAaaaaaAaAaaA = "LCqLMCEZtWgPXvysRUoZEtOgUgHBMZMUGlIpjYzoHORuZqjYPfBuKoftbeHyWcdergfXuLMNHtwtitK"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 492
OpuXsnmislXTwkFOqYiRfoGtyMLBPzShTzKAcRkjjrhHdzuWWDcxemSXZbQaioAlBJBNdsutZiDeKJf95 = 183
d97 = 119
O1638559218109146899 = 385
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 584
n16385592181092951103 = "lbjKfxdLHMiikfsxbSSgRhxVMGdKGxsYTNFmTNppCkTklrEsTBYOThQWYcuMECTkrPcFRlTocZPTjfc"
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "CAenniKMQdQWWlhkzYHVgMZtUNWTlwtDnRTZHzNinVfMtRSUdlKvwOZMTqNbvPVPYBscWLhNubvoUKp"
llIllIllllllIIlIIlIlIIlIIIIIllIIlIllllIllIlIlIIIllIllIllIlIlIllIlllIlIllIllIIllllIlIIllIIllllllIlIIIIIllIII = 416
o16385592181096313109 = "geTYFbzMMSCYGLwhMtBBOdLdNnwNpmkYLfmYqDHNmREgeCNzsOexQyoUxaqatCJCcVgYTjloJeAhzVa"
r111 = 277
h16385592181097734113 = "MNWWDQfZqPTxUjGPzLiOuBbOFmZxNrAaOFLtYmybDoHIiJRsOvoyoVsPOhUYMgRebFnpcgnGfJbuHjP"
z115 = 245
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = "AfkOgGoskkzGWibsZBYHjuyOZpAfQjIEjXkKsafUrICaLwdhehPftdFGwhlViKyaLWGUOGTsuVCXsVd"
X119 = "BJqVLhyjbKYzSzJPuqmJhncftlDuQxKnrGOGzioajROZBasAPQkYtpnLnrMLGjdaCVjEGlFTXcnEMXr"
ovyuFuBwDnvTcQGqRWYgewBEkAcFYEDwhcuLFiAWLjOohftOTtrKFfXxyTGnQUEXfhQnlyfHdDIyHWG121 = 283
llIIIIlIllIIIlllIIlllllIIIlIIIIlIlIIlIllIlIIIlllllIIIllIIlIlIlIlIllllIIIlIIIIlIlIlIlIllllIlIlIlIIIIlllIIlllIIIlIIlIIIlIllIl = "qVZjuXeELXYeJgdqlDpdpoynEggiGnPTxwnuvuzzjHdPpqGlpeOsqXhXxfbSpxkkzMKPlMQANtGSszZ"
c16385592181102984125 = 77
BTvRSHGLiFrGiOwRGXNtrRPuHjbXYgeMFZmyruHtLXGwgRCTjQoZcqlToKqSIWIblsrFJQOUmeWuJZr127 = "znErFNxVMGxmRcOkEPRgurgNSoGbWTSHkhbBgEjsSXJijzUURiMLUeGFFbAtCKHZWUzgdtegyUqXNOk"
AAaaaaAaaaaaaaAaAAAAAaAaAAaAAAaaAAAaaaaAAAaAAAaAAAaAaAaAAaAAAAAaaaAAaAAaaAAAAaaAaaAAAaAAaAAAAAAAAaAAAAaaAaAAAaAaaaAaaaAAaaaAAaAAA = "znlaFtsGmiRBeNsXYoPimHsANlHNqsZotNqHfOfLEVujRMsmpMwbUAfaEVhpSVfKicfYCuPgKcpJcvF"
wkdJKWPqyfSetPeUnsdDmPSHRilPnVBeswolzblFwvdFiAtWvfbiDMoacJDsJYhGGdRUBbdOWrSQtVy131 = 397
IIIIIlIIIIlIllllIIllllIIIlIllIIIIIIIllIllIlIIllllllIIIlIllIIIIIIllllIIllIlIlIIIlIlIIIIIIlIlllIlIIlllIlIlIIIIllIllIllllIlllIIIllIIlllI = "XuHFsIsmUrCyiIQmMKWcImCHDERROwxqqWxkYSBsCMjDJdFLYhjBEnCIniSeJaubcQuKqJnpiWaVCwU"
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 839
R137 = "ksZKFOKRmrsXJoMLXCiELqjRicJWqoHypSGJcPxdLpqKjHGlxQyUiSuouAonshiDyvSMXUdFmqJZafp"
svCfUmdmaqsCiNJrNyvSZlddybLZsKOrHlhvglepgPOwjiKKWHNdcAvHCnLbomQnmpwumIVwWBQEXFR139 = "mmFpglvtZIaQVUnnoejxoXerVOluNOzXnlKUEXOgnvovPguNaKrrYnfePPQYgkZaEeXOuVoQjzgLiVb"
u141 = 179
RDtIjqzJfrSBoTfZgiXUlxhcrTDXfGxPiBegPqlpMMBbxGoxQDbeXlEScORstOJtOJPWjIIfWIpAclV143 = "xZqvyoatiRRAZPPYMeEfESUpMwAnjEXuDtgAzzgqyBZtXcUkaZJavtMOKDQAURrMLeipeCtJQPQDQHX"
B16385592181116133145 = 283
J147 = "xgkiKYgTjmLslfZXCElKbdbBsdtWpNPMuwdpsyTyauArypwzWmUsQeEpLaCEymRugFRNATBGKhsejqY"
Q149 = 234
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 208
IIIllllIIIlIlIlllllIIIlllIllIIllIllIlIlIlIIllllIIlIlIlIlIIIIllIlIllIIlllllllIIllIlIlIIllIlllIIIlIIIIlIIIIlIIIlIIlIlllIIIlIlIlIlIIlllIlllIlllllIIlIIIIIlII = 297
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = "QupbOImykQSaeDeuPJdpArtLgffDNMFXJfBmdhEVdrlmYsakMAOOTPLeDvHFJmLonvvINwuWKkgUbaA"
mdZWFXuOelOzwQGSPtUTviiTLQtySUQcyHNByCZzclmWVGiZKvfiwOAWEfjabLWPxZgyzWrQbsixjvc157 = 265
AaaaAaaAaAaaAaaAaaaaAaaAAaaaaAaAAAaaAaAAAaaaaAAaAaaaAaaaAAaaAaaaAaaAaaAAAAAAaaAaaAaAAAAaAAAAaaAaaaaaAaAaaaaaAAaAAaaaaAaaaAAAaaaaaAAaaaaaAAAaaAAAAAaaAaAAaaaAAaa = "cFYloxVJHVsfOcxfcMonfCVeARmKrTZNilFTEiuUjOInVCPqQOPiAcydXUKZaFMQhaXTPisdbXADxTz"
tCCQxkBVKICQyEyXnCVRXDuOqqEZltWvyDUGGoBfxdeBhtoFiTIObSSexgqvlXtIEyHKLtwWnUyDFAr161 = "AXJXSnvDzsANzkiJexbnCvuwgdefrhqaJPdHDsSrOmxgoTyqjwfvnDCdqwrNmqNYgRqwThyQAohtRcJ"
t16385592181126626163 = "PDUHQTnXuSxHuvZWfKtIuEbWQlYNjdYgRZerGuxgffXjRciRCIGtXnxLKRnKQcffAwCUfpgpYmQxSgn"
c165 = "ryeOpbYbPCOSXGwpvGCQFYhgtKyNDWtyFGSIbzOpdIhBacYMaoavPKEqkSFihcSVzlyIHBsMxDQyJmd"
c167 = "PjBOChJUPDRCGLJlSsMopywinyruladXAgKdvaLsGjwloytEynnzRUkmrahJogzHOrVeysgCjOOvzhH"
AAaaAAAAAAAAaAaaaAaaaAAaAAAAAAAaAaAaaAaAaAaaAaaaAaaaaaAaAaAAAaAAAAaaaaAaaAAAaAaAaAaaAAAAAAAAAaAaaaaAAaaAAaAaAAAaAaaAaAaAAaaAAAaaaaAAaAAaAAAaAAAaaaaaaAaAaAAaaaAAAaaaAAaAa = 440
AaaAAaaAAaaAaAAaaaaaaAAaaAAAaaaAaaAAAaaAaaAAAAAAAAAaAaaaaaaAAAAaAAAaaaaaaaaaAaAaAAaAaAaAaaAAAaAaAAaAAaaaaAAaaAAaAAaaaAaaaAaaAAAaAaAAaAAaAaAAaAaaAaAAaAaAaAaaaAaAaAAaaAAAAaa = 478
lllIlIlllIIllIlIIIllIIIlllIllIlIIllIIIllllIllllllllIIIlIIllIllIIIIlIIIllIIIlllIllIIlIlIlIllllIIlllllIIlIlIIlIlllllIIIIIlIlIllIIIlllIIIllIIlIlIlIIIIIllllllIIIIllIIIlIllIlIlIl = "dfHcChhOyPPkpjVouDUDgSjdKjtKXyxJYPGHdSfIoGeFnuAZvzzfLwvDgSKHHGUVdeLPABLSLLsuouz"
aAAaaaaaAAAaAaaaaaaAaAaAaAaaAaaaAaaaAaAaAaAAAaAAaAAaaaAaAAaAaaAaAAaAaAaAAAAAAaaAaaAAaaAAAAaaaAaaaAAaAaAaaaaaAaaAaaaAAaaaAAAaaaaAaAAaaaaAAaAaAAAAaAaAaaAaAaaaaaAAaAaAAAAaAaaaaaA = 171
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "VYeoGPCUtFCTkjPEImitpQQbxariOceVsSNafrnvFklZTslHTATOcKqfWsLxtvxdPOtTUpBJkUaFDzu"
FfKLFRRkiZolDOAKlkisLCevisgxKdndEkKYsqPQVOZdunSYrKdyfFOyPmNbPiXMkzjQduRxsAQwDnm179 = 231
IIIlIIIlIllllllIIlIlIllIIlIlIIIllIIllIIIlllIlIIIlIIIIIlllIllIlIlIllllIllIIlllllllIIIlIIIIIIlIlIlIllIIIIllllIIIlIIlIlIlIIIIllIIllIlIllllIIIllIllllIIlIIlIIlIlIIIIIllllIIIIlllIlllIlIIl = 444
L183 = 310
cfwtVXWaZMuPgRoOzegzhTQuVnYfPHBSSffnRvAJHrttkiHxJThDATDOcTcUDYlkUxHVtJtvQoKDzzm185 = 397
m16385592181141098187 = "jcanFgqidTMtADBEfdEuwnQdiiGplXEDxOhEYYTnrETVThfAIQUnbbrhcckpKxmvnVtiBiQbIxxFLcM"
unxvSOiEOGLnefUaEXhFUZSoJqCzIyLNmbUqqaBjZOgtgBgzXdoBUxClabfhmfkPHEkGDtMJIZlqzsT189 = "WwjmmKOdkTWDiMJFygKRMVbrCbSOJzCCmBkZXxfDziUSBYAQQhjQqbuJxfWfgvDuXBNQeiqINEZcXkr"
j191 = "shiDXPaUxMpffRIcjQBLWZFddPjDbDJSCshAeuiVbZXbCnOexdNFnBBuglphrilSeHONbOwlMouZzTl"
aAAaAAAaaaaaaAAaaAAAAAaAaaaaaaAAaaaaAAAAAaAAaaAAaAaAAAAaAAaaaAAaaAAAaAaaaAaAaAAaaaAAAaAAAaAaAAaaaAAAaAaaAAAaaAaaaaaaAAaaAaAaaaAaaaaAaaaAAaAaAaAAaAaAAAAaAaaAaAaAAaaaAAAaAAAAAAaAaaAAAaAAaAaAaAAaA = "NxzxwKijKpGueVCEkiVUKEqfCCFvUgMAlksZeqhWGCIWcivLZxcxVvUMcesdRBCDhnBfftGRVNBAxBE"
cKzEoYqzbXzkHiKdfOAXaNbgQppbMWdwqbxRZbCdgQLUxCNVHMMRLKmXVtLVstCGwwliYwLZVbEGXGI195 = 155
aaaAAAaaaaaaaaAaAaaaaaAAaaaAaaAAaaAAAaAaAaaAAaaaAaaAaaaAAAAAAaAAAaaaaaAaAAAAAaAAAaAaaAaAaaaAAAaAAAAaaAaaaAaaaAAAaaAAaAAAaaAAaAAAAaaAaAAaAAAAAaAaaAAAAaaaaAAaaaAAaaAAAaaaAaaaaaaAAAaaaaaaaAAAAaAaAAAaa = 332
IIIIllIIlIlIIlllllIllIIIIIIIIIIllIllllllllIlIlllIIlIIlIIllIIlllIIllIlIlIIlIIIlIllllIIIIlIIllIIllIIIIIIlIlllIIlIlllIIIIlIIIIlIIlIlIIIIIIlIllIlIllIIlIIlIllIllIIIlIIIIIIllllIIIllllllIlIlIllIIlIIllllIlll = 272
aaAaaaAaAAAaAAaaaaaAAaAAaaaaaAAAaaAaaAaAaaAAaaaAAaAaaaaaaaAAAaAAAaaaaaAAAaaaaAAAaaAaaaAaAaaaAaaaaAAaaaaAAaaAaaaaAaAAaaAAAaAaAaAaAAAaAaaaaaaAaaAAaaAAAaAAAAAaAaaaaAAaaaAaaAaAaAAAAAAaAaAAaAAaaAaAAAaaAAaAA = 268
lIllIIIlIllIIIlllIlIIlIllllIlIlIIIlllIIlIIIlIIIlllIIIIIlllIllIlIlIIllIllIlIllIIlIIllllIllIIllIIlIIIllIllllIlIIIIIIllllIllllllllIlllllIlIIlIIllIlIlIIlIllIlllIlllllIIllIlIIlIIIllIlllIIIlllIIlIllIlIIllIlIIl = "ogbNfbCKibENAOYqoKYklpSZWIZJLIrYbkxjhHrAEhvtzLyXNonpVJAsmLQCFeOALmgEoRGvjPYwptT"
s1638559218116128205 = "EzKdiaGYyZMAnLUXuhfWtNymNKqaRmwZmJNKMywEfzmhvNnWvDRGLutXnINNwjlEdswpFKjbPpUpfRO"
x16385592181161826207 = 309
WCKghkEDxYfMyBzhnmHmFqkrdSiazqzkekwddwLOaSwPAPSMfuIzqiAsnFlIAnYeMTcFOFhBPSiMtED209 = 340
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "kFfpSquHsAxQunonFylwLSoQRCRagitHFWibSggdzkosTwYyRyHltxrNbcjqQlmWeNePDqSHwyelQyV"
fSryPpGtsfWxXcspWrBUWchjARdLmSELxMfuTydvtFIQHaYExavuRhHhztEcCpvVPVTolwvIvGViZtt213 = 325
w215 = "xQcBeyLavxmlNSVgnPCWeuGmrvQQYLpygKxbPzAKtXhyYpNtKvjCLsvSceXUWCzEWnWxNMGJgIAAMso"
I217 = "SwrgldsPKraDlQIJdjqLWnHuCwEEFWZUVTwNnrLvodZdvnKrWkwjfYAcIYBFajFWaJsQULUhdHRrzuC"
K16385592181168578219 = 402
aaAaaaaAAAaAAaaaAAaAaaaaAaaaAaaaAaaAaAAaAAaaAAAaAAAAaaAaAaaaAAAAaaAaaaaAAaAAaAaAAAAaaaAaAAaaAAAAAaaaAAaaaaAaAAaAaAaaaAaAaaAAaaAaAaAaAaAaAaaaaaAaaAAAaaAaAaaAaaaAaAaAAaAaAAaaAAAAAaAaAAAaaAaaaaaAaAAaAAAaAAAAaAaAaaAAaAAaAaaAA = 45
lllIIIIIIlIlllIlIIIlllllIllllIIIIIlIllIlIIIIllIIllIIllIIIlIIllIIIlIIIIIlIIIlIllIIlIIIIllIlIIIIllIIllIllIIIllllIlIIlIllIIlIIlIllIllIIlIlIllllIllIlIIIlIlllIIlIIllllIllIlllIlIIIllllllIlIlIlllIlIIlllIIIIlllIllIlllIIllIlIllIIlII = "tfOoBzMxYnbvEzEMPQykKbTYFwQGAsBLwHReNrFpGuyDgxSiiJQIVjfDkcfwLnXAFNEMExghdwjTBcC"
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "vSwlbIyCOMMTvHAMEHpscqDKwbDttVoyntMDtMxlaeSrVWvktisbfAMQPTyuVHloddoECENGnigqcvv"
NuhiXobNZDJNSRvfPhZRHkLjBSXUCNxxWVWNYmrReHOuDPNxursVasCICFuYgtCzuMnfJzMhnXIUdTA227 = "kcbHCfbdDnsWDReBlZzkRLPsNQdJUBxXUdNcekmaOXDQjHnMxmsFCoGcUhPHYbdeJDFvDIionXyRcSj"
aaAaaAaaaAAAAaAaAaAaaAaaAaaAaaAaaAaaaaaAaAAaAAAaaaAaaaaaAaAaaAaAAaAAaAaaAaAAAAAaaaAaaaaaaAaaAaAAaAaaAAAaAAaAaaaaaaAAAaaAAaAaAAaaaAaAaAaAAaaaAAAaaAAaaaAaaAaAaAAaaAAAaaaAaAaAaaaAAaaaaaAAaAAaAAaAAaAaaaaaaAAaaAAaaaAaaaAAAaAaAaaAaAAaA = "edJkZstShadpYKfIBolfmztKoIHeckMpoBalpfblBaLnlSRVNQwzXsBKTvfHTFOqNRoCcRxLvBLfipt"
IllIIlIlIIIIlllIlllIllllllIIIlIIIIIllIlllllIIIIIIlllIIIIlllllIIlIlIIIIlIIlllllIlIIlIlIllIIllIIIlllIIIIlIIlIlIlIIIIIlllIlIlIIlIIIlIllIIIlIIIIIIIlIlIllIIIIlIlllIIlIIIIIlIllIlIIlIIIIlIlIIlIlIIlIIIIIlIIIllIIIllllIlllllIlIIlIIIlllIIlIII = 607
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "nhFiVZitCfLpUmLqpzVLoVhyTZEiFUzEeezxcVRuyKHeFKoIYsIRhReMtBXAcQOBFgnPNxndKdGrFRf"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "XIAgYQPemiYADJlGikBoaiTRQYdQrSNTraJaBDgDDKtDdctHiKxBKxqoneKlifBDXpZSEgbbknMtewk"
p237 = "tPrlirrtwScLfqCzxGfUtkYtdrWnHrVcynGSCvsDTbMLoiRZgHwDnNqLLGyBMwugtjQWMVproVGTJrQ"
PPXifoHPPQloXABFtFCyrTeGmWVyGeqrVAQbCvdzNCJMnayKDBbXmRRXcLkJlXQmbRJohusANqtOmeE239 = "xcpPsVRChgtqOGjQvjqglcEZbKInGdXhmQjxqAXmqfEAaTOEJxuqvMOLyewehFsOpresLBzxfkdricV"
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "jnbZPcjlRItxDgmGAhPuISMVJafoGKRacNTGdYJnLEazKTQngoRSnerqIAWOFeSsdtGhMjxVfeDiNJq"
aaAAaAaAaaaaAAaAaaAAaaaaAaAAAAaAaaaAAaAAAaaaaaAaaAaAAAaAaaAAaAaAAAaaAAaaaaAAAAaaAAaAaAAAaaAaaAaaAaAAAAAAAAAAAaAaAAAAaAaAAaaaaAAaAAaAaAAaAAaAaAaaAaaaAaAAaaAAAAAAAaaAaAaaAaAAaAAAAaaAAaAaaAaaaAAaAaAaaAAaaaaaAAAAaAaaaaAaaAaAAaAAaAaAAaaAAAAAaAaaaaa = 466
O245 = 552
aAaAAAaAAAAaaAAaaAAaAAaAAAaAaAaaAaaaaaAAAAaAAaaAaaAAaAaAaAaAAAaaAaaaaAaaaAAAaAaAaAaaaaaaAaaaaAaAaAaaaAaaAaaaAAAAAaAaaaAAAaaAAaaAAAaAAAAaaAAaAAAAaaaAAaaaAaAaAaaaaaaAAAaAAaaaaaAaaaAAaaaaAAAAAaaaaaAAAaaaaaAaaAAaAAAaAaaAaAaaaaaaaaAAAAAAaAAAaaaAAAaaaAA = 227
Z1638559218118945249 = "TIRJblbKcBbCGMJvjQhsKIrdldcrkwtTXuyotCHsOWhRRGTkVhYvyBsMbjkiLbpYkGCPSLfnbjERULI"
lIIlIIIIlIllllIIlIlIlIIlIIIlIllIlllllIlllIllllllllllIlllIlIllIlIIIIIIIIIIlIIlIlIIlllIlIlllIllllllIIIlIIIIIllIIlIIIIlllIIIIIlllllIIIlllllIlIIIIIllIlIIlIIlIllIlllIIlIllIIIllllIlIlIlIlIIIIIlllIIIlllIlllIIIIlIllIlIlIIIllllIIIIlllIlIIllIllIlIIllIllIIIlIlIl = "nZnJknqdDfMtfIQHGSACZNxOnygnpHOHTAFyIoulPMUndZqLNFiBTDsPfvewqGMHuHBWeYkIQXrkaLm"
nEWudyZAGNsrBUrhYJNJoIrXTRMBDlnPMoTGmLPUQndABrUhsZjBwKTljQDdzsTdrnfZWdsCVnPJwCm253 = 556
I16385592181193936255 = "GtFqKskNAvJzzPZItCoGgGBGfFbkiPQTlGOqakSWymtkLsPzJLiNluseuInVUxfqxllhJeQZrYmjwaZ"
U16385592181195204257 = "PFKFIQVEUVtnLinTAOWidIqgYZCOImzbroTYByGWCzEigPFavDVEcKBpexhvOpYKdflNobHTffKklrN"
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = 350
E16385592181196597261 = "msrIVLjUixmFQCEfXGTvsuBzTYROrKukDMhrScwpsnBffTaQnzONiHJhOYDEzVnkXgXwkpQRHVhLXng"
lIllllIIllIllIIIIIllIIIlllIIIIlIIlIIlIIlIlllIlIIIIIIllIlIIIIIlIIlIllIIIIlllIIIIlIlIIIIlIIllIlllIlIlllIIllllIlIlllIIllIIlIIIIllIlllIIIIIlIIIlllIlIlIIlllIIllllIIllllllIlIlIIlllllIIIlllIIIlIIIIlIlIllIlIIIIlIlIIIIllllIIllIIIlIllIlllllIIIlllIIlIllIIllllllllIllIIIIIIll = 402
DCHLRWJHLDspZulQgYpRDWKPCgVkGmulzKqDcMjmPwyeIovUAIeUekLOTwfVgDyVXuTShBaEHphkRDU265 = 978
aaAAaAAAAaAAaaAaAaAAaaAAaaAaaAaAaAAaaAaaAaAaaAAAAaAaaAAAaAAaaaaaAaAaaAaAAAAAaAaAaaaAaAAaaAaAaaAaAaaaAAAAaAAaaaAaAaAaaAaaAAAaaAaAaAaaAAaaAaAaAaAaAaaAAAaAAaAaAAAaaAAAaaaaAaaaaaAaaaAaaAAaAaaAAAAAaAAAAAaaaAaaAaaAaAAaaAaAaAaaaaAAAaAaAaAaaAaaAaAaaAaaaAaaaaaAaAaaAaaAAaAAAAa = "JDXROxTWzxlRIjozKepGIWSrfaCSLDHUadoSyUKskrufETEZDoeyreRofxyJrSBdNUFDcZxuPecOtaf"
w269 = "okkFlHFGaSXFxbOWuVJMOMRHKayWaiqoifdCHsyDCvoTxTmRrRnsgEjBOskDEzsBeCJXWhBuefaIRDR"
t271 = 193
IlIIlIIIlllIllIllIIlIIlIIIllIlllIlIlIlIIllIIIIIIIllIIllIlIIIllllIIIlIIllllIllIIIIllIlIlIIIIlllIIIIIlllIIIIllIlllIlIIlIIIlIIlllIlIlIIIIlIllIlllllIlIlIllllIIllIIIIIlIlIIlIlIlIlIIIIIlIllIIlllllllIlIlIlllIIIIlIllIlIllIlllllIIIIIllllIlIlllllIlllIlllIlIllIllllIIIIlIIlllIlIllIIlI = 607
r275 = "TwiMBscCVHZbsxExNgeGXkvCqadMgFEBsmYZJKyqCrwCTCTOIfFnyqgHFHJQAfVZTuUgInlCvHOMbgr"
z1638559218120999277 = 334
gbvvlIGXZztqIGhSgUTFilaAUFHufsGBZHIsOEeZvHCvtMXLXCntOlvZZHKYirxPfjdTlRfyhINudIa279 = "NElxEdMwaTLURytDZzrZTLKJLRBMQKhqxFvsCWLodXihAhaWUTKlndXKgloqNlMrnNPvwyqACMOCAjc"
AaaAaaaAAaAaaAaaaAAaAaaaAaAAAAaAaaaaaaAAAaAAAAaaaaaaaaAaaAaaaaAaAAaaAAaaaAaaAAAaAAaaaaaAAaAaaaAaAaAaAAaAaAAaAAaAAAaAAaAaAaAaaaAaaaaAaaaaaaaaAaaaAAaAaaaaaaaaaAaAaaaaaaaaAaAaAaAaAAAAAAaaaAAAAAAaAaaaAAaaAaaAaaaAaaAAaaaAAAaaaaAaAaaAAaAaaaaaaAaAaAAaaAaAAaaAAaaAAaAAaAaaaaaAAAaaaaaAaaaaA = "bbFIbZcIXflfnYEPzjopbWkBsTNOCbBanjTRSnBlVKgbjKUcFROKJySWWMEkXChGeLgVqktqSWVHUgi"
PnTkMvCTkEkfObbWSGVaCeqMxldMhHoBihIHKKugPlprgnRjRJgkWvHagDfDAGpJFwBDKEtjjmtarkU283 = "JzfJfxPLbdIobfnwPmsfGMiJCsxBxLYeHuxynpmBYjxjLkHZfufdjambsoNETCpInDFKnBmaZixorcc"
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = "YoNkFzPWitmfmephWFGpuCMXPgWXUnOaOoeFaWyaNJjpEHbsVHOcAdwWlWkSBYHyTREJZkESsOJEDJg"
HrqUmPcogVXEgEgWyHsbjikMebQYKRFAMgwEDLFaVmUKDOPhjUjtOBVFAtApNboDwAqYmIlPQvZzMvo287 = "EKqCdeFqmVEcUbxdwQBtOIAUqocWnrDUcbcVMqWKckkogyowSPYPOQJagxNlkiAmPVGkinkJuwEJEMO"
IlIIlIlIIlIllIlllIlllIIllIllllllllllllIllIIllIIIIlllllIlIllIlllIlIlIlllllIllllIIIIlIllIllIIIlIIllIllIlllIIllIIIIIlIllllIIlIIIIlIIllIlllIlllllIIIlllIIIlIIllllllllIIlIlIIIlIIlIIlIllIlIlIllIllllIIIlIlllllIIIIlIIIlllllIIIIlllIlIIlIIlIllIIlIIlIlIlIIllIIIIllIIllIIlIIlIllIllllllllIIIllIlllllIIlI = "sBBYWjokbRPxEHwXghtpXVPNdQSVolRvwYcBBOUIPHKdDrcPIRwYeMDmvzdWAepFFCbrSZqbzXaYTbO"
IIIIlIIIllIIlIIllllIlIIllllllllIlIlllIlllIIlIlllIIlIlllIIIlllIlIIlllIIIIIlIllIllllllIlllIIlIlIlIIIIllIIIllIIIIIIIllIllIllIIIlIllIlIlIlIIllllIIIIIlIllIIlIllIIlIIIIIIlIIIllllllIIIIIlllIIlIlIlIlllIIllllIlllIIIlIIIIIIllIlIIIIllIIllIlIlIIIIIIIlllIllIIlIlIIlIIllIIllIlIIllIllllllIIllllllIlIlIIlIIl = 483
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 674
llIIIlIIIllIlIllIIIIllllIIIIlIIlIllIIllIlllIIlIlIIIllIllIIllIlllIllIIlIIlIlIIlIllllllIllIIIIIllllIIIlIIllIIIIIlIlIIIlIIllIlIlIllllIIIlllIlllIlIlIllllIlIlllIIlIlIllIlIIIIIlllIIlllIIlIIIIIlIlllIIIIlIIllIIIIlIllllIllllIIlIIlIIIIlIIlIIlIIIIlIIlIIIIlIllIIIIlIIlIlllIIIlIIIlIlIlIllIIIIllIIIllllIlllIIl = "WTDcGldSKGqkTkmzAlXcWHruzbKYPRhJlhDpmWLpzIYfcVOAgwvMHtuJOdyhkRzYPQrWFWKXqcKftFc"
IlIIIlIIIlIllllIIIlllIIIIIlIIIlllIllIIllIlIIIIIlllllIIllIlIlIIIlllIIIlIIllIIIIllllIIIllIlIIlIIlIIIIIIlllIIIlIlllIIlIlIIlIIIIlIlIIlIllIIlIIlIIlIIIIlIIIlIllIllIIIIIIIIIllllIlIllIIllllIlIIlIIllIIlIlIIlIlllllIIlIllIllIllllllIlllIllIlIIIIllllIllIlIlIIlllIlIIIlIlIIIllIlIllIIlllllIIIlIlIIIIlIlIllIllllll = "LDeizUWcoAXdsZaqPsdYuogmwfGROLxELeRuDNJriKkEJhDJZULDPJuopjCAKzaOlFlRAfTrFhEbkXo"
gDUVbZLElEiotcPFiWFdkXsLYwtrKvcKndeCMAhikyPIDzEZmSXwNKaraHqEQOEapZHKfqbrchkSTTF299 = "ZUxpqfTvYEEsvgWVzTpBTzCIbOkGDrgBKBhfhOgWtCJMmXUbCXEOSgrKgGEGjmZweZfxIySDhHsgjEX"
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ = 475
kBSiBvkuJsoTZpqLNpDkOVNtcvBnKIIpfGTTIZTJAfTacDHcERgPMjCgCRVnBfowQEBIexMbxskTtjM303 = "VXBlVPosxvEjksAzVxSkZCGgpthuiRBYcDpgYXNippTEjZFQXxNXorefaSqvvvUljiasBcCylMgHZre"
l16385592181233451305 = 314
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "SryQMIeJpniqNHdCWQnkJFvXVnyVNaaCytcOjXRmSUgTnFJlAYjFRrtrRKAIxIAbtoYPRZeQJvXDZDR"
llllIllIlIlIllIllIIIIIIIIIIllIIlllllIIIIIlIlIlllllIlIIIIlIlllIlIIIIIIIIlllIIlIlllIlIIIIlIlllIlIlIllIlIlIIllllIlllllIIIlllllllIIIlllIIIlllIlllIIIllIIlIllllIlIIIIIIIlllIIlllllIIIllIlIlIllIIlIIIlIlIlIllllllIIllllllllIIllIIIIIlIIIlllllIllllIlIllIlIIllIIllIIlllIIIIIlIIllIIIIllllllllIllIllIIlIIIIIIlllIlllllIlllllI = "jnjhMVtqGytLdwjLrYQzfPFEwZQICpoPajechGlsxErUeKMZtrLvmWoDrOWdyAcUyswOurIFmDhQUmV"
aaaaaaAAAAAaAaAaAaaAAaAAaAAAaAaaAAAaaaaAaAAAAAaAAAAAaAAAaaAaaAaaAAAAaAAaAaaAaaAAAAAaAAAAaAaAaaAAAaaaaaAaaAaaaaaaAAAAAAaAaaAaaaaaaaaAAaAAAaaAAaaaAaaaAaaaaAaAaAaAaaaaaaAAaAaAaaaAaaaAaAaAaAaAAAaAAaAaAAAAaAaaAaaaaAAAaAAAaAaaaaaAAaAaaaAaaAAAaaAaAAaAAAAAaaAaaaAaAAAAaAAaAAaaAAAaAAAaaaAaaAaaaaAaAaaAaAaaAaAAaaAAAAaAAAa = "mgJcMtHIFyvomIfZUAwYaDVRUcPAtrhtagqbBdjirayOAegEUDHPZKJJZokBlrdGUZDkTkFlIeJULpT"
u1638559218124207313 = 253
o16385592181242201315 = 335
AaaaaaAAaAAaAAaAAAaaAaAAaaAAaaaAAaaAAaaaAaaaaAAaAaaAAAaAaAaaaAaaaAaaaaAaaAaAaAAAAaaaAAaaAAaAAaAAaaaAAAaAaAAaAaAAaAaaaaAaAaaAAAAaaAaAaAAAaAAAaaaaAaaaAaAAAaAaAaaaAAaaAaaAaAaAAaAaaaaAaaAAaaAaaaaaAaAAaAAaaaaaAaAaaaAaAaaAaAAaaAAAaaaaaaaAaAAAaAAaaaAAAaaAAaAaaaaAAAaaAaaaaAaAAaAAaAaaAaAAaaaaAaAAaAAaAAAAAAaaaAAAAAAAAAAaaaAAa = 473
JWbcvzNGYbnlZkbHeAWnBipZmIYBRgTzhZKJPBxAzXGcdvZpoqbOCbwosAwSwLhvAgsJklYJbdNtCVc319 = 305
f321 = "nsQNLsigrfwRosJuVrxFwsOgNKAHVFaNqQoGzVmNkZasawkBKdJPjnXPGjJARRHUXeTuSEucgJnPIbL"
G16385592181246789323 = 602
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "srvlISYqgdLJUNVtsSuACqZslLCRnljpboThQStcfPdqIGdnRzFWThZpAIHvrdWtvPpmbUaaQJwTbJX"