
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T04:33:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7affa08ecdd153e137b4e68d4ebda2bde9ddd079",
 "version": "1.15.0.post.dev683"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
