"""Autogenerated file: DO NOT EDIT!"""
import typing  # noqa: F401
from dazzler.system import Component, Aspect, UNDEFINED  # noqa: F401


class BarChart(Component):
    """

    """
    data = Aspect(docstring="Data of the chart.")
    width = Aspect(docstring="Width of the chart.")
    height = Aspect(docstring="Height of the chart.")
    margin = Aspect(docstring="Spacing around the chart.")
    cartesian_grid = Aspect(children=True, docstring="Add a charts.CartesianGrid to the chart.")  # noqa: E501
    tooltip = Aspect(children=True, docstring="Add a charts.Tooltip to the chart, displaying data on hover.")  # noqa: E501
    legend = Aspect(children=True, docstring="Add a charts.Legend to the chart.")  # noqa: E501
    syncId = Aspect(docstring="Sync two charts hover with the same id.")
    prepend_data = Aspect(docstring="Prepend data to the start of the list.")
    append_data = Aspect(docstring="Append data to the end of the list.")
    concat_data = Aspect(docstring="Concat a list of new data with the previous data.")  # noqa: E501
    delete_data = Aspect(docstring="Delete data by key and value.")
    insert_data = Aspect(docstring="Insert data at the index.")
    sort_data = Aspect(docstring="Sort the data.")
    handle_clicks = Aspect()
    clicks = Aspect()
    click_event = Aspect()
    handle_hover = Aspect()
    hovered = Aspect()
    hover_event = Aspect()
    bars = Aspect(children=True, docstring="List of charts.Bar")
    bar_category_gap = Aspect()
    bar_gap = Aspect()
    bar_size = Aspect()
    max_bar_size = Aspect()
    stack_offset = Aspect(docstring="(Possible values: 'none', 'expand', 'wiggle', 'silhouette', 'sign')")  # noqa: E501
    reverse_stack_order = Aspect()
    layout = Aspect(docstring="Layout direction of the items of the chart. (Possible values: 'horizontal', 'vertical')")  # noqa: E501
    reference_areas = Aspect(children=True, docstring="Add areas to highlight in the chart, list of charts.ReferenceArea")  # noqa: E501
    reference_dots = Aspect(children=True, docstring="Add charts.ReferenceDot")
    reference_lines = Aspect(children=True, docstring="Add charts.ReferenceLine")  # noqa: E501
    brush = Aspect(children=True, docstring="Add charts.Brush elements.")
    y_axis = Aspect(children=True, docstring="List of charts.YAxis")
    x_axis = Aspect(children=True, docstring="List of charts.XAxis")
    class_name = Aspect(docstring="Class name automatically added by dazzler api with a prefix for the component library.ie: core component Container become ``dazzler-core-container``.When added on the component, the class names will be concatenated.")  # noqa: E501
    style = Aspect(docstring="Style object for the top level wrapper of the component.")  # noqa: E501

    def __init__(
            self,
            data: typing.Optional[typing.List[typing.Any]] = UNDEFINED,
            width: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            height: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            margin: typing.Optional[typing.Dict[str, typing.Union[typing.Union[float, int]]]] = UNDEFINED,  # noqa: E501
            cartesian_grid: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            tooltip: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            legend: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            syncId: typing.Optional[str] = UNDEFINED,
            prepend_data: typing.Optional[typing.Any] = UNDEFINED,
            append_data: typing.Optional[typing.Any] = UNDEFINED,
            concat_data: typing.Optional[typing.Any] = UNDEFINED,
            delete_data: typing.Optional[typing.Dict[str, typing.Union[str, typing.Any]]] = UNDEFINED,  # noqa: E501
            insert_data: typing.Optional[typing.Dict[str, typing.Union[typing.Union[float, int], typing.Any]]] = UNDEFINED,  # noqa: E501
            sort_data: typing.Optional[typing.Dict[str, typing.Union[str, typing.Any]]] = UNDEFINED,  # noqa: E501
            handle_clicks: typing.Optional[bool] = UNDEFINED,
            clicks: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            click_event: typing.Optional[typing.Any] = UNDEFINED,
            handle_hover: typing.Optional[bool] = UNDEFINED,
            hovered: typing.Optional[bool] = UNDEFINED,
            hover_event: typing.Optional[typing.Any] = UNDEFINED,
            bars: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            bar_category_gap: typing.Optional[typing.Union[float, int]] = UNDEFINED,  # noqa: E501
            bar_gap: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            bar_size: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            max_bar_size: typing.Optional[typing.Union[float, int]] = UNDEFINED,  # noqa: E501
            stack_offset: typing.Optional[typing.Any] = UNDEFINED,
            reverse_stack_order: typing.Optional[bool] = UNDEFINED,
            layout: typing.Optional[typing.Any] = UNDEFINED,
            reference_areas: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            reference_dots: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            reference_lines: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            brush: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            y_axis: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            x_axis: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            class_name: typing.Optional[str] = UNDEFINED,
            style: typing.Optional[typing.Dict] = UNDEFINED,
            identity: str = None
    ):
        """
        :param data: Data of the chart.
        :param width: Width of the chart.
        :param height: Height of the chart.
        :param margin: Spacing around the chart.
        :param cartesian_grid: Add a charts.CartesianGrid to the chart.
        :param tooltip: Add a charts.Tooltip to the chart, displaying data
            on hover.
        :param legend: Add a charts.Legend to the chart.
        :param syncId: Sync two charts hover with the same id.
        :param prepend_data: Prepend data to the start of the list.
        :param append_data: Append data to the end of the list.
        :param concat_data: Concat a list of new data with the previous
            data.
        :param delete_data: Delete data by key and value.
        :param insert_data: Insert data at the index.
        :param sort_data: Sort the data.
        :param handle_clicks:
        :param clicks:
        :param click_event:
        :param handle_hover:
        :param hovered:
        :param hover_event:
        :param bars: List of charts.Bar
        :param bar_category_gap:
        :param bar_gap:
        :param bar_size:
        :param max_bar_size:
        :param stack_offset: (Possible values: 'none', 'expand', 'wiggle',
            'silhouette', 'sign')
        :param reverse_stack_order:
        :param layout: Layout direction of the items of the chart.
            (Possible values: 'horizontal', 'vertical')
        :param reference_areas: Add areas to highlight in the chart, list
            of charts.ReferenceArea
        :param reference_dots: Add charts.ReferenceDot
        :param reference_lines: Add charts.ReferenceLine
        :param brush: Add charts.Brush elements.
        :param y_axis: List of charts.YAxis
        :param x_axis: List of charts.XAxis
        :param class_name: Class name automatically added by dazzler api
            with a prefix for the  component library. ie: core component
            Container become ``dazzler-core-container``. When added on the
            component, the class names will be concatenated.
        :param style: Style object for the top level wrapper of the
            component.
        """
        Component.__init__(self, locals(), identity)
