"""Autogenerated file: DO NOT EDIT!"""
import typing  # noqa: F401
from dazzler.system import Component, Aspect, UNDEFINED  # noqa: F401


class PieChart(Component):
    """

    """
    height = Aspect(docstring="Height of the chart.")
    width = Aspect(docstring="Width of the chart.")
    tooltip = Aspect(children=True, docstring="Add a charts.Tooltip to the chart, displaying data on hover.")  # noqa: E501
    margin = Aspect(docstring="Spacing around the chart.")
    legend = Aspect(children=True, docstring="Add a charts.Legend to the chart.")  # noqa: E501
    syncId = Aspect(docstring="Sync two charts hover with the same id.")
    handle_clicks = Aspect()
    clicks = Aspect()
    click_event = Aspect()
    handle_hover = Aspect()
    hovered = Aspect()
    hover_event = Aspect()
    pies = Aspect(children=True, docstring="List of charts.Pie")
    polar_grid = Aspect(children=True, docstring="A charts.PolarGrid component.")  # noqa: E501
    polar_angle_axis = Aspect(children=True, docstring="List of charts.PolarAngleAxis")  # noqa: E501
    polar_radius_axis = Aspect(children=True, docstring="List of charts.PolarRadiusAxis")  # noqa: E501
    class_name = Aspect(docstring="Class name automatically added by dazzler api with a prefix for the component library.ie: core component Container become ``dazzler-core-container``.When added on the component, the class names will be concatenated.")  # noqa: E501
    style = Aspect(docstring="Style object for the top level wrapper of the component.")  # noqa: E501

    def __init__(
            self,
            height: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            width: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            tooltip: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            margin: typing.Optional[typing.Dict[str, typing.Union[typing.Union[float, int]]]] = UNDEFINED,  # noqa: E501
            legend: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            syncId: typing.Optional[str] = UNDEFINED,
            handle_clicks: typing.Optional[bool] = UNDEFINED,
            clicks: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            click_event: typing.Optional[typing.Any] = UNDEFINED,
            handle_hover: typing.Optional[bool] = UNDEFINED,
            hovered: typing.Optional[bool] = UNDEFINED,
            hover_event: typing.Optional[typing.Any] = UNDEFINED,
            pies: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            polar_grid: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            polar_angle_axis: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            polar_radius_axis: typing.Optional[typing.List[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]]] = UNDEFINED,  # noqa: E501
            class_name: typing.Optional[str] = UNDEFINED,
            style: typing.Optional[typing.Dict] = UNDEFINED,
            identity: str = None
    ):
        """
        :param height: Height of the chart.
        :param width: Width of the chart.
        :param tooltip: Add a charts.Tooltip to the chart, displaying data
            on hover.
        :param margin: Spacing around the chart.
        :param legend: Add a charts.Legend to the chart.
        :param syncId: Sync two charts hover with the same id.
        :param handle_clicks:
        :param clicks:
        :param click_event:
        :param handle_hover:
        :param hovered:
        :param hover_event:
        :param pies: List of charts.Pie
        :param polar_grid: A charts.PolarGrid component.
        :param polar_angle_axis: List of charts.PolarAngleAxis
        :param polar_radius_axis: List of charts.PolarRadiusAxis
        :param class_name: Class name automatically added by dazzler api
            with a prefix for the  component library. ie: core component
            Container become ``dazzler-core-container``. When added on the
            component, the class names will be concatenated.
        :param style: Style object for the top level wrapper of the
            component.
        """
        Component.__init__(self, locals(), identity)
