"""Autogenerated file: DO NOT EDIT!"""
import typing  # noqa: F401
from dazzler.system import Component, Aspect, UNDEFINED  # noqa: F401


class ResponsiveContainer(Component):
    """

    """
    height = Aspect()
    id = Aspect()
    width = Aspect()
    children = Aspect(required=True, children=True)
    aspect = Aspect()
    minWidth = Aspect()
    minHeight = Aspect()
    maxHeight = Aspect()
    debounce = Aspect()

    def __init__(
            self,
            children: typing.Union[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]],  # noqa: E501
            height: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            id: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            width: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            aspect: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            minWidth: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            minHeight: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            maxHeight: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            debounce: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            identity: str = None
    ):
        """
        :param height:
        :param id:
        :param width:
        :param children:
        :param aspect:
        :param minWidth:
        :param minHeight:
        :param maxHeight:
        :param debounce:
        """
        Component.__init__(self, locals(), identity)
