
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T11:58:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e90d154c98794bfcd71c79a21e4fc132e45276a",
 "version": "0.7.1.post.dev201"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
