# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: featurestore/core/ServiceBus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='featurestore/core/ServiceBus.proto',
  package='featurestore.core',
  syntax='proto3',
  serialized_options=b'\n\030ai.h2o.featurestore.coreB\017ServiceBusProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"featurestore/core/ServiceBus.proto\x12\x11\x66\x65\x61turestore.core\"r\n\x16\x41zureServiceBusDetails\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x63\x63\x65ss_key_name\x18\x02 \x01(\t\x12\x18\n\x10\x61\x63\x63\x65ss_key_value\x18\x03 \x01(\t\x12\x12\n\ntopic_name\x18\x04 \x01(\t\"\x16\n\x14\x41wsServiceBusDetailsB+\n\x18\x61i.h2o.featurestore.coreB\x0fServiceBusProtob\x06proto3'
)




_AZURESERVICEBUSDETAILS = _descriptor.Descriptor(
  name='AzureServiceBusDetails',
  full_name='featurestore.core.AzureServiceBusDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='featurestore.core.AzureServiceBusDetails.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_key_name', full_name='featurestore.core.AzureServiceBusDetails.access_key_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_key_value', full_name='featurestore.core.AzureServiceBusDetails.access_key_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic_name', full_name='featurestore.core.AzureServiceBusDetails.topic_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=171,
)


_AWSSERVICEBUSDETAILS = _descriptor.Descriptor(
  name='AwsServiceBusDetails',
  full_name='featurestore.core.AwsServiceBusDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['AzureServiceBusDetails'] = _AZURESERVICEBUSDETAILS
DESCRIPTOR.message_types_by_name['AwsServiceBusDetails'] = _AWSSERVICEBUSDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AzureServiceBusDetails = _reflection.GeneratedProtocolMessageType('AzureServiceBusDetails', (_message.Message,), {
  'DESCRIPTOR' : _AZURESERVICEBUSDETAILS,
  '__module__' : 'featurestore.core.ServiceBus_pb2'
  # @@protoc_insertion_point(class_scope:featurestore.core.AzureServiceBusDetails)
  })
_sym_db.RegisterMessage(AzureServiceBusDetails)

AwsServiceBusDetails = _reflection.GeneratedProtocolMessageType('AwsServiceBusDetails', (_message.Message,), {
  'DESCRIPTOR' : _AWSSERVICEBUSDETAILS,
  '__module__' : 'featurestore.core.ServiceBus_pb2'
  # @@protoc_insertion_point(class_scope:featurestore.core.AwsServiceBusDetails)
  })
_sym_db.RegisterMessage(AwsServiceBusDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
