
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T11:25:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4cf00aba283ccff3e5e504378507898f237cca7",
 "version": "0.7.1.post.dev191"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
