[tool.poetry]
name = "zygoat-django"
version = "0.7.0"
description = ""
authors = ["Mark Rawls <markrawls96@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
importlib-metadata = "^1.7.0"
django = ">=2"
django-environ = ">=0.4.4"
djangorestframework = ">=3.9.1"
djangorestframework-camel-case = ">=1.2.0"
django-redis = ">=5.0.0"
uvicorn = {version = ">=0.13.0", extras = ["standard"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8-black = "^0.2.1"
black = "^21.11b1"
watchdog = "^2.1.6"
sphinx-autoapi = "^1.5.0"
rtd-poetry-tmp = "^0.1.2"
Sphinx = "^4.3.1"
sphinx-rtd-theme = "^1.0.0"

[tool.black]
line-length = 95
target-version = ['py37']
[build-system]
requires = ["poetry>=0.12", "rtd-poetry-tmp"]
build-backend = "rtd_poetry"
