[tool.poetry]
name = "djangopyetl"
version = "0.1.5"
description = "Django app for ETL"
authors = ["MacSoares <macario.junior@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1, <3.11"
Django = "^3.1"
numpy = "^1.21.3"
pandas = "1.3.4"
SQLAlchemy = "^1.4.26"
pyodbc = "^4.0.32"
ipython = "^7.28.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
