- project:
    templates:
      - check-requirements
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        # NOTE(rpittau): yoga jobs support py38 and py39 but we want to keep
        # testing py36 to maintain compatibility with older distributions like
        # CentOS Stream 8, Ubuntu Bionic, Debian 10, and openSuse Leap
        # Remove after Yoga
        - openstack-tox-py36
    gate:
      jobs:
        # NOTE(rpittau): yoga jobs support py38 and py39 but we want to keep
        # testing py36 to maintain compatibility with older distributions like
        # CentOS Stream 8, Ubuntu Bionic, Debian 10, and openSuse Leap
        # Remove after Yoga
        - openstack-tox-py36
