#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['twottle']

package_data = \
{'': ['*'],
 'twottle': ['cache/*',
             'cache/games/*',
             'cache/users/*',
             'static/*',
             'views/*']}

package_dir = \
{'': 'src'}

install_requires = \
['bottle', 'httpx', 'peewee', 'waitress', 'streamlink', 'yt-dlp']

entry_points = \
{'console_scripts': ['twottle = twottle.app:main']}

setup(name='twottle',
      version='0.4.1',
      description='Web GUI for streamlink cli',
      author=None,
      author_email='Raeed Ahmed <ruahmed7868@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      entry_points=entry_points,
     )
