[tool.poetry]
name = "django_pay2"
version = "2.0.1"
description = "Интеграция платежных систем для Django"
authors = ["Anatoly Gusev <gusev.tolia@yandex.ru>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/la1t/django_pay"

[tool.poetry.dependencies]
python = "3.9"
Django = "^3.2.7"
django-ipware = "^4.0.0"
requests = "^2.26.0"
djangorestframework = "^3.12.4"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
flake8 = "^3.9.2"
tox = "^3.24.4"
pytest = "^6.2.5"
pytest-django = "^4.4.0"
pytest-mock = "^3.6.1"
factory-boy = "^3.2.0"
pytest-factoryboy = "^2.1.0"
responses = "^0.14.0"
black = "^21.9b0"
rope = "^0.19.0"
pre-commit = "^2.15.0"
ipython = "^7.27.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
