
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T16:25:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "561933095390fac0651794677b6c622edf8f3785",
 "version": "0.7.1.post.dev185"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
