
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/ol_openedx_canvas_integration:canvas_integration_package

from setuptools import setup

setup(**{
    'description': 'An Open edX plugin to add canvas integration support',
    'entry_points': {
        'lms.djangoapp': [
            'ol_openedx_canvas_integration = ol_openedx_canvas_integration.app:CanvasIntegrationConfig',
        ],
        'cms.djangoapp': [
        ],
    },
    'name': 'ol-openedx-canvas-integration',
    'version': '0.1.0',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        '',
        'ol_openedx_canvas_integration',
        'ol_openedx_canvas_integration.settings',
    ),
    'namespace_packages': (
    ),
    'package_data': {
    },
    'install_requires': (
        'Django>2.0',
        'edx-django-utils<5.0.0,>=4.0.0',
    ),
})
