
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T22:11:12-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e9c40a5ecebac1eb883c2ea87b94a7b01ae6192",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
