build: false

environment:
  matrix:
    - PYTHON: 3.7
    - PYTHON: 3.8

platform:
  - x86

init:
  - "ECHO %PYTHON%"
  - cmd: SET PATH=C:\Miniconda3\Scripts;C:\Miniconda\Scripts;%PATH%
  - cmd: conda update -yq conda
  - cmd: conda install -yq conda-env conda-build 
  - cmd: conda create -yq -n condaenv python=%PYTHON%

install:
  - cmd: activate condaenv
  - cmd: conda install -yq pip numpy pandas scipy matplotlib pytest sympy pytz
  - cmd: pip install -r requirements_test.txt
  - cmd: python setup.py install
  - cmd: rmdir /Q /S qsdsan

test_script:
  - cmd: pytest --cov-report html --cov=qsdsan -m "not slow and not online"
