
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T15:17:44+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "944c10f222b99439b0b637d071422aeba72b0349",
 "version": "4.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
