
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T18:16:32+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4cf2b200a585c2f5cf51c140ca424d380d775a70",
 "version": "0.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
