# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_types_pb2 as basic__types__pb2
import timestamp_pb2 as timestamp__pb2
import consensus_submit_message_pb2 as consensus__submit__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='consensus_service.proto',
  package='com.hedera.mirror.api.proto',
  syntax='proto3',
  serialized_options=b'\n\033com.hedera.mirror.api.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63onsensus_service.proto\x12\x1b\x63om.hedera.mirror.api.proto\x1a\x11\x62\x61sic_types.proto\x1a\x0ftimestamp.proto\x1a\x1e\x63onsensus_submit_message.proto\"\x9f\x01\n\x13\x43onsensusTopicQuery\x12\x1f\n\x07topicID\x18\x01 \x01(\x0b\x32\x0e.proto.TopicID\x12,\n\x12\x63onsensusStartTime\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12*\n\x10\x63onsensusEndTime\x18\x03 \x01(\x0b\x32\x10.proto.Timestamp\x12\r\n\x05limit\x18\x04 \x01(\x04\"\xd5\x01\n\x16\x43onsensusTopicResponse\x12,\n\x12\x63onsensusTimestamp\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x0f\n\x07message\x18\x02 \x01(\x0c\x12\x13\n\x0brunningHash\x18\x03 \x01(\x0c\x12\x16\n\x0esequenceNumber\x18\x04 \x01(\x04\x12\x1a\n\x12runningHashVersion\x18\x05 \x01(\x04\x12\x33\n\tchunkInfo\x18\x06 \x01(\x0b\x32 .proto.ConsensusMessageChunkInfo2\x8d\x01\n\x10\x43onsensusService\x12y\n\x0esubscribeTopic\x12\x30.com.hedera.mirror.api.proto.ConsensusTopicQuery\x1a\x33.com.hedera.mirror.api.proto.ConsensusTopicResponse0\x01\x42\x1f\n\x1b\x63om.hedera.mirror.api.protoP\x01\x62\x06proto3'
  ,
  dependencies=[basic__types__pb2.DESCRIPTOR,timestamp__pb2.DESCRIPTOR,consensus__submit__message__pb2.DESCRIPTOR,])




_CONSENSUSTOPICQUERY = _descriptor.Descriptor(
  name='ConsensusTopicQuery',
  full_name='com.hedera.mirror.api.proto.ConsensusTopicQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topicID', full_name='com.hedera.mirror.api.proto.ConsensusTopicQuery.topicID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consensusStartTime', full_name='com.hedera.mirror.api.proto.ConsensusTopicQuery.consensusStartTime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consensusEndTime', full_name='com.hedera.mirror.api.proto.ConsensusTopicQuery.consensusEndTime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='com.hedera.mirror.api.proto.ConsensusTopicQuery.limit', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=284,
)


_CONSENSUSTOPICRESPONSE = _descriptor.Descriptor(
  name='ConsensusTopicResponse',
  full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consensusTimestamp', full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse.consensusTimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse.message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runningHash', full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse.runningHash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse.sequenceNumber', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runningHashVersion', full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse.runningHashVersion', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunkInfo', full_name='com.hedera.mirror.api.proto.ConsensusTopicResponse.chunkInfo', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=500,
)

_CONSENSUSTOPICQUERY.fields_by_name['topicID'].message_type = basic__types__pb2._TOPICID
_CONSENSUSTOPICQUERY.fields_by_name['consensusStartTime'].message_type = timestamp__pb2._TIMESTAMP
_CONSENSUSTOPICQUERY.fields_by_name['consensusEndTime'].message_type = timestamp__pb2._TIMESTAMP
_CONSENSUSTOPICRESPONSE.fields_by_name['consensusTimestamp'].message_type = timestamp__pb2._TIMESTAMP
_CONSENSUSTOPICRESPONSE.fields_by_name['chunkInfo'].message_type = consensus__submit__message__pb2._CONSENSUSMESSAGECHUNKINFO
DESCRIPTOR.message_types_by_name['ConsensusTopicQuery'] = _CONSENSUSTOPICQUERY
DESCRIPTOR.message_types_by_name['ConsensusTopicResponse'] = _CONSENSUSTOPICRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConsensusTopicQuery = _reflection.GeneratedProtocolMessageType('ConsensusTopicQuery', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSTOPICQUERY,
  '__module__' : 'consensus_service_pb2'
  # @@protoc_insertion_point(class_scope:com.hedera.mirror.api.proto.ConsensusTopicQuery)
  })
_sym_db.RegisterMessage(ConsensusTopicQuery)

ConsensusTopicResponse = _reflection.GeneratedProtocolMessageType('ConsensusTopicResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONSENSUSTOPICRESPONSE,
  '__module__' : 'consensus_service_pb2'
  # @@protoc_insertion_point(class_scope:com.hedera.mirror.api.proto.ConsensusTopicResponse)
  })
_sym_db.RegisterMessage(ConsensusTopicResponse)


DESCRIPTOR._options = None

_CONSENSUSSERVICE = _descriptor.ServiceDescriptor(
  name='ConsensusService',
  full_name='com.hedera.mirror.api.proto.ConsensusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=503,
  serialized_end=644,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribeTopic',
    full_name='com.hedera.mirror.api.proto.ConsensusService.subscribeTopic',
    index=0,
    containing_service=None,
    input_type=_CONSENSUSTOPICQUERY,
    output_type=_CONSENSUSTOPICRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONSENSUSSERVICE)

DESCRIPTOR.services_by_name['ConsensusService'] = _CONSENSUSSERVICE

# @@protoc_insertion_point(module_scope)
