[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "asgiref==3.4.1",
    "Django==3.2.9",
    "inflect==5.3.0",
    "pytz==2021.3",
    "sqlparse==0.4.2",

]

build-backend = "setuptools.build_meta"