
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-01T04:35:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e1a2ecc5a9badc1c152096d79e82f2cdd5ec923",
 "version": "1.15.0.post.dev638"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
