
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-30T13:38:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4605b3c08b33c6e81466b74cd5774cde9f18799b",
 "version": "1.15.0.post.dev636"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
