version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - "changelog: skip"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - "changelog: skip"
      - dependencies
