
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T05:05:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc3fa06d0d0b82bc0a591eeba8ba97b189dc8078",
 "version": "1.15.0.post.dev685"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
