[tool.poetry]
name = "backend_library_common"
version = "0.1.5"
description = ""
authors = ["Felix <contact@felixnaser.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/intelligence-for-robots/backend.library.common"
repository = "https://github.com/intelligence-for-robots/backend.library.common"
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.6.1"
fastapi = "^0.70.0"
httpx = "^0.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
