[tool.poetry]
name = "eclipse"
version = "0.1.0"
description = "A simplified and extended version of OpenAI's Contrastive Language-Image Pretraining"
authors = ["CWDT <null@cwdt.us>"]
license = "CC0 1.0 Universal"

[tool.poetry.dependencies]
python = "^3.6"
pytorch = "^1.7.1"
torchvision = "^0.11.1"
ftfy = "^6.0.3"
regex = "^2021.11.10"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
numpy = "^1.21.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
