
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T15:22:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dce0f7b45502cf983c607f291a512cdf02afed18",
 "version": "v3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
