
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T10:24:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "52afe54e3946c18e09b55a3acc81e9ac1c8b3aa7",
 "version": "2.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
