
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-03T14:49:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f826145469a997fb31711efa6f6ce7adddbf15f",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
