
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T05:12:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e1835e0641f39fe32f79f282cce887f402be4ae",
 "version": "1.15.0.post.dev605"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
