"""Autogenerated file: DO NOT EDIT!"""
import typing  # noqa: F401
from dazzler.system import Component, Aspect, UNDEFINED  # noqa: F401


class ColorPicker(Component):
    """
    A color picker powered by react-colorful

    A toggle button is included or can be disabled with ``toggleable=False``
    and then it be activated by binding, tie or initial value.

    Common style aspects goes on the container of the picker, hidden by default.

    :CSS:

         - ``dazzler-extra-color-picker`` - Top level container
         - ``dazzler-color-picker-toggle`` - Toggle button
         - ``dazzler-color-picker`` - Picker container.

    .. literalinclude:: ../../tests/components/pages/color_picker.py
    """
    value = Aspect(docstring="Current color value")
    type = Aspect(default="'hex'", docstring="Type of color (Possible values: 'hex', 'rgb', 'rgba', 'hsl', 'hsla', 'hsv', 'hsva') (default="'hex'")")  # noqa: E501
    toggleable = Aspect(default=True, docstring="Add a toggle button to activate the color picker. (default=True)")  # noqa: E501
    toggle_button = Aspect(children=True, docstring="Content of the toggle button.")  # noqa: E501
    toggle_on_choose = Aspect(default=True, docstring="Close the color picker when a value is selected. (default=True)")  # noqa: E501
    toggle_on_choose_delay = Aspect(default=2500, docstring="Delay before closing the modal when the (default=2500)")  # noqa: E501
    toggle_direction = Aspect(default="'top-left'", docstring="Direction to open the color picker on toggle. (Possible values: 'top', 'top-left', 'top-right', 'left', 'right', 'bottom', 'bottom-left', 'bottom-right') (default="'top-left'")")  # noqa: E501
    active = Aspect(docstring="Show the color picker.")
    toggle_button_color = Aspect(default=True, docstring="Use a square with background color from the value as the toggle button. (default=True)")  # noqa: E501
    as_string = Aspect(docstring="The value will always be a string, usable directly in styles.``toggle_button_color`` requires a string value or hex type.")  # noqa: E501
    color = Aspect(docstring="Font color")
    background = Aspect(docstring="Background color/image")
    padding = Aspect(docstring="Space around the content before the border")
    padding_top = Aspect()
    padding_bottom = Aspect()
    padding_left = Aspect()
    padding_right = Aspect()
    margin = Aspect(docstring="Space after the element border")
    margin_top = Aspect()
    margin_bottom = Aspect()
    margin_left = Aspect()
    margin_right = Aspect()
    overflow = Aspect(docstring="Overflow the content and show a scrollbar.")
    height = Aspect(docstring="Height of the component.")
    min_height = Aspect()
    max_height = Aspect(docstring="Maximum height before overflow.")
    width = Aspect(docstring="Width of the component.")
    min_width = Aspect()
    max_width = Aspect(docstring="Maximum width before overflowing.")
    font_family = Aspect(docstring="Font to use.")
    font_size = Aspect(docstring="Size of the font.")
    font_weight = Aspect(docstring="Boldness")
    font_style = Aspect(docstring="Italic")
    text_align = Aspect(docstring="Left center right.")
    border = Aspect(docstring="Border around the component.")
    border_radius = Aspect(docstring="Round the corner of the component, needs a background or border.")  # noqa: E501
    cursor = Aspect(docstring="Cursor when the mouse is over the component.")
    flex_grow = Aspect(docstring="Grow factor for flex item.")
    flex_shrink = Aspect(docstring="Shrink factor for flex item.")
    align_self = Aspect(docstring="Flex alignment for the component. (Possible values: 'auto', 'flex-start', 'flex-end', 'center', 'baseline', 'stretch')")  # noqa: E501
    display = Aspect(docstring="CSS, How to display the component.")
    rounded = Aspect(docstring="Round the edge of the container with borderRadius: 3px;")  # noqa: E501
    bordered = Aspect(docstring="Apply default bordering with neutral dark grey,")  # noqa: E501
    centered = Aspect(docstring="Center the content in the middle of the container.")  # noqa: E501
    scrollable = Aspect(docstring="Set the overflow content to scroll.")
    hidden = Aspect(docstring="Hide the component;")
    unselectable = Aspect(docstring="Do not allow for the text to be selected.")  # noqa: E501
    preset_color = Aspect(docstring="Preset color to apply to the font. (Possible values: 'primary', 'primary-light', 'primary-dark', 'secondary', 'secondary-light', 'secondary-dark', 'tertiary', 'tertiary-light', 'tertiary-dark', 'danger', 'danger-light', 'danger-dark', 'warning', 'warning-light', 'warning-dark', 'success', 'success-light', 'success-dark', 'neutral', 'neutral-light', 'neutral-dark', 'dark', 'dark-light', 'dark-dark', 'darker', 'darker-light', 'darker-dark')")  # noqa: E501
    preset_background = Aspect(docstring="Preset color to apply to the background. (Possible values: 'primary', 'primary-light', 'primary-dark', 'secondary', 'secondary-light', 'secondary-dark', 'tertiary', 'tertiary-light', 'tertiary-dark', 'danger', 'danger-light', 'danger-dark', 'warning', 'warning-light', 'warning-dark', 'success', 'success-light', 'success-dark', 'neutral', 'neutral-light', 'neutral-dark', 'dark', 'dark-light', 'dark-dark', 'darker', 'darker-light', 'darker-dark')")  # noqa: E501
    preset_size = Aspect(docstring="Scale the size of the container using a preset. (Possible values: 'tiny', 'small', 'medium', 'large', 'larger', 'x-large', 'xx-large')")  # noqa: E501
    class_name = Aspect(docstring="Class name automatically added by dazzler api with a prefix for the component library.ie: core component Container become ``dazzler-core-container``.When added on the component, the class names will be concatenated.")  # noqa: E501
    style = Aspect(docstring="Style object for the top level wrapper of the component.")  # noqa: E501

    def __init__(
            self,
            value: typing.Optional[typing.Union[str]] = UNDEFINED,
            type: typing.Optional[typing.Any] = "'hex'",
            toggleable: typing.Optional[bool] = True,
            toggle_button: typing.Optional[typing.Union[str, int, float, Component, typing.List[typing.Union[str, int, float, Component]]]] = UNDEFINED,  # noqa: E501
            toggle_on_choose: typing.Optional[bool] = True,
            toggle_on_choose_delay: typing.Optional[typing.Union[float, int]] = 2500,  # noqa: E501
            toggle_direction: typing.Optional[typing.Any] = "'top-left'",
            active: typing.Optional[bool] = UNDEFINED,
            toggle_button_color: typing.Optional[bool] = True,
            as_string: typing.Optional[bool] = UNDEFINED,
            color: typing.Optional[str] = UNDEFINED,
            background: typing.Optional[str] = UNDEFINED,
            padding: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            padding_top: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            padding_bottom: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            padding_left: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            padding_right: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            margin: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            margin_top: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            margin_bottom: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            margin_left: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            margin_right: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            overflow: typing.Optional[str] = UNDEFINED,
            height: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            min_height: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            max_height: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            width: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            min_width: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            max_width: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            font_family: typing.Optional[str] = UNDEFINED,
            font_size: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            font_weight: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            font_style: typing.Optional[str] = UNDEFINED,
            text_align: typing.Optional[str] = UNDEFINED,
            border: typing.Optional[str] = UNDEFINED,
            border_radius: typing.Optional[typing.Union[str, typing.Union[float, int]]] = UNDEFINED,  # noqa: E501
            cursor: typing.Optional[str] = UNDEFINED,
            flex_grow: typing.Optional[typing.Union[float, int]] = UNDEFINED,
            flex_shrink: typing.Optional[typing.Union[float, int]] = UNDEFINED,  # noqa: E501
            align_self: typing.Optional[typing.Any] = UNDEFINED,
            display: typing.Optional[str] = UNDEFINED,
            rounded: typing.Optional[bool] = UNDEFINED,
            bordered: typing.Optional[bool] = UNDEFINED,
            centered: typing.Optional[bool] = UNDEFINED,
            scrollable: typing.Optional[bool] = UNDEFINED,
            hidden: typing.Optional[bool] = UNDEFINED,
            unselectable: typing.Optional[bool] = UNDEFINED,
            preset_color: typing.Optional[typing.Any] = UNDEFINED,
            preset_background: typing.Optional[typing.Any] = UNDEFINED,
            preset_size: typing.Optional[typing.Any] = UNDEFINED,
            class_name: typing.Optional[str] = UNDEFINED,
            style: typing.Optional[typing.Dict] = UNDEFINED,
            identity: str = None
    ):
        """
        :param value: Current color value
        :param type: Type of color (Possible values: 'hex', 'rgb', 'rgba',
            'hsl', 'hsla', 'hsv', 'hsva') (default="'hex'")
        :param toggleable: Add a toggle button to activate the color
            picker. (default=True)
        :param toggle_button: Content of the toggle button.
        :param toggle_on_choose: Close the color picker when a value is
            selected. (default=True)
        :param toggle_on_choose_delay: Delay before closing the modal when
            the (default=2500)
        :param toggle_direction: Direction to open the color picker on
            toggle. (Possible values: 'top', 'top-left', 'top-right', 'left',
            'right', 'bottom', 'bottom-left', 'bottom-right') (default="'top-
            left'")
        :param active: Show the color picker.
        :param toggle_button_color: Use a square with background color from
            the value as the toggle button. (default=True)
        :param as_string: The value will always be a string, usable
            directly in styles.  ``toggle_button_color`` requires a string
            value or hex type.
        :param color: Font color
        :param background: Background color/image
        :param padding: Space around the content before the border
        :param padding_top:
        :param padding_bottom:
        :param padding_left:
        :param padding_right:
        :param margin: Space after the element border
        :param margin_top:
        :param margin_bottom:
        :param margin_left:
        :param margin_right:
        :param overflow: Overflow the content and show a scrollbar.
        :param height: Height of the component.
        :param min_height:
        :param max_height: Maximum height before overflow.
        :param width: Width of the component.
        :param min_width:
        :param max_width: Maximum width before overflowing.
        :param font_family: Font to use.
        :param font_size: Size of the font.
        :param font_weight: Boldness
        :param font_style: Italic
        :param text_align: Left center right.
        :param border: Border around the component.
        :param border_radius: Round the corner of the component, needs a
            background or border.
        :param cursor: Cursor when the mouse is over the component.
        :param flex_grow: Grow factor for flex item.
        :param flex_shrink: Shrink factor for flex item.
        :param align_self: Flex alignment for the component. (Possible
            values: 'auto', 'flex-start', 'flex-end', 'center', 'baseline',
            'stretch')
        :param display: CSS, How to display the component.
        :param rounded: Round the edge of the container with borderRadius:
            3px;
        :param bordered: Apply default bordering with neutral dark grey,
        :param centered: Center the content in the middle of the container.
        :param scrollable: Set the overflow content to scroll.
        :param hidden: Hide the component;
        :param unselectable: Do not allow for the text to be selected.
        :param preset_color: Preset color to apply to the font. (Possible
            values: 'primary', 'primary-light', 'primary-dark', 'secondary',
            'secondary-light', 'secondary-dark', 'tertiary', 'tertiary-light',
            'tertiary-dark', 'danger', 'danger-light', 'danger-dark',
            'warning', 'warning-light', 'warning-dark', 'success', 'success-
            light', 'success-dark', 'neutral', 'neutral-light', 'neutral-dark',
            'dark', 'dark-light', 'dark-dark', 'darker', 'darker-light',
            'darker-dark')
        :param preset_background: Preset color to apply to the background.
            (Possible values: 'primary', 'primary-light', 'primary-dark',
            'secondary', 'secondary-light', 'secondary-dark', 'tertiary',
            'tertiary-light', 'tertiary-dark', 'danger', 'danger-light',
            'danger-dark', 'warning', 'warning-light', 'warning-dark',
            'success', 'success-light', 'success-dark', 'neutral', 'neutral-
            light', 'neutral-dark', 'dark', 'dark-light', 'dark-dark',
            'darker', 'darker-light', 'darker-dark')
        :param preset_size: Scale the size of the container using a preset.
            (Possible values: 'tiny', 'small', 'medium', 'large', 'larger',
            'x-large', 'xx-large')
        :param class_name: Class name automatically added by dazzler api
            with a prefix for the  component library. ie: core component
            Container become ``dazzler-core-container``. When added on the
            component, the class names will be concatenated.
        :param style: Style object for the top level wrapper of the
            component.
        """
        Component.__init__(self, locals(), identity)
