name: "QHub validate linter"

on:
  pull_request:
    branches:
      - "{{ cookiecutter.ci_cd.branch }}"
    paths:
      - "qhub-config.yaml"

{%- if cookiecutter.QHUB_GH_BRANCH != '' %}
env:
  # Preserve dev branch so pip_install_qhub doesn't get overridden on next render.
  # Although currently no deploy/render step in this workflow so should be OK.
  QHUB_GH_BRANCH: {{ cookiecutter.QHUB_GH_BRANCH }}
{% endif %}

jobs:
  qhub-validate:
    name: 'Qhub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
        with:
          token: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install qhub
        run: |
          {{ cookiecutter.pip_install_qhub }}
      - name: 'Qhub Linterfy'
        env:
          PR_NUMBER: {{ '${{ github.event.number }}' }}
          REPO_NAME : {{ '${{ github.repository }}' }}
          GITHUB_TOKEN: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
        run: |
          qhub validate --config qhub-config.yaml --enable-commenting