# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: m1l0_pipeline/v1/pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from m1l0_services.dataservice.v1 import data_service_pb2 as m1l0__services_dot_dataservice_dot_v1_dot_data__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='m1l0_pipeline/v1/pipeline.proto',
  package='m1l0_pipeline.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fm1l0_pipeline/v1/pipeline.proto\x12\x10m1l0_pipeline.v1\x1a/m1l0_services/dataservice/v1/data_service.proto\"c\n\x0ePipelineConfig\x12\n\n\x02id\x18\x01 \x01(\t\x12\x45\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x37.m1l0_services.dataservice.v1.DataServiceCollectRequestb\x06proto3'
  ,
  dependencies=[m1l0__services_dot_dataservice_dot_v1_dot_data__service__pb2.DESCRIPTOR,])




_PIPELINECONFIG = _descriptor.Descriptor(
  name='PipelineConfig',
  full_name='m1l0_pipeline.v1.PipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='m1l0_pipeline.v1.PipelineConfig.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='m1l0_pipeline.v1.PipelineConfig.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=201,
)

_PIPELINECONFIG.fields_by_name['data'].message_type = m1l0__services_dot_dataservice_dot_v1_dot_data__service__pb2._DATASERVICECOLLECTREQUEST
DESCRIPTOR.message_types_by_name['PipelineConfig'] = _PIPELINECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PipelineConfig = _reflection.GeneratedProtocolMessageType('PipelineConfig', (_message.Message,), {
  'DESCRIPTOR' : _PIPELINECONFIG,
  '__module__' : 'm1l0_pipeline.v1.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:m1l0_pipeline.v1.PipelineConfig)
  })
_sym_db.RegisterMessage(PipelineConfig)


# @@protoc_insertion_point(module_scope)
