site_name: napari-labelimg4classification
site_description: Image-Level labeling tool
site_author: Hiroki Kawai

theme: readthedocs


repo_url: https://github.com/hiroalchem/napari-labelimg4classification

pages:
- Home: index.md
