[tool.poetry]
name = "spylib"
version = "0.3.2"
description = "A library to facilitate interfacing with Shopify's API"
authors = ["Anthony Hillairet <ant@satel.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.65.1"
httpx = "^0.18.1"
loguru = "^0.5.3"
tenacity = "^7.0.0"
shortuuid = "^1.0.1"
nest-asyncio = "^1.5.1"
PyJWT = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
mypy = "^0.812"
mypy-extensions = "^0.4.3"
flake8 = "^3.9.2"
flake8-isort = "^4.0.0"
python-box = "^5.3.0"
requests = "^2.25.1"
watchdog = "^2.1.2"
PyYAML = "^5.4.1"
argh = "^0.26.2"
black = "^21.5b2"

[build-system]
requires = ["poetry-core>=1.0.0", "flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "spylib"
author = "Anthony Hillairet"
author-email = "ant@satel.ca"
home-page = "https://github.com/SatelCreative/satel-spylib"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"


[tool.black]
line-length = 99
skip-string-normalization = true

[tool.isort]
profile = "black"
known_third_party = ["fastapi", "pydantic", "starlette"]
