[tool.poetry]
name = "unconcealment"
version = "0.7.1"
description = "unconcealment"
authors = ["adioss <adrien.pailhes@outlook.com>"]
license = "GPLv3"

[tool.poetry.scripts]
main = "unconcealment:main"

[tool.poetry.dependencies]
python = "^3.8"
argparse = "^1.4.0"

[tool.poetry.dev-dependencies]
pylint = "^2.12.1"
safety = "^1.10.3"
bandit = "^1.7.1"
mypy = "^0.910"
coverage = "^6.2"

[tool.semantic_release]
version_variable = ["pyproject.toml:version"]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "python -m pip install --upgrade pip && pip install poetry && poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
