# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['kwargs2str', 'sorted_dict']

# Cell
from .imports import *

# Cell
def kwargs2str(**kwargs):
    "kwargs to string split with `,`"
    str_list = [f"{k}: {v}" for k, v in kwargs.items()]
    return ", ".join(str_list)

# Cell
def sorted_dict(x, comp='key', **kwargs):
    comp_index = 1 if comp == 'value' else 0
    sorted_x = dict(sorted(x.items(),key=operator.itemgetter(comp_index), **kwargs))
    return sorted_x