name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: pip install build
      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
