
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T14:21:47-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e3b1ad36e19c6d0da75a995c120eb26c746064a",
 "version": "5.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
