# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CloudSettings(Model):
    """CloudSettings.

    :param priority_config:
    :type priority_config: ~designer.models.PriorityConfiguration
    :param hdi_run_config:
    :type hdi_run_config: ~designer.models.HdiRunConfiguration
    :param sub_graph_config:
    :type sub_graph_config: ~designer.models.SubGraphConfiguration
    :param ap_cloud_config:
    :type ap_cloud_config: ~designer.models.APCloudConfiguration
    :param scope_cloud_config:
    :type scope_cloud_config: ~designer.models.ScopeCloudConfiguration
    """

    _attribute_map = {
        'priority_config': {'key': 'priorityConfig', 'type': 'PriorityConfiguration'},
        'hdi_run_config': {'key': 'hdiRunConfig', 'type': 'HdiRunConfiguration'},
        'sub_graph_config': {'key': 'subGraphConfig', 'type': 'SubGraphConfiguration'},
        'ap_cloud_config': {'key': 'apCloudConfig', 'type': 'APCloudConfiguration'},
        'scope_cloud_config': {'key': 'scopeCloudConfig', 'type': 'ScopeCloudConfiguration'},
    }

    def __init__(self, *, priority_config=None, hdi_run_config=None, sub_graph_config=None, ap_cloud_config=None, scope_cloud_config=None, **kwargs) -> None:
        super(CloudSettings, self).__init__(**kwargs)
        self.priority_config = priority_config
        self.hdi_run_config = hdi_run_config
        self.sub_graph_config = sub_graph_config
        self.ap_cloud_config = ap_cloud_config
        self.scope_cloud_config = scope_cloud_config
