
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T14:36:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "91c979e2b4c6f70234117982a1ae5b3d505c0813",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
