
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-02T14:30:34-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb60c4d8584dae9c1d5afd91e3a3261432a313d9",
 "version": "1.8.7-dev.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
