
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-28T10:23:01-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c423403d216556ab2dfa02a7992d202e985fb2d",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
