
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-29T08:22:55-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7a9250967bd2fd8f0b521e6e895045ba0e35421",
 "version": "4.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
