[tool.poetry]
name = "nbox"
version = "0.2.4"
description = "ML Inference 🥶"
authors = [
            "NBX Research <research@nimblebox.ai>",
            "Yash Bonde <bonde.yash97@gmail.com>",
            "Aakash Kaushik <kaushikaakash7539@gmail.com>"
          ]

[tool.poetry.dependencies]
python = "^3.6"
randomname = "^0.1.3"
rich = "^10.7.0"
requests = "^2.25.1"
numpy = "^1.19.5"
Pillow = "^8.3.2"
skl2onnx = "^1.9.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = [
  "poetry-core>=1.0.0",
  "setuptools"
]

build-backend = "poetry.core.masonry.api"
