[tool.poetry]
name = "collegra"
version = "0.1.0"
description = "Collaborative Learning Graphs"
authors = ["Bob Kraft <bkraft4257@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
bump2version = "^1.0.1"
watchdog = "^2.1.6"
flake8 = "^4.0.1"
tox = "^3.24.4"
black = "^21.11b1"
twine = "^3.7.0"
Sphinx = "^4.3.1"
coverage = "^6.2"
wheel = "^0.37.0"
pip = "^21.3.1"
pydantic = "^1.8.2"
typer = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
