[tool.poetry]
name = "minecraft_server_updater"
version = "0.1.0"
description = "pull down most recent server jar file (for Java edition)"
authors = ["Ryan <citizen.townshend@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
beautifulsoup4 = "^4.8.2"
click = "^7.0"
click_log = "^0.3.2"
click-spinner = "^0.1.8"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
msu = 'minecraft_server_updater:main'
