[tool.black]
line-length = 80
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80

[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
# disallow_any_generics = true # disabled due to issues with numpy < 1.20
warn_return_any = true
# warn_unused_ignores = true # can't be run on CI due to windows having different ctypes

[[tool.mypy.overrides]]
module = [
    'tqdm.auto',
    'pandas',
    'ujson',
    'numpy', # these two are required for py36, which numpy 1.21 doesn't support
    'numpy.random'
    ]
ignore_missing_imports = true
