repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies: [
          'flake8-docstrings==1.6.0',
          'flake8-executable==2.1.1',
      ]
