[tool.poetry]
name = "uberduckapi"
version = "0.1.1"
description = "Python wrapper for uberduck API"
authors = ["George <mazzeogeorge@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
polling = "^0.3.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
