
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-28T02:13:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "63c18670e4d46414eb3b5917fb0632e09bc3f8ed",
 "version": "0.9.dev2148"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
