[tool.poetry]
name = "inf_0008_custom_orm-team-3"
version = "0.1.0"
description = ""
authors = ["Belligraf <belligraf@mail.ru>"]
packages = [
    { include = "inf_0008_custom_orm-team-3" }
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
APPLICATION-NAME = 'entry:main'
